### ISSUE TITLE
Suggestion to export as .srt subtitle file

### ISSUE THREAD

**Issue by lucasbr15** [chidiwilliams/buzz#100]
Hello, I would like to make a suggestion for your app, it would be interesting to add an option to export as an .srt file, this other repository offers an option to export srt https://github.com/ahmetoner/whisper-asr-webservice another thing would be nice to integrate cuda, for gpu acceleration for a faster inference, and as a last suggestion add an option of "dark theme" is everything, thank you.

**Comment by chidiwilliams** [comment]
Hey, thanks for all the suggestions. I have plans to add SRT export support in the next few days (https://github.com/chidiwilliams/buzz/pull/98#issuecomment-1283582795). I'll also have a look at integrating Cuda for faster inference. On dark theme, what OS are you using? I believe the app should support dark theme based on your system's theme.
