### ISSUE TITLE
Trojan in latest Windows release 1.2

### ISSUE THREAD

**Issue by Bruce33333** [chidiwilliams/buzz#1010]
Trojan:Win32/Wacatac.B!ml 
Listed twice as: "Severe" in Windows scan of unzipped .exe file

Same response when tried several times. Should this be ignored?
When both trojans are removed, unzipped file won't run and quickly disappears.

**Comment by raivisdejus** [comment]
@Bruce33333 The installation file was downloaded from the releases section? https://github.com/chidiwilliams/buzz/releases

Installation files for Windows are not signed, so windows will warn you about that. It is safe to ignore that warning and click "Run anyway"

Security tools should not detect any trojans or security issues. You can try downloading the installation zip again from the releases section.

sha256 sum of the zip file should be `6a44c0b2ba35a9ce822124fe87b4746f22e673baa2bf07e537b9829ab6b9ace0`
sha256 sum of the `Buzz-1.2.0-windows.exe` should be `bbc37eb36c517d3e9f25d5d247728a2684f355ae8702dcac85c45e7f332b8244`

Command co check the SHA256 sum of the file `certutil -hashfile .\Buzz-1.2.0-windows.exe SHA256`

Windows defender on Windows 10 did not detect any issues with the file from releases section

**Comment by Bruce33333** [comment]
Re d/l and everything now works fine. 
Not sure what exactly happened but it must have been on my end.
Nice to see you here and appreciate the work you are doing.
