### ISSUE TITLE
Setting to limit maximum subtitle text length

### ISSUE THREAD

**Issue by mmindenhall** [chidiwilliams/buzz#1012]
Hi,

I'm using Buzz to generate SRT subtitles for audio tracks.  The subtitles will be displayed within a custom audio player that could be running on a desktop, tablet, or phone.  When running on a phone, it's important to limit the maximum length of any given subtitle that's generated so the full subtitle text will fit within the allocated space at a readable font size.  In some of the output files, I see individual subtitles as long as 110-120 characters, which is too much to display on the phone.

It would be great to have a setting to ensure that the maximum subtitle length does not exceed a specified limit.  For example, suppose Buzz currently produces SRT file output like this:

```
1
00:00:00,000 --> 00:00:08,480
The maximum length of a single subtitle should be limited to a specified number of characters. 
```

With the subtitle character limit set to 60 characters, Buzz would produce output looking something like this:

```
1
00:00:00,000 --> 00:00:06,000
The maximum length of a single subtitle should be limited  

2
00:00:06,000 --> 00:00:08,480
to a specified number of characters. 
```

BTW I experimented with using the "Initial Prompt" (Settings -> Folder Watch -> Advanced) setting to do this, but when I enter anything in the initial prompt, it seems to override a prompt from the application, and produces erratic results.  If it's possible to write a good prompt to do this, please feel free to suggest that as an alternative to the requested setting.

Thanks so much for building this great tool!

**Comment by raivisdejus** [comment]
@mmindenhall Make sure you are using the latest `1.2.0` version and try the resize function on the screen where you see individual subtitles. 
![attels](https://github.com/user-attachments/assets/a0e4886a-0eec-4071-9482-17bb7f933f24)


Resize button currently has very basic subtitle resizing that will limit max subtitle length to a specified number of characters.

There is one upcoming feature planned that will integrate https://github.com/jianfch/stable-ts and give us ability to specify more advances rules on how to resize and post-process already generated subtitles.
