### ISSUE TITLE
Can buzz.exe for windows use Gpus for computation, and if so, how

### ISSUE THREAD

**Issue by Akari00000** [chidiwilliams/buzz#1021]

**Comment by raivisdejus** [comment]
@Akari00000 Latest version `1.2.0` of Buzz on Windows will automatically use GPU for all model types except Faster Whisper. 

Please not that Windows task manager will not show much GPU usage, so to check if it is using the GPU look at the GPU Memory usage.

GPU support for Faster Whisper on Windows will come with some future improvement.

**Comment by Akari00000** [comment]
@raivisdejus Thank you, I tested the Whishper Large-v3 model on the computer and made sure that buzz.exe ran the model on the GPU.
I have another small question for you. The large-v3 model takes up 10GB of memory on the GPU, which is probably more than my personal computer can handle :). Is it possible for a normal computer like my 6GB laptop to run buzz.exe on a GPU, or should I use a model that requires less memory?

**Comment by raivisdejus** [comment]
@Akari00000 Faster whisper tends to use less VRAM than the regular Whisper try that. Also the Turbo models tend to require less VRAM and their quality is just a little less good as the full models, you can also try that. 

If you need the best quality, run the largest model on CPU, will be slow but the quality will be there. 

In the very latest development version I have updated Faster whisper to a version that supports Turbo models on a GPU, Can also try that https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version
