### ISSUE TITLE
Exe gets detected as a virus

### ISSUE THREAD

**Issue by punk1234567** [chidiwilliams/buzz#1028]
Hi, 

Everytime i launch the exe, it gets detected as a virus and gets deleted. Please advise. Thanks.

**Comment by raivisdejus** [comment]
@punk1234567 We get reports like this from time to time. 

To make sure you get the correct installation file download it from https://github.com/chidiwilliams/buzz/releases/latest 
Second thing you can do is check md5 sum of the downloaded file. Windows installation `.zip` file should have this md5 hash `6a4e5bd394c53f436cd89b8bd9c64374  Buzz-Windows-X64.zip`

Also note that windows file is not signed, so you will get a warning about that. For this you should select  `More info` -> `Run anyway`. But the file should not be detected as virus.

**Comment by raivisdejus** [comment]
I re-uploaded the release installation files and their md5 sum files, so you can check if the downloaded file is downloaded correctly.

Switched `.zip` files to extracted `.exe` and `.dmg` so it is one less step to install.
