### ISSUE TITLE
Add stable-ts support for more accurate timing

### ISSUE THREAD

**Issue by Nisekoi-1** [chidiwilliams/buzz#139]
https://github.com/jianfch/stable-ts

**Comment by chidiwilliams** [comment]
Would you want this supported both in the live transcription and file export?

**Comment by Nisekoi-1** [comment]
File export

**Comment by Nisekoi-1** [comment]
> Would you want this supported both in the live transcription and file export?

File export

**Comment by hansnolte** [comment]
"_Add stable-ts support for more accurate timing_"
That would really be of great help

Btw.
Hi chidiwilliams,
many thanks for Buzz.
Love it!

**Comment by chidiwilliams** [comment]
Released in v0.5.5: https://github.com/chidiwilliams/buzz/releases/tag/v0.5.5
