### ISSUE TITLE
Add large model selection in the "import audio file" option, please

### ISSUE THREAD

**Issue by leonelcba** [chidiwilliams/buzz#142]
Can you please add the large model selection in the import audio file option?
There are many errors when transcribing in high quality. It's not enough for an accurate transcription.
I could see that the first versions of Buzz had the large model as an option, but they didn't allow to import audios.

**Comment by chidiwilliams** [comment]
I removed it earlier because the larger models had high RAM requirements and seemed to crash on some PCs. I'll add it back in the next release.

**Comment by leonelcba** [comment]
Thank you so much 💯
