### ISSUE TITLE
SegFault Mac Book Pro 16 inch intel

### ISSUE THREAD

**Issue by MyraBaba** [chidiwilliams/buzz#144]
Downloaded app but give segFault

Mac OS : Catalina

<img width="873" alt="Screen Shot 2022-11-07 at 10 34 24" src="https://user-images.githubusercontent.com/17505439/200251983-8d4ca791-cf20-40d6-8a20-df251da2ff47.png">
<img width="1261" alt="Screen Shot 2022-11-07 at 10 35 38" src="https://user-images.githubusercontent.com/17505439/200252054-3dab0c35-c4c9-4e91-97dc-3c5097e14e1e.png">

**Comment by chidiwilliams** [comment]
Thanks for the report. Can I ask if you're able to run from source?

**Comment by MyraBaba** [comment]
I will try, is there a requirements.txt for pip3?

**Comment by chidiwilliams** [comment]
Added here https://github.com/chidiwilliams/buzz/blob/main/requirements.txt
