### ISSUE TITLE
Buzz 0.5.4 does not create a "srt" file.

### ISSUE THREAD

**Issue by OlafausBerlin** [chidiwilliams/buzz#158]
I used the "Very High Mode" and the "High Mode" to transcribe a video wit automatic language detection.
The process in both cases seems to work, but at the end i did not get a "srt" file and no error messages.
I uninstalled Buzz 0.5.4 and reinstalled it, but no changes.
The i reinstalled Buzz 0.5.3 and everything works fine.

By the way, thanks for "Buzz".
A brilliant piece of software. Easy to install and easy to use.

**Comment by OlafausBerlin** [comment]
I just found your fix:
https://github.com/chidiwilliams/buzz/issues/152
after i send my issue.
Sorry for that. I have to test the fix.

**Comment by OlafausBerlin** [comment]
The fix works fine.
"srt" files were created.
Thank you.

**Comment by chidiwilliams** [comment]
Great to hear it worked fine. The fix should be available in the next release.
