### ISSUE TITLE
new version 0.5.5 does nothing

### ISSUE THREAD

**Issue by sonkite225** [chidiwilliams/buzz#161]
new version 0.5.5 does nothing (in file mode, mic i dont know)

open file, make settings, click on run... nothing happens

**Comment by chidiwilliams** [comment]
Do you have `Enable GGML inference` on in the Settings? Also, do you see anything interesting in the logs at `C:\Users\{your user}\AppData\Local\Buzz\Buzz\logs.txt`?

**Comment by leonelcba** [comment]
![Captura de pantalla 2022-11-13 111643](https://user-images.githubusercontent.com/117379507/201526454-3b518168-5441-41cc-a2a1-d894843c8f3e.png)

The new version doesn't open for me

**Comment by chidiwilliams** [comment]
> ![Captura de pantalla 2022-11-13 111643](https://user-images.githubusercontent.com/117379507/201526454-3b518168-5441-41cc-a2a1-d894843c8f3e.png)
> 
> The new version doesn't open for me

Yes this has been reported in #157, and should be fixed in the next release.

**Comment by chidiwilliams** [comment]
Here: https://github.com/chidiwilliams/buzz/releases/tag/v0.5.7

**Comment by leonelcba** [comment]
> Here: https://github.com/chidiwilliams/buzz/releases/tag/v0.5.7

Windows antivirus detects a virus in this version :(

**Comment by chidiwilliams** [comment]
That's unfortunate, as it must have to do with the code signing and I'm currently not willing the pay $100/year for the cert. I've added the build files to the release (check for the .tar.gz file [here](https://github.com/chidiwilliams/buzz/releases/tag/v0.5.7)). You can unzip and run the .exe file directly from there. Alternatively, you can check to see if the installer in version 0.5.3 works for you. I believe that was the version before the issue you reported came up.

**Comment by sonkite225** [comment]
> Do you have `Enable GGML inference` on in the Settings? Also, do you see anything interesting in the logs at `C:\Users\{your user}\AppData\Local\Buzz\Buzz\logs.txt`?

no, ggml wasnt on, and no, in log nothing special...

i try new version 0.5.7 now :)

**Comment by sonkite225** [comment]
soo,
the 0.5.7 has not worked after the overinstall again. after the click on run happened again nothing at all.

but: after complete uninstallation of buzz, and subsequent reinstallation it works fine again.
with and without GGML by the way :)

**Comment by chidiwilliams** [comment]
@sonkite225 That's great to hear. And thanks for getting back to me.

**Comment by sonkite225** [comment]
it seems that it is better to completely uninstall the old version first with every new version that comes along. it seems that problems occur more often with over-installing.

if this can be confirmed it would be good to note this on the info :)

**Comment by sonkite225** [comment]
> @sonkite225 That's great to hear. And thanks for getting back to me.

np 

it seems that it is better to completely uninstall the old version first with every new version that comes along. it seems that problems occur more often with over-installing.

if this can be confirmed it would be good to note this on the info :)

**Comment by chidiwilliams** [comment]
Good point. I'll investigate a bit more and update docs as well, thanks.

**Comment by leonelcba** [comment]
> That's unfortunate, as it must have to do with the code signing and I'm currently not willing the pay $100/year for the cert. I've added the build files to the release (check for the .tar.gz file [here](https://github.com/chidiwilliams/buzz/releases/tag/v0.5.7)). You can unzip and run the .exe file directly from there. Alternatively, you can check to see if the installer in version 0.5.3 works for you. I believe that was the version before the issue you reported came up.

The .tar.gz file works! I hope the exe file can work in the future 💯
