### ISSUE TITLE
bug on windows with GGML

### ISSUE THREAD

**Issue by sonkite225** [chidiwilliams/buzz#169]
have just tested it several times.

ggml files are downloaded even when ggml is turned off.
if ggml is on, and the files are downloaded correctly, the processing window comes on, the cpu load increases to 100% but NOTHING happens. the process bar does not go on and nothing happens.

if you turn off ggml it seems to be used anyway, because when i choose the language exactly the same happens (so nothing ^^ except 100% cpu) 

but if you take language auto detection it works normal again (auto detection obviously doesn't work with ggml and so it's definitely not taken)

oh, and even if i disabled ggml, after restarting buzz it is active again. would be better if it was disabled by default, or saves the selected state.

but most of all it would be good if buzz won't use ggml when it's turned off, but it will still use it when a language is selected :)

so now was some, hope that comes across understandable in english ^^

Translated with www.DeepL.com/Translator (free version)

**Comment by chidiwilliams** [comment]
That's sad :(

Could you try this release and let me know what you get in the logs? https://github.com/chidiwilliams/buzz/releases/tag/v0.5.8

Do you see an "ImportError"? Also what do you get in the log lines that start with "Loading model = ..." and "Model path = ..." when you try to transcribe?

**Comment by sonkite225** [comment]
sorry that I write only now, was unfortunately something sick...

unfortunately it is the same behavior as before.

if ggml was activated once in the settings it stays in.
even if i deactivate it it is set active again after restarting the program.
and it seems to stay active even if i deactivate it in the running program, without restarting, because as soon as i choose a language (in my case german) ggml is still used and it comes back to the problem that the processor runs at full load, but no progress is made and it has to be cancelled manually.

only when I use auto language select it works, because there no ggml can be used.

then i tested the following: buzz reinstalled. ggml is then off by default. if i never activate it, then i can also choose a language and ggml is not used. but once it has been activated! you can't get rid of ggml by deactivating it, except by reinstalling!

so again briefly summarized:

1. if ggml was activated once! after the installation of buzz it remains active, even if the hook is removed. always! and that until buzz is reinstalled.

2. ggml does not work, processor load increases to 99-100% but no progess > 0

so it should be fixed that 1. ggml can really be deactivated without reinstalling and 2. that ggml runs at all ^^

hope this helps a little further :)

i post a log separately. 
LG

**Comment by sonkite225** [comment]
oh, and one question, why not all 5 whisper models and same names?

**Comment by sonkite225** [comment]
no, no Buzz.plist there

**Comment by chidiwilliams** [comment]
I think I understand what the issue here was now. Could you try downloading the Windows build at the bottom of this page: https://github.com/chidiwilliams/buzz/actions/runs/3513223957?

Then try to turn off/on GGML inference on the menu and let me know what you get. Thanks.

**Comment by sonkite225** [comment]
oh yes :)
that is far better.
GGML itself still doesn't work, but the ggml settings are now really disabled when deactivated and this remains even after restarting the program.
so defacto buzz doesn't need to be reinstalled anymore if you had ggml active once and it doesn't work for you.

the new reset settings function did not even have to be used :)

if now still sometime ggml is brought to run it is perfect :) 

Thx :)

**Comment by chidiwilliams** [comment]
@sonkite225, can you use whisper.cpp in this release? https://github.com/chidiwilliams/buzz/releases/tag/v0.8.0

**Comment by sonkite225** [comment]
no :(
just jumps to completed and is empty

**Comment by sonkite225** [comment]
also faster whisper dont work. it produces an "unknown error"
