### ISSUE TITLE
Feature: CMD

### ISSUE THREAD

**Issue by amichelis** [chidiwilliams/buzz#170]
It would be excellent to be able to work directly on cmd.
Keep the good work.

**Comment by sonkite225** [comment]
for that you can use whisper by itself.
whithout buzz gui

**Comment by amichelis** [comment]
The problem with Whisper is that you have to install lot of things.
Python, Pip, download the models, etc.. and Buzz is excellent because is just all in one tool. Great for those who need GUI but if you use CMD it would be great too.
