### ISSUE TITLE
User experience design

### ISSUE THREAD

**Issue by kohasummons** [chidiwilliams/buzz#172]
Hey heyy! ☘️ Tried my hands on [ possible improvements](https://www.figma.com/file/QvTccUX1vaTxYe4qZPLwrN/Buzz?node-id=1%3A2) to buzz's UX. Would this be a contribution that fits into your roadmap...

**wireframes**
![A screengrab of proposed buzz wireframe](https://user-images.githubusercontent.com/66284362/201778440-8064b25a-740a-40eb-8c42-f9a1f612290a.png)

**Comment by chidiwilliams** [comment]
Hi, thanks for these, but the project is constrained by the use of desktop widgets such that it would be difficult (or probably impossible) to style as you've shown. If it were a web project, I would have been more flexible with the design from the start, but desktop widgets aren't as easy to style as web elements, and I wanted the app to look native to both Mac and Windows. That said, adding a Recent tab is something I had in mind, and I might look into it eventually if I get some more time. Thanks.
