### ISSUE TITLE
Possible to add new fields

### ISSUE THREAD

**Issue by MbuguaDavid** [chidiwilliams/buzz#175]
Hi,
Is it possible to add new fields to Buzz? 
It would be awesome to set the number of characters per line and also the number of lines per subtitle block. 

![new fields](https://user-images.githubusercontent.com/92556454/201891505-b45a01d9-1da6-4ee7-8dec-3a3fc0cfe78b.png)

Something like above, with input fields.

Like what we have here.

![max characters per line](https://user-images.githubusercontent.com/92556454/201891588-1b45f340-86fd-4a83-bb5c-eb527c91c6e9.png)

![lines break](https://user-images.githubusercontent.com/92556454/201891665-9fe92d1f-e86b-4c8c-8a51-2f41e79ef3b3.png)

Thanks for the updates. :)

**Comment by chidiwilliams** [comment]
Hi, thanks. I'm not quite sure what "Max lines per card" means.

**Comment by MbuguaDavid** [comment]
> Hi, thanks. I'm not quite sure what "Max lines per card" means.

It means you can choose to have 1 line per subtitle or up to 10 lines if you want to. The standard is 2 lines per "card" or subtitle block. 
Thanks!
