### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by pluja** [chidiwilliams/buzz#176]
It would be awesome if we could have a Linux version of Buzz. You could look at [AppImage](https://appimage.org/) or [FlatPak](https://flatpak.org/) to generate the packages.

**Comment by pluja** [comment]
Also, this could be of your interest since you are using poetry:
https://github.com/flatpak/flatpak-builder-tools/tree/master/poetry

**Comment by peepo5** [comment]
Yes, would be nice, especially because original whisper is shown by demo on linux.

**Comment by chidiwilliams** [comment]
Hi, yes, Buzz initially had a Linux version, but I had to remove it as it had some bugs, and I could not replicate as I don't have a Linux desktop to test: https://github.com/chidiwilliams/buzz/issues/116. I'll give it another go soon.

**Comment by peepo5** [comment]
Linux is pretty easy to emulate for testing, there is windows subsystem for linux, or you can boot it straight off of a USB or VM.

**Comment by faveoled** [comment]
The app runs on Linux using poetry instructions (tested just now)

**Comment by pluja** [comment]
As I was unable to easily use this on Linux, I built a similar web-based app which can be used on any platform supporting Docker: https://codeberg.org/pluja/web-whisper
