### ISSUE TITLE
when launched the app says unhandled exception in script (windows)

### ISSUE THREAD

**Issue by alanyin233** [chidiwilliams/buzz#183]
![Capture](https://user-images.githubusercontent.com/77308148/203778438-8bbf9284-b1f8-4da2-a2bb-7a5c45f18514.JPG)

**Comment by alanyin233** [comment]
after the app launched, no matter how the options i chose it just crashed when i clicked the record button. Except the pic here there is another pop-up window behind this one and is trying to download some resources. After i close this pic here these pop-up windows all gone.

**Comment by chidiwilliams** [comment]
Hey, it seems like the app is unable to download the Whisper models for some reason. Let me add some debugging to see if we can figure out what the issue is.

**Comment by Pokem0n2** [comment]
> after the app launched, no matter how the options i chose it just crashed when i clicked the record button. Except the pic here there is another pop-up window behind this one and is trying to download some resources. After i close this pic here these pop-up windows all gone.

We're facin' the TOTALLY SAME issue, buddy. I'd guess dat u are Chinese? So... just cut the VPN, net booster or some, then rerun this program, bro. Best wishes! :-b
