### ISSUE TITLE
ModuleNotFoundError: No module named 'stable_ts.stable_whisper'

### ISSUE THREAD

**Issue by jordimas** [chidiwilliams/buzz#184]
mac OS 

when trying to build from source I get the error:

ModuleNotFoundError: No module named 'stable_ts.stable_whisper'

It looks like that stable_ts may be missing as dependency

**Comment by chidiwilliams** [comment]
Could you try running `git submodule init`? `stable-ts` is added as a Git submodule instead of a Python dependency. I should update the docs for that soon.

**Comment by jordimas** [comment]
Yes, this fixes the issue. I made a PR to improve the documentation. Thanks

**Comment by chidiwilliams** [comment]
Seen, thanks!
