### ISSUE TITLE
Allow Buzz UI to be translated to other languages

### ISSUE THREAD

**Issue by jordimas** [chidiwilliams/buzz#188]
It will be great if Buzz can be translated to different languages for non-native English speakers.

I can prepare a PR using the standard Python Lib/gettext.py library and providing the first translation as example

Does this work?

**Comment by chidiwilliams** [comment]
That would be a wonderful addition, thanks.

**Comment by jordimas** [comment]
See: https://github.com/chidiwilliams/buzz/pull/193/files

**Comment by chidiwilliams** [comment]
Hi, @jordimas. Thanks for your work on this. I've gotten some time and pulled in your changes into #306. If you could help update the [locale file](https://github.com/chidiwilliams/buzz/blob/main/locale/ca_ES/LC_MESSAGES/buzz.po) further in a new PR, that would be really helpful. Thanks.

**Comment by jordimas** [comment]
Thanks so much for your work. 
I created the PR: https://github.com/chidiwilliams/buzz/pull/307
