### ISSUE TITLE
What about the less-than-ideal results?

### ISSUE THREAD

**Issue by zhl111** [chidiwilliams/buzz#198]
I would like to know that this software recognizes very few voices and many are missed. And it's very slow and not very accurate. What should I do if I like to change these problems? The virtual audio software I use is the free version, does this cause problems with recognition? Do I need to change to another software?
![image](https://user-images.githubusercontent.com/29135984/205116662-af2a7696-5440-4386-abff-173948d8d21a.png)
![image](https://user-images.githubusercontent.com/29135984/205201770-5552f879-3760-4db1-8123-9e693ba05ce0.png)

**Comment by chidiwilliams** [comment]
Could you try selecting a language, instead of using "Detect Language"?
