### ISSUE TITLE
"Enable GGML Interface" is gray

### ISSUE THREAD

**Issue by happyTonakai** [chidiwilliams/buzz#200]
Hi, on my Windows PC the setting "Enable GGML Interface" is gray. Any prerequisites to enable this option? I've downloaded [ggml-model-whisper-tiny.bin](https://ggml.buzz.chidiwilliams.com/ggml-model-whisper-tiny.bin) and put it in `C:\Users\<username>\AppData\Local\Buzz\Buzz\Cache`.

What should I do next? Thanks.

**Comment by chidiwilliams** [comment]
This should be fixed in an upcoming version. I'll update this thread once it's out.
