### ISSUE TITLE
Access to actual large model

### ISSUE THREAD

**Issue by jjoergensen** [chidiwilliams/buzz#208]
If "High" uses the "medium" model, is there a way that I can get higher quality? I would like to use the large model. But how? Does it require modifying the code and rebuilding it? Or is there a trick?

**Comment by chidiwilliams** [comment]
Hi, yes, I had disabled this because the large models seemed to be crashing the application on some machines. There isn't really a workaround, so it'll need a new build/release.

**Comment by ashishbhateja** [comment]
I am also looking for a way to use the large model. I believe that the large v2 model was recently released. Due to nature of speaker accents/language, a less accurate model doesn't seem to work well in my use case.
