### ISSUE TITLE
Parallel Model Usage

### ISSUE THREAD

**Issue by thakurudit** [chidiwilliams/buzz#236]
I have created a websocket server and client for real-time transcription which uses python bindings mentioned [here](https://github.com/ggerganov/whisper.cpp/issues/9#issuecomment-1342138572). It seems to work fine with single client sessions (only 1 client connected to the server for transcription) but as soon as I create two multiple concurrent clients it throws a segmentation fault. 

**Note**: The segmentation fault occurs **only** when I create a global instance of `WhisperCpp` and pass the same instance for transcription for every client which is connected to the websocket server but If I create `WhisperCpp` instance every time a client connects to the server the error does not appear. The latter is not efficient as it fills up the system memory by creating N instances of whisper model where N is no. of clients.

> System: Macbook Air | M1 chip
> Python Version: 3.8

Error:-
```
GGML_ASSERT: /Users/apple/VsCodeProjects/whisper.cpp/ggml.c:4514: ne02 == ne12
GGML_ASSERT: /Users/apple/VsCodeProjects/whisper.cpp/ggml.c:4514: ne02 == ne12
GGML_ASSERT: /Users/apple/VsCodeProjects/whisper.cpp/ggml.c:4514: ne02 == ne12
GGML_ASSERT: /Users/apple/VsCodeProjects/whisper.cpp/ggml.c:4514: ne02 == ne12
Process 48661 stopped
* thread #26, stop reason = signal SIGABRT
    frame #0: 0x000000018df33224 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x18df33224 <+8>:  b.lo   0x18df33244               ; <+40>
    0x18df33228 <+12>: pacibsp 
    0x18df3322c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x18df33230 <+20>: mov    x29, sp
Target 0: (python) stopped.
```

**Comment by chidiwilliams** [comment]
Hey, I'm not sure, really. Could you create an issue/discussion in the Whisper.cpp project?
