### ISSUE TITLE
Support for Whisper finetuned models

### ISSUE THREAD

**Issue by jordimas** [chidiwilliams/buzz#241]
Huggingface is leading a community effort to fine tunning and improve Whisper for many languages. As result, many of these finetune models perform significantly better for specific languages that the original Whisper model.

See: https://huggingface.co/models?other=whisper-event

It will be really great to extend Buzz to support Whisper finetuned models. This will be important for many languages moving forward.

I participated in the HuggingFace community by finetuning the Whisper model for Catalan language, then if you have follow up questions, I may be able to help.

**Comment by chidiwilliams** [comment]
WIP: #262

**Comment by chidiwilliams** [comment]
Available in the latest version: https://github.com/chidiwilliams/buzz/releases/tag/latest
