### ISSUE TITLE
Running Whisper on Cloud GPU by 3rd Party Services

### ISSUE THREAD

**Issue by yigitkonur** [chidiwilliams/buzz#245]
It is unlikely that Whisper can be used on the cloud as an extra option, as it requires a powerful GPU to run efficiently. However, some software companies offer Whisper as an API, such as Replicate. This allows users to access Whisper's functionality without needing to have a powerful GPU. More information about using Whisper through Replicate can be found at the following link: https://replicate.com/openai/whisper.

**Comment by novmikvis** [comment]
I second that! [OpenAI recently released their official API](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) and it would be great to have an option to set up an API key and access larger models from the cloud. 

I tested out [a basic python setup with the API](https://platform.openai.com/docs/guides/speech-to-text) and was able to transcribe a 13 minute file in just one minute. Compared to my laptop using the medium model which took 58 minutes, the difference is massive. Even though the API isn't free, [the pricing](https://openai.com/pricing#audio-models) makes it a very viable option.

**Comment by Sircam19** [comment]
> I second that! [OpenAI recently released their official API](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) and it would be great to have an option to set up an API key and access larger models from the cloud.
> 
> I tested out [a basic python setup with the API](https://platform.openai.com/docs/guides/speech-to-text) and was able to transcribe a 13 minute file in just one minute. Compared to my laptop using the medium model which took 58 minutes, the difference is massive. Even though the API isn't free, [the pricing](https://openai.com/pricing#audio-models) makes it a very viable option.

Yes there are others similar to the company you cited. However, there are issues linked to cloud usage vs local processing (I.e. pricing, security,privacy etc). However, local transcription has been moving very rapily in terms of speed improvements. The work being carried out by Chidi and others will shrink the differences between offline and cloud offerings...just stay tuned :-)

**Comment by novmikvis** [comment]
It seems Cidi has added support for Whisper API: https://github.com/chidiwilliams/buzz/pull/371
![](https://i.imgur.com/JNYrfUm.png)
You can create API key [on the OpenAI Website](https://platform.openai.com/account/api-keys)
Currently they gift $18.00 for the new users.

The only thing to note is that the file size is currently limited to 25MB. But since we already have ffmpeg, I guess it would not be too hard to slice the files before sending them to the API.

@chidiwilliams Should I start a new issue with a slicing suggestion?

**Comment by chidiwilliams** [comment]
Yes, Whisper API is supported in v0.7.2. I'll have a look at slicing.
