### ISSUE TITLE
Unable to open Buzz app on Mac once installed

### ISSUE THREAD

**Issue by dimitryslavin** [chidiwilliams/buzz#25]
Have not been able to successfully open the Buzz app once it is in the Applications folder. Seems that this is likely an OS binary verification issue, but not familiar enough with the topic to be sure

**Comment by chidiwilliams** [comment]
Are you using a Mac M1/M2?

**Comment by dimitryslavin** [comment]
nope, am using a macbook pro (16 inch, 2019)

**Comment by yigitkonur** [comment]
Same here:

<img width="372" alt="CleanShot 2022-10-0
![CleanShot 2022-10-06 at 21 21 54@2x](https://user-images.githubusercontent.com/9989650/194410973-7015baea-d28f-4427-ae75-ec8f7e0bb6f8.png)
6 at 21 21 38@2x" src="https://user-images.githubusercontent.com/9989650/194410902-dac590ad-bb6d-4de1-98ca-770e9cd0eadb.png">

![CleanShot 2022-10-06 at 21 21 54@2x](https://user-images.githubusercontent.com/9989650/194411053-2795d718-59d6-4b02-90c8-f7513f10e8ab.png)

**Comment by chidiwilliams** [comment]
Thanks for the report. I'm able to replicate now. Looking into a fix.

**Comment by maccman** [comment]
also replicated - 
![CleanShot 2022-10-08 at 22 58 15@2x](https://user-images.githubusercontent.com/2142/194735581-c2d9b8cc-2b7b-4f84-b123-32b58dc0c98e.png)

**Comment by maccman** [comment]
also replicated - 
![CleanShot 2022-10-08 at 22 58 15@2x](https://user-images.githubusercontent.com/2142/194735581-c2d9b8cc-2b7b-4f84-b123-32b58dc0c98e.png)

**Comment by yigitkonur** [comment]
Yes, it runs the app now but when I start to record with large model in Turkish, it fails and crashes.

<img width="372" alt="CleanShot 2022-10-12 at 11 42 56@2x" src="https://user-images.githubusercontent.com/9989650/195322683-6a8f8f19-a821-4699-ac6c-eed52d2c7a22.png">

**Comment by chidiwilliams** [comment]
Does it run with the tiny or small model?

**Comment by yigitkonur** [comment]
Yes it does, but failing in large model.

**Comment by jjoergensen** [comment]
I have the same issue with the release binaries (failing on Apple silicon). But running it from source did work.

**Comment by chidiwilliams** [comment]
> Yes it does, but failing in large model.

Sure, looking into the issue with loading the large model.

**Comment by chidiwilliams** [comment]
> I have the same issue with the release binaries (failing on Apple silicon). But running it from source did work.

Yes, the challenge is GitHub Actions does not support Apple Silicon, and I don't own one myself, so I'm currently unable to make builds. I'll update this thread once I'm able to find a solution. Thanks.

**Comment by nixsiow** [comment]
I downloaded the release and installed it on my M1 Macbook Pro. It's working so far, I tested the transcription with a manually imported audio file. I haven't got time to configure and test the live transcription.

**Comment by chidiwilliams** [comment]
> I downloaded the release and installed it on my M1 Macbook Pro. It's working so far, I tested the transcription with a manually imported audio file. I haven't got time to configure and test the live transcription.

Great to hear!

**Comment by Sircam19** [comment]
> I downloaded the release and installed it on my M1 Macbook Pro. It's working so far, I tested the transcription with a manually imported audio file. I haven't got time to configure and test the live transcription.

I've been able to have it work on M1 Macbook and an Intel Mini no problems at all :-) and using the latest build.
