### ISSUE TITLE
Unable to load the Whisper model Aconnection error occurred.Pleaselretry or check the application logs for more inforrmationa

### ISSUE THREAD

**Issue by langyu0618** [chidiwilliams/buzz#250]
![20221216232501](https://user-images.githubusercontent.com/120570758/208132363-63edebf1-435d-4f4c-874a-080aaaa74d1f.jpg)

**Comment by chidiwilliams** [comment]
Related to https://github.com/chidiwilliams/buzz/issues/183?

**Comment by langyu0618** [comment]
I hope it can be installed and used on a computer without Internet

**Comment by dreampjk** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by chidiwilliams** [comment]
> I hope it can be installed and used on a computer without Internet

Yes, you only need to install the model once.
