### ISSUE TITLE
infinite "downloading resources"

### ISSUE THREAD

**Issue by rmichelena** [chidiwilliams/buzz#266]
macOS, v.0.6.4
I selected Transcribe, Spanish, Very High, Microphone
machine is MacBook Air M2, 24Gb RAM
as soon as I pressed "Record", it popped out a window showing "downloading resources", it's been a couple hours, it's still the same, says it's about a trillion percent progress in downloading :)
however it seems to have transcribed some loose words from a conversation I was having, don't know at what point it did.
Screenshot attached.
<img width="413" alt="Screenshot 2022-12-25 at 12 22 30" src="https://user-images.githubusercontent.com/77797875/209476907-1dc6e69a-9530-43a1-9a86-f8aef8e7da23.png">

**Comment by chidiwilliams** [comment]
This is being fixed in an upcoming version. What happens when you try with quality set to Very Low/Low?

**Comment by rmichelena** [comment]
I guess it's just an UI issue, when I look at ~/.cache/whisper I can see the large-v2.pt file is continuously growing so it's downloading, and it's roughly the same as the percentage shown. So the UI assumed a size of 1 byte and it's showing the percentage based on that.

But... it shouldn't do that when you press "record" and by all means it shouldn't keep the microphone open.
There should be some UI to download the models first.
Ideally, one would download the models independently (via URL, using the browser) and import them into Buzz.

**Comment by rmichelena** [comment]
And indeed my Mac shows the microphone is being used by Buzz all this time (hours) while "downloading resources".
And the transcription window shows some Spanish text (I had selected Spanish), while I've been totally silent, it seems to be text from some YouTube channel (it says the Spanish equivalent of  "suscribe", "buy this is the last chance"), this is eerie... I have no video running, and I'm alone now... it might have picked up words from some videos my wife was watching an hour ago, but also I don't recall such words...

**Comment by Zeesy** [comment]
Great app! Audio file transcription works impressively, but I have the same problem with "downloading resources" using live recording (from internal audio). 
English transcribe, high quality, RealTek ASIO (default internal input)
Windows 10, 32GB RAM, NVIDIA RTX 3090 24GB RAM

If it's a UI issue then it sounds like it's on Mac and Windows.

**Comment by chidiwilliams** [comment]
> Great app! Audio file transcription works impressively, but I have the same problem with "downloading resources" using live recording (from internal audio). English transcribe, high quality, RealTek ASIO (default internal input) Windows 10, 32GB RAM, NVIDIA RTX 3090 24GB RAM
> 
> If it's a UI issue then it sounds like it's on Mac and Windows.

Thanks! Does version 0.7.1 work for you?
