### ISSUE TITLE
Can Buzz be used from the command line in windows10 or Linux?

### ISSUE THREAD

**Issue by cc-qq-gg** [chidiwilliams/buzz#267]

**Comment by Conniverd** [comment]
I'd love that functionality too. I use ffastrans in windows 10, to generate proxy files for editing, and would love to have a command line based tool for transcription.

**Comment by TheTural** [comment]
Command line would be a killer addition to the app. Being able to bulk process a folder of videos and automatically output the transcripts in the desired format via a script would be tremendous for me. 

eg:
`buzz.exe -i videofile.mp4 -o videofile_transcript.srt -model Whisper -size Tiny -task Transcribe -lang EN`

**Comment by chidiwilliams** [comment]
CLI: https://github.com/chidiwilliams/buzz#add

At the moment, you still need to download the model first from the GUI or manually, but starting a command with the CLI should work now.
