### ISSUE TITLE
srt exports should use '00:01:02,123' instead of '00:01:02.123'

### ISSUE THREAD

**Issue by scateu** [chidiwilliams/buzz#278]
For example, '00:01:02.123' cannot be recognized by Aegisub software (which is, sort of, the de-facto software in subtitle editing.

Thanks for your work. I love it very much.

**Comment by i990049** [comment]
'00:01:02.123' can be recognized by subtitle edit，Aegisub only show '00:01:02.12'

**Comment by chidiwilliams** [comment]
Should be out in the next release. Thanks.

**Comment by scateu** [comment]
> '00:01:02.123' can be recognized by subtitle edit，Aegisub only show '00:01:02.12'

Thank you for the info. I'll try subtitle edit.

**Comment by scateu** [comment]
> Will be available in the next release. Thanks.

Thank you for the quick fix and happy new year.
