### ISSUE TITLE
Sounddevice is an unmet dependency

### ISSUE THREAD

**Issue by afonsoguerra** [chidiwilliams/buzz#28]
Traceback (most recent call last):
  File "/buzz/main.py", line 3, in <module>
    from gui import Application
  File "/buzz/gui.py", line 5, in <module>
    import sounddevice
ModuleNotFoundError: No module named 'sounddevice'

**Comment by chidiwilliams** [comment]
Did you follow this guide to install dependencies? https://github.com/chidiwilliams/buzz#buildrun-locally

**Comment by afonsoguerra** [comment]
Yes, I have used poetry. To be precise:
    git clone https://github.com/chidiwilliams/buzz
    cd buzz
    poetry install

**Comment by chidiwilliams** [comment]
And then do you run with

```shell
poetry run python main.py
```

**Comment by afonsoguerra** [comment]
> And then do you run with
> 
> ```shell
> poetry run python main.py
> ```

Yes.

**Comment by chidiwilliams** [comment]
I don't see why the dependency should be missing in that case. Maybe try running poetry install again?
