### ISSUE TITLE
Keeps closing when I click Record on Windows 10

### ISSUE THREAD

**Issue by regstuff** [chidiwilliams/buzz#29]
Doesn't really give any Error message or anything. Just sort of stalls for 10 seconds and then the Buzz window closes.
Any idea what the issue might be?
I have whisper already installed in a virtual environment. Is that the issue?

**Comment by chidiwilliams** [comment]
Could you try this release? https://github.com/chidiwilliams/buzz/releases/tag/v0.3.2
