### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by esonec** [chidiwilliams/buzz#305]
Is that possible to configure the recognition engine with custom vocabulary for terms, names and abbreviations?

**Comment by chidiwilliams** [comment]
Right now, it's theoretically possible if you're willing to write some NLP code. Buzz supports Hugging Face models, so you can train your models (https://discuss.huggingface.co/t/open-to-the-community-whisper-fine-tuning-event/26681) and import them into Buzz. But, yes, there isn't a way to load your own custom vocabulary in a way that is practical for most people.
