### ISSUE TITLE
Transcript is empty

### ISSUE THREAD

**Issue by TanteGerd** [chidiwilliams/buzz#308]
The download works, and I can open the program, but when I transcribe a file it creates a txt-file but its totally empty - what am I doing wrong?

**Comment by chidiwilliams** [comment]
- What version of the app are you using?
- Could you share a screenshot of what the app looks like after transcribing?
- Do you see any info in the app logs?

**Comment by xsiviso** [comment]
I have the same problem when I’m using the whisper.cpp model. After I press „run“ it’s immediately done and nothing is transcribed. 
The Version should be 0.7.1 (but it’s showing 0.7.0)
I use a M1 MacBook. How can I open the log file?
![0CAF2B9A-DF03-404B-8C58-E74370142B86](https://user-images.githubusercontent.com/108767747/210891556-81cce60d-dd11-4d86-9537-22b6b01a179d.jpeg)

**Comment by Sircam19** [comment]
> I have the same problem when I’m using the whisper.cpp model. After I press „run“ it’s immediately done and nothing is transcribed.
> The Version should be 0.7.1 (but it’s showing 0.7.0)
> I use a M1 MacBook. How can I open the log file?
> ![0CAF2B9A-DF03-404B-8C58-E74370142B86](https://user-images.githubusercontent.com/108767747/210891556-81cce60d-dd11-4d86-9537-22b6b01a179d.jpeg)


Hello friend... try the following link to see if that helps in understanding how to view the log file. I had the same issue a few days ago...so make sure you have the latest version... I've been transcribing for almost 2 days now, with the new version (download the latest dmg file) and had no problems since. Happy to help if not working. 

https://github.com/chidiwilliams/buzz/issues/292#issuecomment-1370164775

**Comment by Sircam19** [comment]
> The download works, and I can open the program, but when I transcribe a file it creates a txt-file but its totally empty - what am I doing wrong?

https://github.com/chidiwilliams/buzz/issues/292#issuecomment-1370164775

Scroll down the thread and look for a reference to .dmg which will allow you to download the latest and greatest :-)

**Comment by chidiwilliams** [comment]
Thanks, @Sircam19. I made a mistake with the release I pushed to Homebrew, but downloading the DMG from the latest release should work fine for you https://github.com/chidiwilliams/buzz/releases/tag/v0.7.1. Thanks!

**Comment by Piciok** [comment]
Hello! The same seems to be happening on the latest Windows 0.8.0 release. Each transcription performed with any CPP model ends very quickly, is marked as complete but is empty.
Any help would be greatly appreciated.
