### ISSUE TITLE
The clear history button should show a warning message.

### ISSUE THREAD

**Issue by dhysuiej** [chidiwilliams/buzz#310]
Unfortunately I clicked the clear history button thinking it would remove only the selected row, but it removed all the completed transcriptions. I lost like about 10 transcriptions with about 10 minutes of conversation each, it was like about an hour waisted because now I have to start the process with those audio files again. I think there should be a warning message stating clearly that all the completed transcriptions will be lost, and that the action can't be undone.

**Comment by AlmostHuman34** [comment]
Same, is there any way to recover the ones that were deleted from the list? I made many transcriptions and left home, when I got back I tried to delete the old ones but it deleted all of them, so roughly around 10 hours of it. Add option to separate deletion please.

**Comment by chidiwilliams** [comment]
@dhysuiej @AlmostHuman34, I'm so sorry to hear. Unfortunately, there isn't one in the latest version. I'm working to separate deletion and add a warning message as well. Thank you.
