### ISSUE TITLE
Awesome app~ small feature requested: "Save / Export all" button

### ISSUE THREAD

**Issue by shruru** [chidiwilliams/buzz#314]
Now it's supported batch files input, however when they are all finished, you have to click the third icon for exporting srt / txt file one by one. 😂 I got 50 files..
so if it's possible to have a button like "Export" all , or at least enable the "multiple files selection" for exporting srt files.
hope you can consider this feature. 

Thanks in advance~

**Comment by Zeesy** [comment]
Love this app, sharing it with people who work with sensitive info and appreciate local transcription. This would be a lovely feature to add.
