### ISSUE TITLE
Buzz not opening on Windows 7

### ISSUE THREAD

**Issue by buzzlover69** [chidiwilliams/buzz#322]
after installing i clicked on the desktop shortcut but does not open,it just does nothing.

**Comment by chidiwilliams** [comment]
What OS are you on? And how did you install?

**Comment by buzzlover69** [comment]
windows 7 after installation got an error saying api-ms-core-path-l1-1-0.dll missing downloade the file,now it doesnt show that error,now doesnt react at all when i click the shortcut on desktop

**Comment by chidiwilliams** [comment]
Unfortunately, Buzz requires Windows 8 or newer to run.
