### ISSUE TITLE
Whisper.cpp transcription crashing on Mac M1

### ISSUE THREAD

**Issue by AlanDinkle** [chidiwilliams/buzz#323]
I can open this software, but every time I click "record", the software crashes and flashes back. I installed it through homebrew, and the system version is Monterrey.

**Comment by jeansordes** [comment]
I have the same issue, I'm on MacOS on an M2 chip though (Macbook Air 2022)

I wonder if that's your case as well, which model of Mac or you on ?

**Comment by jeansordes** [comment]
As a workaround, you can record a voice note, then move a copy of your vocal note on your Desktop, and transcribe the audio this way instead, the app doesn't crash on my machine this way

**Comment by Sircam19** [comment]
> > I have the same issue, I'm on MacOS on an M2 chip though (Macbook Air 2022)
> > I wonder if that's your case as well, which model of Mac or you on ?
> 
> Same as you! M2 MacBook Air. Seems that this is a bug on M chip

Hello folks. Just to add further specificity. I have an M1 and it works just fine for me. Merci.

**Comment by chidiwilliams** [comment]
Hey @AlanDinkle @jeansordes, assuming you installed via Homebrew, could you pls try installing the DMG directly? (https://github.com/chidiwilliams/buzz/releases/download/v0.7.1/Buzz-0.7.1-mac.dmg) Also, could you pls share whether transcribing via Whisper/Whisper.cpp makes any difference? Thanks.

**Comment by jeansordes** [comment]
Hm. The Whisper doesn't crash, but it doesn't output anything

Whisper.cpp crash as soon as I click "Record"

Here is the crash report

[english, whisper cpp, tiny, crash report.txt](https://github.com/chidiwilliams/buzz/files/10378436/english.whisper.cpp.tiny.crash.report.txt)

**Comment by jorgecaballeroramos** [comment]
I've installed DMG and It crashes on my M1, both whisper and whisper.cc! THANKS!!!!

**Comment by manuthebyte** [comment]
> As a workaround, you can record a voice note, then move a copy of your vocal note on your Desktop, and transcribe the audio this way instead, the app doesn't crash on my machine this way

This just gives me back an empty file.

**Comment by onesecurity** [comment]
hi @chidiwilliams 

I have the same issue, can you build a Mac ARM version dmg file? thanks.

https://github.com/chidiwilliams/buzz/releases

**Comment by EthanKeng** [comment]
Same issue here.
 M1, MBA, english, whisper cpp, base

**Comment by chidiwilliams** [comment]
Couldn't get Whisper.cpp to bundle for Mac ARM on this Python stack, but I worked on a native rebuild over the past few months. It's available on the App Store here: https://apps.apple.com/us/app/buzz-captions/id6446018936.
