### ISSUE TITLE
Buzz 0.7.1 does not run on Windows 8.1 (ImportError QtGui)

### ISSUE THREAD

**Issue by oep42** [chidiwilliams/buzz#328]
I installed "Buzz-0.7.1-windows.exe" on Windows 8.1. When I then try to run Buzz, I get this error message:

Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "buzz\gui.py", line 14, in <module>
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.

**Comment by buzzlover69** [comment]
yes i tried windows 7 and 8.1 same errors,i think it works windows 10 only.

**Comment by chidiwilliams** [comment]
> yes i tried windows 7 and 8.1 same errors,i think it works windows 10 only.

Yes, unfortunately, that may be the case.
