### ISSUE TITLE
Feature Request: Multi-language Transcription

### ISSUE THREAD

**Issue by avenir-g** [chidiwilliams/buzz#332]
Would it be possible to transcribe two languages simultaneously? I have audio recordings where the speaker goes back and forth between two languages or has a translator. This would be super duper awesome! 💁‍♂️🙂 Thank you!

**Comment by Sircam19** [comment]
> Would it be possible to transcribe two languages simultaneously? I have audio recordings where the speaker goes back and forth between two languages or has a translator. This would be super duper awesome! 💁‍♂️🙂 Thank you!

Hello Avenir-g. It absolutely does. As I use it for my language lessons which switch between English and Frenc all the time. It's hardly perfect but it works really well. Here's a screen shoot, and just ensure that you are using medium or higher. The lower models do not support mult-langage transcription. It will take some time to do the transcription. Usually up to 3X the length of audio time. So have a coffee, go out and about and forget about it till completed. Thanks again Chidi for making such a great program.

![CleanShot 2023-01-15 at 07 37 37@2x](https://user-images.githubusercontent.com/4651001/212541183-0709fe88-fe40-4c02-a5fe-2cea7a5ba2f8.jpg)
