### ISSUE TITLE
Windows 10 Not using any GPU.

### ISSUE THREAD

**Issue by AlmostHuman34** [chidiwilliams/buzz#333]
I don't know if that version suppose to use CPU or is it a bug in my case. It takes very long time to transcribe using cpu.

**Comment by doomlordss** [comment]
Also curious on this. Can we please include gpu support for windows

**Comment by cogscides** [comment]
+1 for this. Running this on GPU will be a gamechanger

**Comment by chidiwilliams** [comment]
Yes, I'm looking into this... I'll update here once I have it completed in the next release.

**Comment by Sircam19** [comment]
> Yes, I'm looking into this... I'll update here once I have it completed in the next release.

So happy to hear as am almost at the point of grabbing a more powerful machine but if GPU support is enabled then there would be less of a need.Awesome

**Comment by chongkaechin** [comment]
https://github.com/fortypercnt/stream-translator

I think I found a similar project. The difference is it doesn't seem to have a GUI. I haven't looked at it closely enough to understand the sorce code. So I am not sure if this can be used as a reference.

**Comment by shruru** [comment]
> https://github.com/fortypercnt/stream-translator
> 
> I think I found a similar project. The difference is it doesn't seem to have a GUI. I haven't looked at it closely enough to understand the sorce code. So I am not sure if this can be used as a reference.

Lovely~ but GUI is essenstial to someone like me. 👍🏻 looking forward to Buzz's update.

**Comment by chidiwilliams** [comment]
Unfortunately, I've had to stop working on this as I spent the last few days trying to implement this but didn't make much progress: https://github.com/chidiwilliams/buzz/pull/346#issuecomment-1414406529.

I think it's still possible to get this to work if you're okay running the code locally:

- [Set up CUDA for your operating system](https://developer.nvidia.com/cuda-downloads)
- With [Poetry](https://python-poetry.org/) installed and the project cloned, run `poetry export --without-hashes --format=requirements.txt > requirements.txt` to generate a `requirements.txt` file
- In the `requirements.txt` file, manually add `--extra-index-url https://download.pytorch.org/whl/cu113` before the line containing "torch" (just like [this](https://github.com/fortypercnt/stream-translator/blob/e9e8594f820d8baea1b405231a01e88900cf1070/requirements.txt#L4-L5))
- Run `pip install -r requirements.txt`
- Run `make buzz/whisper_cpp.py`
- Run `python3 main.py`

**Comment by AlmostHuman34** [comment]
Uhh that's a hard way to make it work around, anyway, maybe in the future it will be easier.

**Comment by cogscides** [comment]
@AlmostHuman34 true, I also faced with trouble on installing this
