### ISSUE TITLE
Blank? Help

### ISSUE THREAD

**Issue by JBreezy222** [chidiwilliams/buzz#334]
I run Buzz with the Whisper.cpp. It will finish but nothing happens. No srt file. I have tried numerous different formats and nothing happens. It will run for around 10 minutes and finish. But nothing happens. No download of a srt file. What am I doing wrong? I used to run the older version with no problem. Could find the srt where I downloaded it to. But with this new version 0.7.0 I get nothing.

**Comment by chidiwilliams** [comment]
Hi, yes. The UI on the new version is just a little different. Double-click on the row that says completed, and it should open the transcript, and you should be able to export. (You can also click on the row, and click the Export icon.)

![image](https://user-images.githubusercontent.com/17879672/212672890-c40640a4-8ce7-413f-989f-0ced43a3c924.png)

**Comment by chidiwilliams** [comment]
Did this work for you?

**Comment by chidiwilliams** [comment]
@nmeln Are you on an Apple Silicon computer?

**Comment by chidiwilliams** [comment]
Got it. It's a known issue (see https://github.com/chidiwilliams/buzz/issues/323), and I've been working on a fix for a few days (https://github.com/chidiwilliams/buzz/actions/runs/3953120107/jobs/6769024210). The challenge is that GitHub's runners are Intel-only, but I should have a fix out soon.

**Comment by nmeln** [comment]
> @nmeln Are you on an Apple Silicon computer?

Yes, I'm using M1 Pro

**Comment by JBreezy222** [comment]
I will redownload it. I got frustrated and took it out. I am using a HP Slim Desktop PC

**Comment by JBreezy222** [comment]
Speaking of crashing... I did notice it crashed on "Very Large"

**Comment by JBreezy222** [comment]
I put it back in and ran the whisper.cpp. it still doing the exact same thing. Says complete but double click on completed and it is blank. Nothing to export. :(

**Comment by chidiwilliams** [comment]
If you're on Mac Silicon, please retry with the new native version of Buzz. Testflight: https://testflight.apple.com/join/0T5byiDM. App Store: https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200.
