### ISSUE TITLE
[Fixed] "Failed to execute script 'main' due..."

### ISSUE THREAD

**Issue by shruru** [chidiwilliams/buzz#336]
I got something like this at pop-up windows and everything stopped.
`Traceback (most recent call last):
  File "whisper\audio.py", line 42, in load_audio
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber.py", line 430, in transcribe_whisper
  File "whisper\transcribe.py", line 84, in transcribe
  File "whisper\audio.py", line 111, in log_mel_spectrogram
  File "whisper\audio.py", line 47, in load_audio
RuntimeError: Failed to load audio: ffmpeg version 5.0.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers

  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)

  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

  libavutil      57. 17.100 / 57. 17.100

  libavcodec     59. 18.100 / 59. 18.100

  libavformat    59. 16.100 / 59. 16.100

  libavdevice    59.  4.100 / 59.  4.100

  libavfilter     8. 24.100 /  8. 24.100

  libswscale      6.  4.100 /  6.  4.100

  libswresample   4.  3.100 /  4.  3.100

  libpostproc    56.  3.100 / 56.  3.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:/Offworlder Sculpting and Texturing in 3D Coat for Blender Eevee/Part 1 - Creating the Base Head/04 Timelapse Offworlder v1.mp4':

  Metadata:

    major_brand     : qt  

    minor_version   : 512

    compatible_brands: qt  

    encoder         : Bandicut 3.5.0.599 / Cutter / ENC / H264 (NVIDIA® NVENC)

  Duration: 00:17:10.40, start: 0.000000, bitrate: 668 kb/s

  Stream #0:0[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(progressive), 1912x1008 [SAR 1:1 DAR 239:126], 667 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn (default)

    Metadata:

      handler_name    : VideoHandler

      vendor_id       : FFMP

      encoder         : Lavc58.35.100 h264_nvenc

Output #0, s16le, to 'pipe:':

Output file #0 does not contain any stream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'
`

**Comment by shruru** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/2038477/212883449-cbfcd62e-637e-4321-bbbd-9fc061309f07.png">

**Comment by shruru** [comment]
haha ,I figured it out.

**Comment by chidiwilliams** [comment]
Great. How did you fix?

**Comment by shruru** [comment]
> Great. How did you fix?

well, I found out if you import video file WITHOUT Audio or commentary , this error pops up which is still very confused to users. 😂 

I always import a brunch of videos (and sure I don't watch Every video beforehand) , so some of them just video without any audio. it's fine for showing "complete" but it comes with this error window.

**Comment by shruru** [comment]
BTW @chidiwilliams, if you need UI designer to help building this amazing app, feel free let me know I wanna help out.

**Comment by chidiwilliams** [comment]
Oh, I see! I should probably test that to see how I can improve the error messages.



> BTW @chidiwilliams, if you need UI designer to help building this amazing app, feel free let me know I wanna help out.

Thanks a lot! I'll let you know once I have a UI task to be done.
