### ISSUE TITLE
support videos?

### ISSUE THREAD

**Issue by deadcoder0904** [chidiwilliams/buzz#338]
[this project](https://github.com/m1guelpf/yt-whisper/) uses `yt-dlp` underhood thereby increasing support to not just audio but video files.

can this project support videos too?

**Comment by Sircam19** [comment]
> [this project](https://github.com/m1guelpf/yt-whisper/) uses `yt-dlp` underhood thereby increasing support to not just audio but video files.
> 
> can this project support videos too?

I've used it on mp4 files (i.e. videos) from Skype meetings that I have had with my teacher and absolutely on problems.
