### ISSUE TITLE
Sentences break incorrectly , Could / How to fix it?

### ISSUE THREAD

**Issue by shruru** [chidiwilliams/buzz#344]
Something like that 👇🏻...Many of sentence are breaked / Punctuate incorrectly..which is quite annoying 😂. Please how to "fix" it or is it due to Whisper AI?  we can do nothing with it? Thank you so much🙏🏻

<img width="614" alt="SCR-20230129-iqi" src="https://user-images.githubusercontent.com/2038477/215307112-7159094b-4b3c-4837-b77c-058b07c03891.png">

**Comment by chidiwilliams** [comment]
Yes, it's from Whisper. One alternative could be to use a subtitle editor like [SubtitleEdit](https://www.nikse.dk/subtitleedit) to fix up the timings.

**Comment by shruru** [comment]
> Yes, it's from Whisper. One alternative could be to use a subtitle editor like [SubtitleEdit](https://www.nikse.dk/subtitleedit) to fix up the timings.

I got 30+ srt files like this , and  each one duration is around 60mins or 500-800 lines 😂
So I am afraid that I have to look for a solution instead of manually fix it. 
How about WhisperX - https://github.com/m-bain/whisperX

**Comment by chidiwilliams** [comment]
Is this different from turning on "Word-level timings" in Buzz? Does that work for you?
