### ISSUE TITLE
Is it possible to download the models manually from my browser instead of automatically?

### ISSUE THREAD

**Issue by metorm** [chidiwilliams/buzz#347]
Buzz is such excellent work. I'd like to run it on a workstation that is unfortunately completely offline. So, can I download the models manually from another computer and copy the necessary files to the offline workstation? Where shall I place the files for `buzz` to detect?

**Comment by Sircam19** [comment]
> Buzz is such excellent work. I'd like to run it on a workstation that is unfortunately completely offline. So, can I download the models manually from another computer and copy the necessary files to the offline workstation? Where shall I place the files for `buzz` to detect?

I wholeheartedly agree. Such great work and that's a great question also.

**Comment by chidiwilliams** [comment]
Thanks a lot. The Whisper models should be placed in `$HOME/.cache/whisper` (Mac and Windows), while the Whisper.cpp models should be placed in `$HOME/Library/Caches/Buzz` (Mac) or `$HOME\AppData\Local\Buzz\Buzz\Cache` (Windows):

```shell
/Users/chidiwilliams/.cache/whisper
├── base.en.pt
├── base.pt
├── large-v2.pt
├── medium.pt
├── small.pt
├── tiny.en.pt
└── tiny.pt
```

```shell
/Users/chidiwilliams/Library/Caches/Buzz
├── ggml-model-whisper-medium.bin
├── ggml-model-whisper-tiny.bin
└── tasks
```

This is also stated in [the FAQ](https://github.com/chidiwilliams/buzz#faq).

**Comment by metorm** [comment]
@chidiwilliams Thanks a lot. I'll try it.

**Comment by mobilestack** [comment]
> 

Just curious why the large model is named with large-V2? Is that if I download the large model manually, I have to rename to large-V2, so as to be recognized by Buzz?
