### ISSUE TITLE
Crashes when after models load

### ISSUE THREAD

**Issue by jballant12** [chidiwilliams/buzz#348]
I'm on Intel Core. Have tried dl by homebrew or dmg. Both crash after installing any of the models for the first time. I go back in to the app and record but no transcription is produced. When I try with huggingface I get an error that model can't be 'none'. 

I deleted and did a reinstall of buzz, but the models i tried previously won't automatically download the next time. I try some other models not previously used but same thing happens and it crashes after downloading.

Looks like a great app and would love to use for medical admin.

**Comment by jballant12** [comment]
<img width="409" alt="Screen Shot 2023-02-06 at 4 50 06 pm" src="https://user-images.githubusercontent.com/121175923/216893686-f6237dcb-153b-4e44-8cc8-4d3affa2062e.png">

**Comment by jballant12** [comment]
the audio file to text transcription works though

**Comment by jballant12** [comment]
I also get this error when attempting to re-install using 'brew install --cask buzz'

(base) iMac:journal jamesballantyne$ brew install --cask buzz
Warning: Cask 'buzz' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for buzz.

**Comment by jballant12** [comment]
I also get this error when attempting to re-install using 'brew install --cask buzz'

(base) iMac:journal jballant$ brew install --cask buzz
Warning: Cask 'buzz' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for buzz.

**Comment by chidiwilliams** [comment]
Hi, could you please share the contents of the logs at `/Users/[username]/Library/Logs/Buzz/logs.txt`? Are there any logs that might be of interest?

**Comment by LittIeBbug** [comment]
Also having the issue! Here's what was in that pathway.
[logs.txt](https://github.com/chidiwilliams/buzz/files/10709184/logs.txt)
In addition, if it's helpful, here's apple's crash log:
[Buzz Crash.txt](https://github.com/chidiwilliams/buzz/files/10709221/Buzz.Crash.txt)

**Comment by secondbrain-note** [comment]
I have the same issue
