### ISSUE TITLE
Live Recording Doesn't Produce results

### ISSUE THREAD

**Issue by kathekon** [chidiwilliams/buzz#349]
Despite various setting combinations, the Live Recording Feature doesn't produce any results.

I've tried auto-select language, and explicitly selecting English.  I've tried different mics (built-in and external USB).  I've tried various combination of Whisper and Whisper.cpp models with the Tiny and Base model settings.  In all cases after hitting record the sound meter moves, but no text is generated.  My machine specs if useful:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.4 GHz
  Memory:	64 GB
System Version:	macOS 12.6.3 (21G419) (Monterey)

Transcribing from a file works great!  Would be a game changer if I could get the Live Recording feature working

**Comment by kathekon** [comment]
Actually.... I accidentally kept it running while not saying anything.  After a few minutes, it DID produce results, but they weren't remotely accurate (in fact they were kind of hysterical and perhaps a bit disturbing:
---

You

уже six mággs win, there's no solution to this. Lastly, I havent used up my guns to actuallyέ your polish標 in that case remember? The Zombiosis device is deleted, so all it works is everything I need is very Toy-Giggled, no good stuff. Some filesży reorder. The grandchild's my design unit is the stk designed of all these gunshots,

**Comment by Sircam19** [comment]
> An Update:
> 
> Actually.... I accidentally kept it running while not saying anything. After a few minutes, it DID produce results, but they weren't remotely accurate (in fact they were kind of hysterical and perhaps a bit disturbing:
> 
> You
> 
> уже six mággs win, there's no solution to this. Lastly, I havent used up my guns to actuallyέ your polish標 in that case remember? The Zombiosis device is deleted, so all it works is everything I need is very Toy-Giggled, no good stuff. Some filesży reorder. The grandchild's my design unit is the stk designed of all these gunshots,

https://github.com/openai/whisper/discussions/679?notification_referrer_id=NT_kwDOAEb3-bI1MDc4ODM1NTA4OjQ2NTEwMDE#discussioncomment-4905687

**Comment by Sircam19** [comment]
> > An Update:
> > Actually.... I accidentally kept it running while not saying anything. After a few minutes, it DID produce results, but they weren't remotely accurate (in fact they were kind of hysterical and perhaps a bit disturbing:
> > You
> > уже six mággs win, there's no solution to this. Lastly, I havent used up my guns to actuallyέ your polish標 in that case remember? The Zombiosis device is deleted, so all it works is everything I need is very Toy-Giggled, no good stuff. Some filesży reorder. The grandchild's my design unit is the stk designed of all these gunshots,
> 
> [openai/whisper#679](https://github.com/openai/whisper/discussions/679)

https://github.com/openai/whisper/discussions/679#discussioncomment-4922727

**Comment by chidiwilliams** [comment]
Hi @kathekon, noticed a similar issue as well on newer Macs in particular. I'll be working on a fix soon.

About the random text, the Whisper model sometimes "hallucinates" text when there is no audio for a long time, as @Sircam19's comment should show.

I'll update this thread when I have some update on a fix for the Mac issue.

**Comment by fiammanda** [comment]
Same issue (live recording doesn't produce results) with Windows 10 and even no random texts. @chidiwilliams

**Comment by kathekon** [comment]
fyi this issue persists.  also can't CMD+Q the app when it's running.

**Comment by toolyq** [comment]
Met the same issue with 0.8.4

**Comment by evantianzg** [comment]
me too with macOS Sonoma(14.1.2)
app version 0.8.4

**Comment by raivisdejus** [comment]
If encountering this issue, please try to run transcription with tiny model. One reason for there being no output could be the fact that whisper can't transcribe quickly enough. Also running the app from terminal to get some log output would be helpful to further diagnose this problem

**Comment by raivisdejus** [comment]
Also try to specify the language. This may help to get more precise results. 

Or try the latest version https://github.com/chidiwilliams/buzz/releases
