### ISSUE TITLE
Does Windows version only supports audio?

### ISSUE THREAD

**Issue by yinguohang** [chidiwilliams/buzz#351]
I installed the v0.7.1 while it shows v0.7.0 after the installation. Not like the README, it shows that it only supports audio. Is this expected behavior? Thanks!

<img width="529" alt="image" src="https://user-images.githubusercontent.com/6234533/218248468-cc77365e-3843-4d70-a6ba-7cc6ab55b982.png">

**Comment by Sircam19** [comment]
> I installed the v0.7.1 while it shows v0.7.0 after the installation. Not like the README, it shows that it only supports audio. Is this expected behavior? Thanks!
> 
> <img alt="image" width="529" src="https://user-images.githubusercontent.com/6234533/218248468-cc77365e-3843-4d70-a6ba-7cc6ab55b982.png">

Hello I see the same thing after installing "0.71" I can say however that as far as processing audio AND video it works perfectly. 
![CleanShot 2023-02-11 at 09 25 32@2x](https://user-images.githubusercontent.com/4651001/218263621-83d049c8-c06d-41e8-972e-26ea02e11575.jpg)

**Comment by Sircam19** [comment]
> > I installed the v0.7.1 while it shows v0.7.0 after the installation. Not like the README, it shows that it only supports audio. Is this expected behavior? Thanks!
> > <img alt="image" width="529" src="https://user-images.githubusercontent.com/6234533/218248468-cc77365e-3843-4d70-a6ba-7cc6ab55b982.png">
> 
> Hello I see the same thing after installing "0.71" I can say however that as far as processing audio AND video it works perfectly. ![CleanShot 2023-02-11 at 09 25 32@2x](https://user-images.githubusercontent.com/4651001/218263621-83d049c8-c06d-41e8-972e-26ea02e11575.jpg)

![CleanShot 2023-02-11 at 09 25 32@2x](https://user-images.githubusercontent.com/4651001/218263663-ff384f48-8d8f-43cf-af8c-ff487ea7e9f1.jpg)
