### ISSUE TITLE
Option to download all avalible model files locally.

### ISSUE THREAD

**Issue by harrypm** [chidiwilliams/buzz#352]
[Note of manual downloads for Whisper](https://github.com/openai/whisper/discussions/63 
)

Without manually downloading the model files this app is crippled with tedium for offline usage.

It would be nice if there was a download all button built into the small release and or a pre-compiled full download with the model files bundled at the time of release.

This is no longer an issue for me as I now have done so manually but for simple users or archive/offline users this would mean a lot in terms of simplification of user experience and ease of setup.

**Comment by chidiwilliams** [comment]
Thanks a lot for the feedback. The Whisper models total more than 3GB for multi-language and English-only in all sizes (not counting Whisper.cpp and Hugging Face models), so I'm not sure it would be practical to bundle the models with the application itself).

Would it be helpful to make a Settings/Preferences page that shows a dropdown of all the models and lets you see which models you have downloaded and download the ones you don't have, and then show this page at setup time?

**Comment by harrypm** [comment]
A settings page with a dropdown list would be a reasonable addition to address this for now.

**Comment by sandyplus** [comment]
Can not download any model except "tiny".
Try a lot of times, but keep failure.

**Comment by chidiwilliams** [comment]
@sandyplus

- What OS are you on? 
- Were you using Whisper/Whisper.cpp?
- Could you let me know what you have in your logs?

**Comment by chidiwilliams** [comment]
https://github.com/chidiwilliams/buzz/releases/tag/v0.8.0
