### ISSUE TITLE
Whisper transcription super slow - Mac Silicon

### ISSUE THREAD

**Issue by NAL100** [chidiwilliams/buzz#358]
Running on an M1 Mac - tested on Whisper, Model small. Transcription, English selected. I assume it was using the small-en model but not sure.

File successfully outputted but after 20:52. File is a 30 minute mp3 file.

Ran the exact same file but with a python script I wrote which calls the whisper small-en model - it took 04:32.  Now the only difference between the two scenarios that I can tell is that Buzz outputted one with line by line timestamps (word level timings were off in both cases). But why is it so much slower?

I will test whisper.cpp once the new changes about that are compiled into a binary (running Buzz v. 0.7.0 which is what brew installed) - it looks like there have been commits (e.g. #331  but no new release yet.)

**Comment by Sircam19** [comment]
> Indeed. Processing an 1-hour-long video using large model took me hours... Buzz seems only use 1 CPU core on my M1 Max

Yep I noticed the same :-( Was so excited to check the latest version  I installed it and ran the transcription while being in a hotel room 2000km away from home :-(

**Comment by chidiwilliams** [comment]
The new version is now live [on the App Store](https://apps.apple.com/gb/app/buzz-captions/id6446018936?mt=12) (for $9.99). It uses Whisper.cpp optimized for Mac silicon and also has search, audio playback, supports the Whisper API, and many other new features.

**Comment by NAL100** [comment]
> The new version is now live [on the App Store](https://apps.apple.com/gb/app/buzz-captions/id6446018936?mt=12) (for $9.99). It uses Whisper.cpp optimized for Mac silicon and also has search, audio playback, supports the Whisper API, and many other new features.

That's great but I'm not sure why I would pay for it since it wasn't working just a short time ago and has been pretty buggy. Perhaps make a free version available for beta testers?
