### ISSUE TITLE
build error:An error occurred when running the package exe command

### ISSUE THREAD

**Issue by sammichenVV** [chidiwilliams/buzz#361]
When I run this command “poetry run pyinstaller --noconfirm Buzz.spec” on ubuntu, an error is reported：
TypeError: expected str, bytes or os.PathLike object, not NoneType
![image](https://user-images.githubusercontent.com/22388079/220537941-27e4ad80-0925-4bef-b61d-c9e8f453c5f2.png)

This seems to be caused by the relative path，how to fix it？

**Comment by chidiwilliams** [comment]
@sammichenVV I'm not quite sure really. I haven't seen this issue before.
