### ISSUE TITLE
Buzz-0.7.1-mac is still showing 7.0.0 after update (and still crashes immediately on M1)

### ISSUE THREAD

**Issue by tdkardum** [chidiwilliams/buzz#363]
![buzz](https://user-images.githubusercontent.com/63611084/221162444-d3893a46-8ac8-46a0-9c96-9a5a1daa5e69.png)

**Comment by chidiwilliams** [comment]
Hi, thanks for the report. It's a known issue, and I'm looking to fix it soon. I'm currently working on a Mac-native version of Buzz, and I'll update this thread once it becomes available.

**Comment by tdkardum** [comment]
@chidiwilliams Awesome, appreciated!

**Comment by Sircam19** [comment]
Music to our ears glad you still pushing forward on buzz. It's such a solid program. Interestingly I have an M1 and it works fine.

**Comment by chidiwilliams** [comment]
The Mac app is live on the App Store now: https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200. Thanks.
