### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by ilentt** [chidiwilliams/buzz#365]
### Error occurred while launch
```
Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "buzz\gui.py", line 14, in <module>
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
```
#### Error GUI
![image](https://user-images.githubusercontent.com/11204504/222196470-8c6704d0-2776-4d8e-8cdc-867f05d05d40.png)

#### OS info
![image](https://user-images.githubusercontent.com/11204504/222197128-0c5304e6-2ada-4587-88ed-99ff64b1dc10.png)

**Comment by Sircam19** [comment]
> ### Error occurred while launch
> ```
> Traceback (most recent call last):
>   File "main.py", line 42, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "buzz\gui.py", line 14, in <module>
> ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
> ```
> 
> #### Error GUI
> ![image](https://user-images.githubusercontent.com/11204504/222196470-8c6704d0-2776-4d8e-8cdc-867f05d05d40.png)
> 
> #### OS info
> ![image](https://user-images.githubusercontent.com/11204504/222197128-0c5304e6-2ada-4587-88ed-99ff64b1dc10.png)

![CleanShot 2023-03-01 at 20 55 33@2x](https://user-images.githubusercontent.com/4651001/222310836-2d8f6961-fe88-4589-aaa9-d47b6ee92890.jpg)

Sorry fella...I think this is why it didn't work for ya.
