### ISSUE TITLE
Buzz transcribes same line over entire file.

### ISSUE THREAD

**Issue by AlmostHuman34** [chidiwilliams/buzz#379]
With the newest update when I run transcription for my files (Around 1:30h audio wav) I quite often get after few minutes or at the end same lines as if the buzz was processing to some point and then it repeats for whole file on all txt srt vtt. 
My model is medium and language is Polish but same thing happend to me with English as well. I don't run any additional commands.

**Comment by cddqssc** [comment]
I have the same issue, any ideas?
