### ISSUE TITLE
Does not download any Whisper model but the tiny one

### ISSUE THREAD

**Issue by wolframklaeger** [chidiwilliams/buzz#383]
Really nice app, eventually, in the future. 

In this current state, unfortunately, useless. 

Please consider to provide an option for separate model downloads, using a reliable download manager or something.

**Comment by wolframklaeger** [comment]
Thanks. Gave it another try. Installed again on Windows 10. Testing Live Recording. 

This time, at least the base model was downloaded successfully. Click record. Crash. Relaunch. Maybe a result after minutes. Or crash.

Sorry. Maybe this app works with GPU installed or diving into Python or something else than Windows.

Aside, I already have downloaded all Whisper models and used it successfully via commandline, as suggested by OpenAI.

**Comment by Piciok** [comment]
I can confirm that with the version 0.8.0 under Windows 10 any attempt to download a model for any implementation results in an immediate quitting of the application. Unfortunately I can't find any file with a log created for the event to provide more useful context.

Any assistance on this would be greatly appreciated.

**Comment by chidiwilliams** [comment]
I've been able to get a Windows 10 machine to test. Could you try this build? 
 https://github.com/chidiwilliams/buzz/suites/12584744384/artifacts/673007635

I did notice an issue with loading Whisper.cpp on Windows 10, but the other model types should work for you.

**Comment by Piciok** [comment]
Thank you very much for the prompt response. It seems that's been fixed for all except the large Faster Whisper model. That one still crashes the app.
