### ISSUE TITLE
Can you add whisper faster or whisper cpp. Its way FASTER than Openai's Whisper?

### ISSUE THREAD

**Issue by pheonis2** [chidiwilliams/buzz#386]
Openai's whisper large model is quiet slow. Is there a way to change the model to this repo :https://github.com/ggerganov/whisper.cpp or https://github.com/guillaumekln/faster-whisper

**Comment by yshalsager** [comment]
+1 for faster-whisper! It's significantly faster than the original model.

**Comment by Sn0wfly** [comment]
+1 to this request!

**Comment by chidiwilliams** [comment]
Whisper.cpp is already supported. I'll look into faster-whisper.

**Comment by AlmostHuman34** [comment]
Any progress?

**Comment by chidiwilliams** [comment]
It's already in `main` if you want to test there (https://github.com/chidiwilliams/buzz/actions/runs/4787674070). I'll cut a new release in a few days.

**Comment by chidiwilliams** [comment]
Out in the new release: https://github.com/chidiwilliams/buzz/releases/tag/v0.8.0
