### ISSUE TITLE
Linux version crashes.

### ISSUE THREAD

**Issue by CHJ85** [chidiwilliams/buzz#390]
Hi there.  I'm getting this error on Ubuntu Mate 22.04:
`
 Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Humanity/status/16/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: pango_attr_overline_new (gdk-pixbuf-error-quark, 5)
`
According to this error, the issue is icon theme related. However, I already have the humanity-icon-theme package installed.
Do you think you could release the Linux version as a flatpak instead, thus include the necessary dependencies?
And if not, bundle in the theme files instead, or somehow have the app automatically recognize the system theme. 
Please and thank you.

**Comment by yango** [comment]
I've got a similar (or the same) bug:
(Buzz:719414): Gtk-WARNING **: 13:29:18.089: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/elementary-xfce/status/16/image-missing.png: Format der Bilddatei unbekannt (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/elementary-xfce/status/16/image-missing.png: Format der Bilddatei unbekannt (gdk-pixbuf-error-quark, 3)
Abgebrochen (Speicherabzug geschrieben)

**Comment by yango** [comment]
There is a similar bug: https://github.com/chidiwilliams/buzz/issues/382
Unfortunately, the #382 has been closed without any explanation.

**Comment by yango** [comment]
Well unfortunately I see the very same bug with SuSe:
Buzz:5935): Gtk-WARNING **: 02:52:59.929: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)

**Comment by chidiwilliams** [comment]
Hey, I closed #382 as it seemed the author was going to build from source instead. The app loads fine on Ubuntu 20.04 as far as I'm aware, but I'm not super familiar with other Linux distros. I'll test on Ubuntu 22.04 in a short while and see if I can fix the build. Thanks.

**Comment by raivisdejus** [comment]
Assume this has been fixed, if not download latest version from some successful Action run or use latest snap `snap install buzz --channel latest/edge`
