### ISSUE TITLE
Mac Version keep crashing (0.72)

### ISSUE THREAD

**Issue by ideatrap** [chidiwilliams/buzz#391]

**Comment by daochou** [comment]
me 2

**Comment by chidiwilliams** [comment]
Are you on Intel or Silicon Macs?

**Comment by ideatrap** [comment]
M1

**Comment by chidiwilliams** [comment]
Got it. Unfortunately, the stack this project uses seems to break on Silicon Macs, and I've been unable to find a workaround. I've also mentioned this in other issues, and I'll update the docs as well.

I rebuilt this app in native Swift, and it works well on all Macs; it's paid, however, but you can join the free beta here if you still want to try it out (https://github.com/chidiwilliams/buzz/discussions/374). Alternatively, you can check out [MacWhisper](https://goodsnooze.gumroad.com/l/macwhisper).

**Comment by ideatrap** [comment]
Let me try both. Really appreciate.

**Comment by ideatrap** [comment]
the new test version seems more stable, though it crashes also. but much more stable.

**Comment by chidiwilliams** [comment]
Thanks. I see the crash report, which is very helpful. Thanks for the feedback.
