### ISSUE TITLE
How do I edit the transcription before exporting it to SRT?

### ISSUE THREAD

**Issue by Geeks4Good** [chidiwilliams/buzz#395]
Iʻm probably being dense, but since the transcription is not perfect and needs some edits before it the SRT file is created, and I donʻt have an SRT editor, is there a way to edit the transcription prior to exporting it as an SRT file? I have poked around some and donʻt seem to find a way. Lots of alleged TXT to SRT free converters out there, but have struck out on all of them I have tried using the TXT file exported from Buzz.
On a side but related note, I did find a decent online free SRT editor here: https://www.happyscribe.com/subtitle-tools/online-subtitle-editor/free

**Comment by chidiwilliams** [comment]
If you're on Windows, [SubtitleEdit](https://www.nikse.dk/subtitleedit) is pretty good. Building a subtitle editor into this (cross-platform) version of Buzz is quite tricky, but the [MacOS version](https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200) has a good editor.

**Comment by Geeks4Good** [comment]
> [MacOS version](https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200) has a good editor.

Thanks Chidi. I have been using the free/open source version of Buzz on MacOS, but may try your paid version if it has the built-in editor.

**Comment by Sircam19** [comment]
> > [MacOS version](https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200) has a good editor.
> 
> Thanks Chidi. I have been using the free/open source version of Buzz on MacOS, but may try your paid version if it has the built-in editor.

It does...and have used it :-)

**Comment by chidiwilliams** [comment]
> > [MacOS version](https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200) has a good editor.
> 
> Thanks Chidi. I have been using the free/open source version of Buzz on MacOS, but may try your paid version if it has the built-in editor.

I've added support for an editor here which should be available in the next release. But, yes, the editor in the native app is a lot better.
