### ISSUE TITLE
There is a problem with the connection logic of the timeline

### ISSUE THREAD

**Issue by EndDream** [chidiwilliams/buzz#396]
When using Software to transcribe Chinese, I found a problem with the connection logic of some of the timelines. Even if there was no speech for a while in between, the subtitles of the previous sentence would continue in the timeline to the next sentence. This can lead to obvious errors in the output subtitles and audio, affecting their usability and readability. But I'm not sure if this is a problem with Whisper's model or with buzz.

**Comment by EndDream** [comment]
In addition, this is really very good software that frees up a lot of my time, thanks to the author.

**Comment by chidiwilliams** [comment]
Yes, I think this should be coming from Whisper, unfortunately.
