### ISSUE TITLE
Buzz Captions for macOS is unable to modify the Whisper API

### ISSUE THREAD

**Issue by tutulifestyle** [chidiwilliams/buzz#397]
I want to transcribe captions using the OpenAI Whisper API, but I mistakenly entered an incorrect API key during the initial setup. Now, the window for editing the API key does not appear, and I cannot find any way to modify it. This is causing me to receive continuous error messages, and I am unable to proceed. I would appreciate it if you could help me resolve this issue.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/62787426/230705079-4c45a009-b62b-4b6a-9b68-99f89464da85.png">

<img width="734" alt="image" src="https://user-images.githubusercontent.com/62787426/230705193-3207e706-372f-42fb-80c6-33ed60a72653.png">

**Comment by chidiwilliams** [comment]
The key is stored in your Keychain, and you can change it there. I'll add a view within the app in the next update. Thanks.

![image](https://user-images.githubusercontent.com/17879672/230733930-bc91ce57-b0dc-4fd4-be57-ad42a8b6a15e.png)

**Comment by tutulifestyle** [comment]
Thank you for your reply. The issue has been resolved, but I hope to see an option for related modifications in the next version. I believe it would be useful for users who hold multiple API keys as well.Thanks again.
