### ISSUE TITLE
Improvements to keyboard and screen reader accessibility

### ISSUE THREAD

**Issue by Piciok** [chidiwilliams/buzz#404]
Currently certain tasks are very difficult to achieve when using just the keyboard and a screen reader, namely:

- The toolbar with buttons such as "Record", "Open Transcript" and "Clear History" is not focusable with a keyboard;
- The edit field with the transcript's content is impossible to navigate using a screen reader. It currently behaves as if nothing was happening when trying to navigate with the standard hotkeys used in edit fields. This may be due to how edit fields are implemented in QT and may require a custom, accessibility-specific implementation;
- the action of opening a transcript for a given file straight from the tasks' table is achievable only with a mouse click, not with the pressing of the enter key as might be usual in such situations
- The addition of hotkeys and context menu items for more actions E.G. recording, opening of a transcript, exporting and clearing of the history would make it faster to work with Buzz using the keyboard.

I hope my suggestions could be integrated into the project. It would make a huge difference to users with differing access needs.

Thank you for a great app and keep up the good work. Good luck and have lots of fun coding it!

**Comment by Sircam19** [comment]
Thanks so much for leaving these points. As someone who suffered a concussion I can now more fully relate to what you have asked for.

**Comment by chidiwilliams** [comment]
Thanks a lot for the feedback. I'll look into each one of these.

**Comment by chidiwilliams** [comment]
The new release should have better transcript editing and accessibility: https://github.com/chidiwilliams/buzz/releases/tag/v0.8.0

Pls let me know if you face any further issues with it.

**Comment by Piciok** [comment]
Hello and thank you very much for the improvements. Those are great ones!

I have given the 0.8.0 release a spin and here are my observations:

1. I really like the new transcript editor. It resembles a kind of translation software and I like that. Unfortunately, as the Tab key allows for navigation between the columns of the table, it is not possible to reach the toolbar and as a result use the Export button. I would propose the two following solutions to this:
A. To create a keyboard shortcut for the export action;
B. To create a way to reach the toolbar by keyboard (it is convention to do it using the F6 key).
2. For some reason the ctrl+o shortcut for importing a file doesn't seem to be working anymore.
3. In the Settings window, the shortcuts modification is not accessible to screen readers i.e. you can focus an option and by pressing a new hotkey it is possible to modify it but as the edit field with the current setting is not exposed as such to the screen reader, it is difficult to read it i.e. to tell what is currently set.
Again, thank you for all of your work and thanks in advance for further improvements.
