### ISSUE TITLE
Why buzz takes 15%(one core) CPU usage when IDLE?

### ISSUE THREAD

**Issue by anonymouscnuser** [chidiwilliams/buzz#418]
version: `0.7.2` release on Windows 10

What is buzz doing after I open buzz? There's no reason to take so much cpu.

![image](https://user-images.githubusercontent.com/68681806/234461276-d5a0b07f-def8-4bb9-a896-70e6de2091ec.png)

**Comment by chidiwilliams** [comment]
Poor coding on my part. Will be fixed in #419.

**Comment by anonymouscnuser** [comment]
> Poor coding on my part. Will be fixed in #419.

Thank you for your reply.
