### ISSUE TITLE
Why's Linux package so big?

### ISSUE THREAD

**Issue by momobobe** [chidiwilliams/buzz#425]
The Linux version is times larger than those for Windows and MacOS, why? Pardon me that I'm just a noob user, but I think there must be some way to optimize it.

**Comment by jemacchi** [comment]
hi @momobobe, could you please point me to the Linux release download page? (I was looking for it on the releases section, but only find Mac and Windows ones). I would like to try the app in Ubuntu.

**Comment by chidiwilliams** [comment]
@jemacchi, I only recently noticed the release script wasn't publishing the Ubuntu version. You can download the build for an earlier version here: https://github.com/chidiwilliams/buzz/releases/tag/v0.7.2. I'll work on fixing the newer releases.

**Comment by chidiwilliams** [comment]
@momobobe, I've noticed this too, but I have to admit I'm not sure and I haven't gotten time to check yet. I'll have a look at some point, but can't promise it'll be soon.
