### ISSUE TITLE
Failed to execute script 'main' due to unhandled exception: 'NoneType' object has no attribute 'flush'

### ISSUE THREAD

**Issue by c469591** [chidiwilliams/buzz#429]
Hello.
buzz is not running on windows 10.
It shows an error
Failed to execute script 'main' due to unhandled exception: 'NoneType' object has no attribute 'flush' Traceback (most recent call last).
And the title of the releases page shows version 0.8, but the download link is still 0.72.
I hope this can be fixed, thanks!

**Comment by chidiwilliams** [comment]
Does version 0.7.2 work for you?

**Comment by CuriousSpirit** [comment]
No, unfortunately, it does not.

**Comment by c469591** [comment]
0.71 can be used, 0.72 sometimes will report an error, 0.8 is completely unable to open, he will directly report an error

**Comment by chidiwilliams** [comment]
Does the build on the main branch (https://github.com/chidiwilliams/buzz/suites/12580902779/artifacts/672771691) work for you?

**Comment by c469591** [comment]
This works now.
I'm curious as to why the one I downloaded from releases doesn't work?
Thanks!

**Comment by chidiwilliams** [comment]
I added a fix for it here: https://github.com/chidiwilliams/buzz/commit/6528bbcd0786a54747d91f356f0e3e48340ed5fd. I'll update the release.
