### ISSUE TITLE
Whisper.cpp and Faster Whisper models cannot be downloaded

### ISSUE THREAD

**Issue by c469591** [chidiwilliams/buzz#432]
Hello.
I can't download the model from Preferences, after clicking download, buzz will flash back directly without error message.
Directly import the file and select
Whisper.cpp
or
Faster Whisper
After clicking rom, almost all models will flash back directly.
Only when you choose
Faster Whisper
inside the (medium) model in order to download successfully.
Also, if they have a new version of the model, can I also update the model from buzz?
Thanks!

**Comment by c469591** [comment]
Another question, can buzz be accelerated by GPU?

**Comment by chidiwilliams** [comment]
Are you on Windows 10? Also what's the output of your logs at `C:\Users\<username>\AppData\Local\Buzz\Buzz\Logs`?

**Comment by c469591** [comment]
This is the log
[logs.txt](https://github.com/chidiwilliams/buzz/files/11364886/logs.txt)

**Comment by c469591** [comment]
I am windows 10 22H2
