### ISSUE TITLE
Faster Whisper never progresses with the transcription

### ISSUE THREAD

**Issue by Piciok** [chidiwilliams/buzz#435]
Tried on a Windows 10 PC with the medium model:
I have loaded a file that is around one hour long and in ogg format. The model has downloaded just fine, the conversion by FFMPEG worked as expected, I think, the recording has queued for transcription and then it seems to forever be stuck at 0%.
Maybe the issue is not related to Buzz at all and there is something about my machine and Faster Whisper not playing nice with each other. If there is any additional information I might provide, do not hesitate to reach out.

Thanks in advance for taking a look at this.

**Comment by chidiwilliams** [comment]
Could you let me know which of these work for you?

- Using the normal Whisper model and not Faster Whisper
- Transcribing a much shorter audio (you can try with this test file: https://github.com/chidiwilliams/buzz/raw/main/testdata/whisper-french.mp3)
- Using the tiny Faster Whisper model

**Comment by Piciok** [comment]
Hello!

1. Transcribing with regular Whisper including larger models works as usual;
2. Transcribing of your test file with the medium Faster Whisper model worked in an instant.
3. Transcribing of a 8-minute file with the Faster Whisper tiny model also worked relatively quickly.
I'm beginning to wonder whether something isn't up with the progress bar indication because also during the download of the Faster Whisper models it seems to be showing that the download is at 25% with 2 seconds remaining all the time. Of course the download takes longer than that and it works as expected in the end.
