### ISSUE TITLE
Faster Whisper issue error and Whisper.cpp finishes after few lines.

### ISSUE THREAD

**Issue by AlmostHuman34** [chidiwilliams/buzz#439]
Error description:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber.py", line 473, in transcribe_whisper
  File "buzz\transcriber.py", line 500, in transcribe_faster_whisper
  File "faster_whisper\transcribe.py", line 101, in __init__
RuntimeError: CUDA failed with error out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

Windows 10 newest update.

**Comment by chidiwilliams** [comment]
**> RuntimeError: CUDA failed with error out of memory**

Which of the models are you running? And are you sure you have enough GPU memory to run it?

**Comment by AlmostHuman34** [comment]
> **> RuntimeError: CUDA failed with error out of memory**
> 
> Which of the models are you running? And are you sure you have enough GPU memory to run it?

Is the Fast Whisper  and Whisper.cpp based on GPU only now? It was medium model.

**Comment by AlmostHuman34** [comment]
Alright so I changed my GPU from 1060 to 3060 12 GB version, I runned faster whisper, my network speed goes full then I ger unknown error.

**Comment by kaushal2012** [comment]
> Error description: Traceback (most recent call last): File "multiprocessing\process.py", line 314, in _bootstrap File "multiprocessing\process.py", line 108, in run File "buzz\transcriber.py", line 473, in transcribe_whisper File "buzz\transcriber.py", line 500, in transcribe_faster_whisper File "faster_whisper\transcribe.py", line 101, in **init** RuntimeError: CUDA failed with error out of memory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 36, in File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support File "multiprocessing\spawn.py", line 116, in spawn_main File "multiprocessing\spawn.py", line 129, in _main File "multiprocessing\process.py", line 329, in _bootstrap AttributeError: 'NoneType' object has no attribute 'write'
> 
> Windows 10 newest update.

-->hey can you please help me setup on my windows because i have to show it in my college and i am getting lots of errors when i run main.py!!

**Comment by AlmostHuman34** [comment]
> > Error description: Traceback (most recent call last): File "multiprocessing\process.py", line 314, in _bootstrap File "multiprocessing\process.py", line 108, in run File "buzz\transcriber.py", line 473, in transcribe_whisper File "buzz\transcriber.py", line 500, in transcribe_faster_whisper File "faster_whisper\transcribe.py", line 101, in **init** RuntimeError: CUDA failed with error out of memory
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "main.py", line 36, in File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support File "multiprocessing\spawn.py", line 116, in spawn_main File "multiprocessing\spawn.py", line 129, in _main File "multiprocessing\process.py", line 329, in _bootstrap AttributeError: 'NoneType' object has no attribute 'write'
> > Windows 10 newest update.
> 
> -->hey can you please help me setup on my windows because i have to show it in my college and i am getting lots of errors when i run main.py!!

just swap to subtitle edit software, i had way too many issues with buzz back then.

**Comment by kaushal2012** [comment]
> > > Error description: Traceback (most recent call last): File "multiprocessing\process.py", line 314, in _bootstrap File "multiprocessing\process.py", line 108, in run File "buzz\transcriber.py", line 473, in transcribe_whisper File "buzz\transcriber.py", line 500, in transcribe_faster_whisper File "faster_whisper\transcribe.py", line 101, in **init** RuntimeError: CUDA failed with error out of memory
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last): File "main.py", line 36, in File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support File "multiprocessing\spawn.py", line 116, in spawn_main File "multiprocessing\spawn.py", line 129, in _main File "multiprocessing\process.py", line 329, in _bootstrap AttributeError: 'NoneType' object has no attribute 'write'
> > > Windows 10 newest update.
> > 
> > 
> > -->hey can you please help me setup on my windows because i have to show it in my college and i am getting lots of errors when i run main.py!!
> 
> just swap to subtitle edit software, i had way too many issues with buzz back then.

i don't think that's an option for me anymore, its just too late and i was too busy with my internship so if possible i just want to make few changes like APP NAME & LOGO change and get Translation!!
