### ISSUE TITLE
issue: Faster  Whisper Model download program flashing

### ISSUE THREAD

**Issue by martjay** [chidiwilliams/buzz#442]
OS: Win11 PRO X64

Buzz Version:  0.8.1

issue: Faster Whisper Model download program flashing

**Comment by martjay** [comment]
I downloaded the model of Whisper.cpp and used it to recognize subtitles, but at the beginning, the CMD window showed a flash of a few tenths of a second. After a while, the Buzz display was completed, but I clicked on the subtitles to see that they were blank.
![888888](https://user-images.githubusercontent.com/44982189/235833195-b040f6df-a1d2-455b-8815-a3f857d05409.jpg)

**Comment by Dragoy** [comment]
Have you found a solution?

**Comment by martjay** [comment]
> Have you found a solution?

NO. Did you encounter the same problem?

**Comment by Dragoy** [comment]
> > Have you found a solution?
> 
> NO. Did you encounter the same problem?

Yes, I ended up doing everything based on the WhisperDesktop CLI with my gpu it was much faster and better.

**Comment by chidiwilliams** [comment]
Yeah, I'm not sure what is causing the issue here tbh. I just tested on a new Windows 11 VM and both Whisper.cpp and Faster Whisper work fine. I'll update the build to add better logging for the errors, but looks like WhisperDesktop might be a better solution atm.

**Comment by chaomai** [comment]
Maybe you've already downloaded the model, so there is no error for you.

In model_loader.py

```
    if model.model_type == ModelType.FASTER_WHISPER:
        try:
            return download_faster_whisper_model(size=model.whisper_model_size.value, local_files_only=True)
        except (ValueError, FileNotFoundError):
            return None
```

```
def download_faster_whisper_model(size: str, local_files_only=False, tqdm_class: Optional[tqdm] = None):
    if size not in faster_whisper.utils._MODELS:
        raise ValueError(
            "Invalid model size '%s', expected one of: %s" % (
                size, ", ".join(faster_whisper.utils._MODELS))
        )

    repo_id = "guillaumekln/faster-whisper-%s" % size

    allow_patterns = [
        "config.json",
        "model.bin",
        "tokenizer.json",
        "vocabulary.txt",
    ]

    return huggingface_hub.snapshot_download(repo_id, allow_patterns=allow_patterns, local_files_only=local_files_only,
                                             tqdm_class=tqdm_class)

```

You call `download_faster_whisper_model ` with `local_files_only=True`, so `huggingface_hub.snapshot_download` would run with `local_files_only=True`. I didn't download the model previously, when I run it I got this,

```
>>> huggingface_hub.snapshot_download(repo_id, allow_patterns=allow_patterns, local_files_only=True, tqdm_class=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chaomai/.local/opt/miniconda3/envs/common_env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/chaomai/.local/opt/miniconda3/envs/common_env/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/chaomai/.cache/huggingface/hub/models--guillaumekln--faster-whisper-large-v2/refs/main'
```

**Comment by raivisdejus** [comment]
If some unexpected issue happens during model download Like network disconnect or something. Part of model files will be downloaded, but not all. This will cause errors. To fix this you need to delete model cache folder and re-download it.

Also in latest development versions there are improvements to model download, so try the latest development version. To get it log into GitHub and download the latest development version from some successful action run https://github.com/chidiwilliams/buzz/actions?query=branch%3Amain

Please re-open issue or create new one if this is still a problem on latest development version.
