### ISSUE TITLE
[M1 Buzz] 'Open With' an audio file from inside Finder to Buzz

### ISSUE THREAD

**Issue by vinhquach** [chidiwilliams/buzz#446]
Hi,
I'm using Buzz for Apple Silicon.
Could you allow users to open audio files from inside Finder to Buzz? I find it more comfortable than using "Import" button or drag and drop files.
Currently, I can force-open files with Buzz from inside Finder, but Buzz open a new window instead of loading the files. Why is that?
Have a good one!

**Comment by chidiwilliams** [comment]
Hey, thanks. Added now, and should be available in the next release.
