### ISSUE TITLE
The model directory should be selectable

### ISSUE THREAD

**Issue by martjay** [chidiwilliams/buzz#450]
It always automatically downloads the model to the C drive without prompting for the specific download location. I think it should be possible to set the download directory.

**Comment by rokejulianlockhart** [comment]
Shouldn't it just be in `%AppData%/Buzz`?

**Comment by rokejulianlockhart** [comment]
@martjay, ...which?

**Comment by martjay** [comment]
> @martjay, ...which? That's a multiple-choice question.

I hope to customize the path or other drive letters outside of the C drive

**Comment by raivisdejus** [comment]
Model download directory can be specified via advanced preference `BUZZ_MODEL_ROOT` - https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences

Use this guide to set the variable permanently in Windows (or macOS / Linux) settings https://www.imatest.com/docs/editing-system-environment-variables/#Windows

Available in latest development builds https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain To download the artifacts you need to log into the github.
