### ISSUE TITLE
I encountered some issues when using version 0.8.1

### ISSUE THREAD

**Issue by th10010** [chidiwilliams/buzz#453]
Hello, I updated buzz to the latest version yesterday, and encountered the following problems during use:
1. When using it, it prompts that the model is wrong, and the pop-up window of the picture below pops up;
2. The known video duration is 10 minutes, and the video is in The language is English, but when I using the Whisper.cpp model to export subtitles, no matter whether the model is tiny or base, even including small, medium, and large, complete subtitles cannot be exported, and even blank subtitles are exported.
How to solve it? is there any way?Thank you for your answer.
![微信截图_20230509011813](https://user-images.githubusercontent.com/55772277/236889090-08cdf124-71d8-43f2-b0e9-1129d0c65576.png)
![微信截图_20230508111034](https://user-images.githubusercontent.com/55772277/236884247-c1cde35b-6147-4940-8b3e-9f4b1bcbe497.png)
![微信截图_20230509005950](https://user-images.githubusercontent.com/55772277/236885019-c3fabe0b-b44a-4936-906e-2b7f57f772c5.png)
![微信截图_20230509012150](https://user-images.githubusercontent.com/55772277/236889417-a1e2a190-f184-4a47-ae63-9a87786a2bd9.png)

**Comment by chidiwilliams** [comment]
Pls try the latest version: https://github.com/chidiwilliams/buzz/releases/tag/v0.8.2. I think this should be fixed now.
