### ISSUE TITLE
suggestion: if possible enable the app to indicate voices with numbers etc.

### ISSUE THREAD

**Issue by marrie** [chidiwilliams/buzz#455]
this could be a toggle when transcribing. The app could on a separate line  indicate a voice change and all the voice's output in a paragraph. I just had to edit a transcript with two voices and that became a bit tedious. I have no clue if this would be possible in the AI models, however this would be helpful. Thanks.

**Comment by DJRipley** [comment]
For interviewing or multiple voices this would be invaluable.

**Comment by marrie** [comment]
Wow, I didn’t think of interviews, voice 1 and voice 2 is even fine with me. I can always relabel. So long as the voice parts so tgo speak are in separate paragraphs or they stgart on a new line.

**Comment by raivisdejus** [comment]
This has also been requested in https://github.com/chidiwilliams/buzz/issues/492

Will close this issue, possible implementation of this feature and ideas for it can be discussed in the other issue

**Comment by raivisdejus** [comment]
@marrie @DJRipley Please share your workflows for this feature in this discussion https://github.com/chidiwilliams/buzz/discussions/1043 so we can figure out best way to implement this.
