### ISSUE TITLE
Version 0.8.1 - Legitimation reguired

### ISSUE THREAD

**Issue by sapereaudete** [chidiwilliams/buzz#460]
I've just installed Version 0.8.1 on Linux openSUSE LEAP 15.4.
When I try to transcript an mp4- file I a legitimation is required.
Is that correct? Where can I get it? I have an openAI API key, but that does not work

**Comment by raivisdejus** [comment]
Please try the latest version:
- From the Releases section https://github.com/chidiwilliams/buzz/releases
- Snap store https://snapcraft.io/buzz
- Or run the source version https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#running-buzz-locally

This discussion with custom APIs may also be relevant https://github.com/chidiwilliams/buzz/discussions/827
