### ISSUE TITLE
Translate to Icelandic

### ISSUE THREAD

**Issue by haukur1982** [chidiwilliams/buzz#461]
My main objective is to create Icelandic subtitles. I have uploaded a audio file with English language and used Whisper.cpp Large and have Translate selected in Task. I selected Icelandic as the language. With these selections it won't do any translation. 

If I try to use OpenAI API Whisper.cpp IT gives me error. It says I exceeded the maximum content limit. The file is only 13mb so I am unsure if that is accurate error code. 

I bought Buzz on the Mac App Store. 

What is the best protocol to get the App to work for translating English audio to Icelandic text?

Thanks!

**Comment by chidiwilliams** [comment]
Hey, unfortunately, English audio to Icelandic text is not supported. Whisper (both Whisper.cpp and Whisper API) only transcribes "X audio to X text" or "X audio to English text" (where X can be Icelandic, etc.).

I'll look into the issue with the max content limit, but English -> Icelandic text isn't currently supported.

**Comment by Sircam19** [comment]
> My main objective is to create Icelandic subtitles. I have uploaded a audio file with English language and used Whisper.cpp Large and have Translate selected in Task. I selected Icelandic as the language. With these selections it won't do any translation.
> 
> If I try to use OpenAI API Whisper.cpp IT gives me error. It says I exceeded the maximum content limit. The file is only 13mb so I am unsure if that is accurate error code.
> 
> I bought Buzz on the Mac App Store.
> 
> What is the best protocol to get the App to work for translating English audio to Icelandic text?
> 
> Thanks!

Hello there. What I've done in the past is to grab the translated English with the timestamps as an SRT and then run it through DeepL to get you target the  language-  just copy and paste the text into DeepL afterwards you can  either overwrite the old English srt or simply duplicate the old SRT  and THEN overwrite over by selecting all  and then copying over the Icelandic text you got as an output from DeepL. I've done that with TV shows and documentaries so so many times. The only thing with DeepL is that if your SRT was really really long it might prompt for a subscription but I doubt that will be the case for you.

**Comment by RonanDex** [comment]
How to collaborate with OpenAI for subtitle translation implementation?

**Comment by raivisdejus** [comment]
Option to translate with ChatGPT or some other AI has been added in latest development version. See FAQ for details on how to use it. https://chidiwilliams.github.io/buzz/docs/usage/translations

All feedback would be very welcome
