### ISSUE TITLE
[0.8.1 Linux] Doesn't detect manually downloaded language models (and can't download new ones)

### ISSUE THREAD

**Issue by galmeida28** [chidiwilliams/buzz#462]
**Version [0.8.1 Linux].**

**Downloading a new model gives me:** 
Download failed: [Errno 18] Invalid cross-device link: '/tmp/tmp02obn3np' -> '/home/user/.cache/whisper/tiny.pt'
Which seems to be related to the fact that tmp and home are on different file systems. (Is it?)

**I then downloaded the model from:**
https://github.com/openai/whisper/discussions/63
And pasted it into:
/home/user/.cache/whisper/large.pt
But when I open buzz, go to help->preferences->models the large model doesn't show as downloaded.

Do I have to alter some config file?
Is the only way to alter Buzz python scripts?
What can I do?

**Comment by chidiwilliams** [comment]
The large model should be named `large-v2.pt`, I believe

**Comment by chidiwilliams** [comment]
The cross-device link error has been addressed in https://github.com/chidiwilliams/buzz/issues/454 and should be fixed in the next release
