### ISSUE TITLE
Won't Open After Install

### ISSUE THREAD

**Issue by OllieWhale** [chidiwilliams/buzz#467]
After I install Buzz on Windows nothing happens after I click to run the application. 

I am getting the following error message after trying to open the shortcut "The item 'Buzz.exe' that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly"

I have looked inside the installed files and can't find the file to launch the application.

Is there any other software I need to run it?

**Comment by albino1** [comment]
Just run it by hand:

`C:\Program Files (x86)\Buzz\Buzz.exe`

**Comment by OllieWhale** [comment]
I am getting the message; 

"C:\windows\system32>\Program Files (x86)\Buzz\Buzz.exe
'\Program' is not recognized as an internal or external command,
operable program or batch file."

**Comment by albino1** [comment]
Are you installing it using this?

https://github.com/chidiwilliams/buzz/releases/download/v0.8.1/Buzz-0.8.1-windows.exe

**Comment by OllieWhale** [comment]
Yes, it is still coming up with the message

The install doesn't seem to install the Buzz.exe file or it gets installed and then removed somehow.

**Comment by faveoled** [comment]
> "C:\windows\system32>\Program Files (x86)\Buzz\Buzz.exe '\Program' is not recognized as an internal or external command,
> 
> and if I try this i get this message:
> 
> "C:\windows\system32>start Buzz.exe The system cannot find the file Buzz.exe. operable program or batch file

This is wrong, you aren't actually starting the app. Read up on console escaping symbols or move the app to location with no spaces in path
