### ISSUE TITLE
possible to show timestamps in txt file

### ISSUE THREAD

**Issue by DJRipley** [chidiwilliams/buzz#469]
Hello
I am trying to transcribe an interview. Absent any markers identifying which speaker is speaking (which would be extremely helpful), it would be helpful to have a text file that keeps the timestamps for each line. When I open the txt file it just has a big block of unseparated text (although in Buzz I can see the time stamps). Is that possible now or can that be added as a feature?

**Comment by chidiwilliams** [comment]
Hm, how about exporting as SRT/VTT? They're still text file formats, and you can change the extension if you need.
