### ISSUE TITLE
GTK issues

### ISSUE THREAD

**Issue by LTGuan** [chidiwilliams/buzz#470]
(Buzz:23344): Gtk-WARNING **: 12:11:27.469: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: 无法识别的图像文件格式 (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: 无法识别的图像文件格式 (gdk-pixbuf-error-quark, 3)
已放弃

**Comment by yango** [comment]
It's the same bug as #390

**Comment by chidiwilliams** [comment]
Could you try installing from Snapcraft? https://snapcraft.io/buzz

**Comment by raivisdejus** [comment]
Alternatively try to run source version as per notes here https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md

Ple3ase reopen the issue if still an issue
