### ISSUE TITLE
Translation from english to french 

### ISSUE THREAD

**Issue by 2nipix** [chidiwilliams/buzz#472]
First of all, congratulations on your work.
I bought the BUZZ application and I have a Mac M1, I tested it on a video and I think it's great.
I would like to know if in the near future your software will be able to translate video files from English into French?

Best regards,

**Comment by raivisdejus** [comment]
Option to translate with ChatGPT or some other AI has been added in latest development version. See FAQ for details on how to use it. https://chidiwilliams.github.io/buzz/docs/usage/translations

All feedback would be very welcome
