### ISSUE TITLE
Error while downloading a model

### ISSUE THREAD

**Issue by Pocokk** [chidiwilliams/buzz#475]
Getting [this type of message](https://i.imgur.com/nT0ry2B.png) everytime I want to start download a model, what can I do?

Things I've tried, none of them worked.

-install Buzz on C:
-install Buzz on E:
-launch/start as Admin
-change PATH for %TEMP% to C:\Temp

**Comment by hardbrick2** [comment]
Seconded. I'm having similar issues with Buzz 8.1 on both Windows 10 and Linux Mint.
When I click "Record" using Whisper.cpp as the backend, it appears to download the model, then fails and crashes.

Console output on Linux:

Traceback (most recent call last):
  File "buzz/gui.py", line 601, in on_cancel_model_progress_dialog
AttributeError: 'ModelDownloader' object has no attribute 'stop'
Aborted (core dumped)

**Comment by chidiwilliams** [comment]
Thanks for the report, @Pocokk. This should have been fixed in #454, but I haven't published a new release yet. Does the latest main build work for you? (Download link: https://github.com/chidiwilliams/buzz/suites/13256198862/artifacts/722788091)

**Comment by Pocokk** [comment]
I've just downloaded and installed https://github.com/chidiwilliams/buzz/suites/13256198862/artifacts/722788091

let me try it now!

**Comment by Pocokk** [comment]
Oh another minor thing I have noticed (don't want to open new ticket for that)

I checked both TXT and SRT, yet at the end only a TXT file was in the folder with the original audio file.

**Comment by chidiwilliams** [comment]
Weird, sure. As a workaround, you can double-click on the transcription and click export again.
