### ISSUE TITLE
KeyError: <OutputFormat.SRT: 'srt'>

### ISSUE THREAD

**Issue by faveoled** [chidiwilliams/buzz#479]
```
Traceback (most recent call last):
  File "/home/user/Downloads/buzz/buzz/gui.py", line 250, in on_checkbox_state_changed
    self.file_transcription_options.output_formats.remove(output_format)
KeyError: <OutputFormat.SRT: 'srt'>
Fatal Python error: Aborted
```
Reproducing:
![image](https://github.com/chidiwilliams/buzz/assets/85760289/be1c0717-9b28-449d-9648-9525b890a07e)
Trying to disable checked "SRT" (or "TXT")  when window opens with checked items. Checked on 0.8.1 and latest.

**Comment by chidiwilliams** [comment]
Thanks for this. I've put in a fix. Btw, what Linux distro and version are you using? I've been trying to track down the issue with Arch (#384).

**Comment by faveoled** [comment]
I'm on Ubuntu 22.04.2. I'm not sure how it relates to Arch.
