### ISSUE TITLE
App crashes on macOS Ventura M1

### ISSUE THREAD

**Issue by larryqiann** [chidiwilliams/buzz#481]
I've tried installing with both Homebrew and V0.8.1/0.8.0 on my Mac Mini M1 and when starting the recording, it will crash with the following log:
[log.txt](https://github.com/chidiwilliams/buzz/files/11648292/log.txt)

Is anyone else having the same issue?

Thanks!

**Comment by chidiwilliams** [comment]
This version of Buzz doesn't support Mac Silicon, unfortunately. You can check out the App Store version (although it's paid): https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200.

**Comment by chidiwilliams** [comment]
You can try out a TestFlight link here: https://github.com/chidiwilliams/buzz/discussions/374
