### ISSUE TITLE
 I can't quite figure it out now. I have an MP4 video that is over 9 hours long. I'm certain that I used either Buzz or Whisper desktop to convert the English in this video into two separate SRT files: one in Chinese and one in English. However, no matter how I try now, I can't replicate the process, and it seems that Whisper doesn't support this feature. I'm wondering how I managed to do it back then. 

### ISSUE THREAD

**Issue by lenmao** [chidiwilliams/buzz#489]
I'm really perplexed and don't know whether to laugh or cry. Earlier, I used Whisper to convert videos and generate Chinese SRT subtitles from Englisth input, and English SRT subtitles from English input.

However, for the past two days, no matter what I specify, it only generates English SRT subtitles. The audio in the videos is in English. Has anyone else encountered a similar issue?

**Comment by chidiwilliams** [comment]
I'm not sure how that happened, to the best of my knowledge, Whisper can only generate Chinese-to-Chinese / Chinese-to-English / English-to-English subtitles, but not English-to-Chinese.

**Comment by t0t061** [comment]
Hi Lenmao,
The "translate" function translates the source language into English, while the "transcribe" function translates from English into the language of your choice.
At least, that's what I confirmed in the discussion section (https://github.com/chidiwilliams/buzz/discussions/488#discussioncomment-6184728), based on this Whisper thread (https://github.com/openai/whisper/discussions/649#discussioncomment-4325122).
A+
