### ISSUE TITLE
Auto Language select to enable transcription of multi language audio

### ISSUE THREAD

**Issue by menelic** [chidiwilliams/buzz#493]
When transcribing multi-language audio, whisper will take the language set in the dropdown menue as main input and transcription target and translate audio in other languages it recognizes into the target language even if translation is not selected. Please implement transcription of multi-language files without translation. Some workarounds that the gui could implement - including prompting tips - https://github.com/lewangdev/faster-whisper-youtube/issues/1 and here https://github.com/openai/whisper/discussions/49

**Comment by raivisdejus** [comment]
If you specify language when transcribing (do not leave default "Detect language") selected Whisper will transcribe to this language. Unfortunately you can select only one language, there is nothing I can think that could be done in Buzz to fix this. 
I have seen that when transcribing audio with multiple languages in it whisper can switch from selected language to the other in the audio. This can happen and for this I also do not see any solution part from waiting for better whisper models in the future
