### ISSUE TITLE
model Whisper.cpp

### ISSUE THREAD

**Issue by LilacZhang** [chidiwilliams/buzz#498]
When I use Whisper.cpp model on a Apple silicon Mac, it always doesn't work, the output files are empty, my guess is the Whisper.cpp version model have not yet translate to a coreml version, can anybody fix this issue?

**Comment by chidiwilliams** [comment]
This version of Buzz does not support Apple Silicon Macs. You may consider getting the (paid) App Store version: https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200
