### ISSUE TITLE
Microphone recording no sound when opened from Finder

### ISSUE THREAD

**Issue by chidiwilliams** [chidiwilliams/buzz#50]
When the app is opened from Finder on Mac (via double-clicking the app from Finder or opening from Spotlight Search), the recording stream returns arrays of all zeroes. But it works fine when the program is opened from the terminal (via `python main.py` or `./dist/Buzz.app/Contents/MacOS/Buzz`).

This seems related: https://stackoverflow.com/questions/69193993/pyinstaller-app-not-getting-microphone-permission-works-fine-with-terminal

**Comment by chidiwilliams** [comment]
It seems to work after signing a new version??

**Comment by chidiwilliams** [comment]
Finally figured it out 🤦🏾‍♂️

The second step of code signing overwrites the previous entitlement for requesting audio input. Fix is to add the audio permission to the entitlements.plist file

**Comment by transitive-bullshit** [comment]
I'm getting the same issue using the latest release [0.5.2](https://github.com/chidiwilliams/buzz/releases/tag/v0.5.2) on MacOS Monterey. If I open it through finder, it doesn't request Microphone permissions, but if I open the python app directly through the terminal, it spawns the GUI and requests Microphone access correctly.

**Comment by chidiwilliams** [comment]
> I'm getting the same issue using the latest release [0.5.2](https://github.com/chidiwilliams/buzz/releases/tag/v0.5.2) on MacOS Monterey. If I open it through finder, it doesn't request Microphone permissions, but if I open the python app directly through the terminal, it spawns the GUI and requests Microphone access correctly.

Ah, I'll have a look at this

**Comment by chidiwilliams** [comment]
@transitive-bullshit, this should be fixed in the latest release https://github.com/chidiwilliams/buzz/releases/tag/v0.5.4

**Comment by transitive-bullshit** [comment]
Huzzah! 😄
