### ISSUE TITLE
can't download "faster-whisper large model" buzz auto closes 

### ISSUE THREAD

**Issue by viktorblack** [chidiwilliams/buzz#503]
can't seem to download "faster-whisper large model" buzz automatic closes when trying

**Comment by chidiwilliams** [comment]
What version/OS are you using?

**Comment by viktorblack** [comment]
buzz 8.2 and I'm windows 10

**Comment by viktorblack** [comment]
is there a way to manually download the model if so how?

**Comment by mtrabelsi** [comment]
happens to me in win11 as well, and in general it does not seem to run on GPU..........

**Comment by wzgrx** [comment]
+1
