### ISSUE TITLE
GPU use in windows 

### ISSUE THREAD

**Issue by johnfelipe** [chidiwilliams/buzz#504]
Is possible use one or two GPU for transcriptor with large model?

**Comment by johnfelipe** [comment]
This is possible?

**Comment by johnfelipe** [comment]
pls tell me witch model do i need download, i need large for best accuracy, but for use NVIDIA GeForce RTX 3060 Ti

**Comment by raivisdejus** [comment]
GPU For windows is now available for source version. Please see https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows on how to run it.

**Comment by raivisdejus** [comment]
Version 1.0.0 has been released https://github.com/chidiwilliams/buzz/releases

GPU Support should work on Windows with CUDA installed https://developer.nvidia.com/cuda-downloads

In my experience the Faster Whisper with `large-v2` model has the best results. Some languages may have better results with `large-v3`. 

Please re-open the issue if GPU support does not work as expected.
