### ISSUE TITLE
Local drive storage space shrinked with every download when doing transcribe or record

### ISSUE THREAD

**Issue by mouselema** [chidiwilliams/buzz#505]
hi I notice my hard disk space shrinking whenever I perform transcribe or record of different base, type like between different ai.

Every time I select different type to transcribe the download will start for a few mins. 
Thereafter disk space becomes substantially lower. Can we remove this temporary cach being downloaded into my pc?

Thank you.

**Comment by chidiwilliams** [comment]
Hi, this is how local transcription with Whisper works: you download the model only once for each type you wish to use.

The cache directories are listed here: https://chidiwilliams.github.io/buzz/docs/faq. You can navigate to those directories and delete the models for the types you no longer wish to use.
