### ISSUE TITLE
Use by SSH

### ISSUE THREAD

**Issue by cflo56** [chidiwilliams/buzz#509]
Hello, I was able to install in SSH mode (dpkg -i), however when I launch it it gives me an error asking for a screen (server x).
Is it possible to pass only in command line without server x?
OS : Debian 11
```
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, offscreen, vkkhrdisplay, minimal, eglfs, vnc, wayland-egl, minimalegl, xcb, wayland.

```

**Comment by raivisdejus** [comment]
Buzz is a GUI application that uses different whisper implementations internally. If you do not need GUI, you can use the underlying implementations directly. See https://github.com/SYSTRAN/faster-whisper or https://github.com/ggerganov/whisper.cpp for more details how to run them

**Comment by raivisdejus** [comment]
To run Buzz on SSH you can also forward the X sessions to the remote server. For more info on this see https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely
