### ISSUE TITLE
The new version at the Apple Store is not functioning properly

### ISSUE THREAD

**Issue by maomaosiyuLsc** [chidiwilliams/buzz#511]

**Comment by chidiwilliams** [comment]
What issues are you having with it?

**Comment by maomaosiyuLsc** [comment]
I am sending you the video to explain what happened after importing the
folder. It's always like this.

Chidi Williams ***@***.***> 于2023年6月27日周二 08:29写道：

**Comment by chidiwilliams** [comment]
Sure, I didn't get the link though.

**Comment by maomaosiyuLsc** [comment]
sorry，i replay directly the mail. Here is the link:
https://drive.google.com/file/d/1oRBvRZlG13JtfuyRK0R0ECxwqi3BbzYP/view?usp=drive_link
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>


Chidi Williams ***@***.***> 于2023年6月27日周二 19:31写道：

**Comment by maomaosiyuLsc** [comment]
I just did the test. It works. But yesterday, I tried several times,
everything failed. I didn't restart the system.

刘书超 ***@***.***> 于2023年6月28日周三 10:12写道：

**Comment by chidiwilliams** [comment]
Got it. Not sure what the issue was as well, but feel free to reopen an issue if it comes up again. Thanks.
