### ISSUE TITLE
Crash in live recording / transcribe on Apple MacBook M1

### ISSUE THREAD

**Issue by arturedward** [chidiwilliams/buzz#512]
Buzz installed through brew. App crashes right after downloading the model.

**Comment by bryanshihpeng** [comment]
same here

**Comment by duojianghuji** [comment]
To install Buzz, download the [latest version](https://github.com/chidiwilliams/buzz/releases/latest) for your operating system. Buzz is available on Mac (Intel), Windows, and Linux. (For Apple Silicon, please see the [App Store version](https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200).)

**Comment by duojianghuji** [comment]
To install Buzz, download the [latest version](https://github.com/chidiwilliams/buzz/releases/latest) for your operating system. Buzz is available on Mac (Intel), Windows, and Linux. **(For Apple Silicon, please see the [App Store version]**(https://apps.apple.com/us/app/buzz-captions/id6446018936?mt=12&itsct=apps_box_badge&itscg=30200).)

**Comment by jordanbaucke** [comment]
@duojianghuji it would appear the version compiled for Apple Silicon is $9.99

**Comment by wzhisaso** [comment]
same here but m1pro

**Comment by glorialai** [comment]
I'm facing the same issue

**Comment by raivisdejus** [comment]
For Apple silicon please try the latest version `1.1.0`
For Intel get the version from latest development build (you need to log into the github to see the artifact download button) https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

**Comment by raivisdejus** [comment]
Latest versions for Apple silicon and Intel chips are available here https://github.com/chidiwilliams/buzz/releases
