### ISSUE TITLE
Crash (Unhandled exception) 

### ISSUE THREAD

**Issue by andercard0** [chidiwilliams/buzz#514]
Hi,

I'd like to report a issue while trying to use Buzz in the latest version as follows:

**Error:**
![image](https://github.com/chidiwilliams/buzz/assets/43047877/1afcc48c-256b-44ce-9d66-32611e380928)

**To reproduce:**
- Drag 'n drop a music(mp3) or video
- Choose model, task, language
- Press run
- Error

**Application Version:**
Version: 0.8.2

**Additional notes:**
Did test it in version 0.7.2 with the same settings and it is working without issues at all. 

![image](https://github.com/chidiwilliams/buzz/assets/43047877/753893b2-7208-413c-9e43-4647dda5026f)

**Comment by chidiwilliams** [comment]
Thanks for the report. Does this also happen when you transcribe with Whisper.cpp models?

**Comment by chidiwilliams** [comment]
What version of Windows are you on?

I've just tested on a clean install of version 0.8.3 on Windows 11 and both Whisper and Whisper.cpp transcriptions work fine. Could you also try cleaning the models at `C:\Users\<user>\.cache\whisper` and re-downloading them?

**Comment by andercard0** [comment]
Hello. Sorry for the delayed response. well, tested here as you mentioned as follows:
(after clean up the cache) and it worked. both, whisper and whisper cpp
![image](https://github.com/chidiwilliams/buzz/assets/43047877/06247496-a807-41c1-aafa-ce129dcb1d78)

I did not know about the cache folder, Thank you!
