### ISSUE TITLE
exe crash when ran

### ISSUE THREAD

**Issue by gitihobo** [chidiwilliams/buzz#516]
It just crashes, no explanation. models are downloaded.

**Comment by Idealisten** [comment]
I have the same problem, Windows11 22H2, CPU AMD R9 7945HX, buzz 0.8.3, when I download the fast whisper model(large) the exe will crash with showing nothing, just gone

**Comment by Metawishes** [comment]
I have the same problem, too

**Comment by raivisdejus** [comment]
Please try more recent version and if the issue still repeats, see if you can get any logs

*    Mac and Linux run the app from the terminal and check the output.
*    Windows paste this into the Windows Explorer address bar %USERPROFILE%\AppData\Local\Buzz\Buzz\Logs and check the logs file.

**Comment by raivisdejus** [comment]
Latest version available here https://github.com/chidiwilliams/buzz/releases
