### ISSUE TITLE
Customizable api_base for OpenAI

### ISSUE THREAD

**Issue by ldotlopez** [chidiwilliams/buzz#521]
There some projects out there replicating the OpenAI API like [LocalAI](https://github.com/go-skynet/LocalAI).  Some organizations are using them for experimentation and local-AI powered projects. The possibility of connecting Buzz with those platforms is interesting.

The openai module already supports this by just setting an internal attribute:
```
import openai
openai.base_api = "http://someinternalhost.local/v1"
```
I made some tests by manually tweaking Buzz code and it works but it needs some UI.

The propose is to add some  UI to expose the "base API" for OpenAI to the user

Even if related [PR on LocalAI ](https://github.com/go-skynet/LocalAI/pull/721)is not accepted this would be an interesting feature for interoperability with other projects

**Comment by faspie** [comment]
I would also suggest to add a feature like that.

**Comment by raivisdejus** [comment]
Latest development version has ability to specify custom base url for OpenAI API. This can support also local LLMs running via `ollama` or other tool with API that is compatible with OpenAI API.

To get the latest development version for Linux use `sudo snap install buzz --channel latest/edge` or log into github and download the latest development version from some successful action run https://github.com/chidiwilliams/buzz/actions?query=branch%3Amain
