### ISSUE TITLE
Auto Translate Wanted

### ISSUE THREAD

**Issue by Idealisten** [chidiwilliams/buzz#527]
I have many video to be handled, they are japanese(I can't understand), but I hope the srt is English, so can you please add a function auto translate the language, as I know WhisperDesktop has this function.Thanks~

**Comment by chidiwilliams** [comment]
This should work if you select the Detect Language option before transcribing

**Comment by raivisdejus** [comment]
Latest development version has ability to translate using ChatGPT or some other AI model. Please see notes on how to use this on latest development version here https://chidiwilliams.github.io/buzz/docs/usage/translations

Feedback would be welcome.
