### ISSUE TITLE
GPU not working 

### ISSUE THREAD

**Issue by Idealisten** [chidiwilliams/buzz#528]
transcribe in progress 16% but GPU 0%, R7-6800H, but when it began GPU is 100%
it seems like buzz is using R7-6800H's CPU to transcribe, how to change to GPU?

**Comment by burbilog** [comment]
I have the same problem -- ollama uses my 3060 card just fine on debian, but buzz installed via snapd does not. I'd like to install it via pip, but my python is 3.11 and buzz requires python <= 3.10.

**Comment by raivisdejus** [comment]
Please try the latest development version `sudo snap install buzz --channel latest/edge` it has some useful improvements for running Buzz on Linux.
