### ISSUE TITLE
can't run Buzz

### ISSUE THREAD

**Issue by qianzhuo08** [chidiwilliams/buzz#530]
![image](https://github.com/chidiwilliams/buzz/assets/130830303/19986938-d0a1-42d1-bb10-2282a4a7afba)

**Comment by chidiwilliams** [comment]
Did you recently upgrade to 0.8.3 or you made a clean install?

**Comment by qianzhuo08** [comment]
Thank you for your reply. 


The issu has been resolved, I found my dir path contains "&" which casued the problem.
















At 2023-07-08 20:22:41, "Chidi Williams" ***@***.***> wrote:

Did you recently upgrade to 0.8.3 or you made a clean install?

**Comment by chidiwilliams** [comment]
Got it. Thanks for your response.
