### ISSUE TITLE
How to install buzz on Centos 7.9?

### ISSUE THREAD

**Issue by FreeSlaver** [chidiwilliams/buzz#533]
hi ,ask a question,How to install buzz on Centos 7.9? 
just download the Ubuntu deb file and then recompile and install it manually or not support?

**Comment by chidiwilliams** [comment]
Are you able to install from Snap?

sudo apt-get install libportaudio2
sudo snap install buzz

**Comment by kohasummons** [comment]
Awesome, @FreeSlaver. Resolved.

**Comment by raivisdejus** [comment]
Latest development version of the official buzz snap has some cool improvements, like fixed GPU and model downloading issues as well as ability to translate using LLMs.

To get the latest development version use `sudo snap install buzz --channel latest/edge` or see notes on running source version locally https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md
