### ISSUE TITLE
Crashes on Windows

### ISSUE THREAD

**Issue by ddb21** [chidiwilliams/buzz#539]
I get a crash whenever attempting to use Fast-Whisperer on windows (any model size).  Version. 82 and 83

**Comment by lukkzien** [comment]
Did you solve it ? I'm having the same problem

**Comment by DeafNet** [comment]
> Did you solve it ? I'm having the same problem 

You not alone on this issue

**Comment by Vaelwynn** [comment]
Same issue here

**Comment by ch826** [comment]
Ditto. Same thing here.

**Comment by enzohack2** [comment]
virus

**Comment by kaushal2012** [comment]
> I get a crash whenever attempting to use Fast-Whisperer on windows (any model size). Version. 82 and 83

hey can you please help me setup project on windows? I have to make changes because in few days, i have to show it in my college!!

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
