### ISSUE TITLE
Play button in subtitle option in windows 

### ISSUE THREAD

**Issue by johnfelipe** [chidiwilliams/buzz#541]
Is possible have play button for edit subtitle
And have sync when select subtitle
All this in windows?

**Comment by yahya8000** [comment]
> Is possible have play button for edit subtitle And have sync when select subtitle All this in windows?

**Comment by johnfelipe** [comment]
Is this possible for do it?

**Comment by chidiwilliams** [comment]
Should be available in 0.8.4
