### ISSUE TITLE
crash - bad parameters supplied by ui

### ISSUE THREAD

**Issue by fixerivan** [chidiwilliams/buzz#543]
when i select model: large it crashes because the correct parameter should be large-v2 but there isnt such option in the dropndown menu:

(base) vania@ubuntu:~/Downloads$ buzz
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
Gtk-Message: 21:34:39.767: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:34:39.767: Failed to load module "canberra-gtk-module"
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
[2023-07-23 21:34:39,823] file_transcriber_queue_worker.run:29 DEBUG -> Waiting for next transcription task

(python:17688): GLib-GIO-WARNING **: 21:34:42.834: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
ALSA lib pcm_pulse.c:758:(pulse_prepare) PulseAudio: Unable to create stream: Access denied

Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1812
ALSA lib pcm_pulse.c:758:(pulse_prepare) PulseAudio: Unable to create stream: Access denied

Expression 'r' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2097
Expression 'PaAlsaStreamComponent_FinishConfigure( &self->capture, hwParamsCapture, inParams, self->primeBuffers, realSr, inputLatency )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2730
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2842
[2023-07-23 21:34:46,639] recording.start_recording:25 ERROR -> 
Traceback (most recent call last):
  File "/snap/buzz/12/buzz/recording.py", line 21, in start_recording
    self.stream = sounddevice.InputStream(device=self.input_device_index, dtype='float32',
  File "/snap/buzz/12/lib/python3.10/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/snap/buzz/12/lib/python3.10/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/snap/buzz/12/lib/python3.10/site-packages/sounddevice.py", line 2745, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening InputStream: Unanticipated host error [PaErrorCode -9999]: 'Input/output error' [ALSA error -5]
Traceback (most recent call last):
  File "/snap/buzz/12/buzz/model_loader.py", line 162, in run
    model_path = download_faster_whisper_model(
  File "/snap/buzz/12/buzz/model_loader.py", line 101, in download_faster_whisper_model
    raise ValueError(
**ValueError: Invalid model size 'large', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2**
Fatal Python error: Aborted

Current thread 0x00007f27811f7640 (most recent call first):
  <no Python frame>

Thread 0x00007f27631eb640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 320 in wait
  File "/usr/lib/python3.10/queue.py", line 171 in get
  File "/snap/buzz/12/buzz/file_transcriber_queue_worker.py", line 33 in run

Thread 0x00007f27a8cd1740 (most recent call first):
  File "/snap/buzz/12/buzz/buzz.py", line 56 in main
  File "/snap/buzz/12/main.py", line 4 in <module>

Extension modules: PyQt6.QtCore, _cffi_backend, PyQt6.QtGui, PyQt6.QtNetwork, PyQt6.QtWidgets, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.enum, av.error, av.utils, av.option, av.descriptor, av.container.pyio, av.dictionary, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.audio.fifo, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.audio.resampler, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, yaml._yaml, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, charset_normalizer.md, frozenlist._frozenlist, torch._C, torch._C._fft, torch._C._linalg, torch._C._nn, torch._C._sparse, torch._C._special, regex._regex (total: 75)
Aborted (core dumped)

**Comment by 23992836** [comment]
I have the same problem.

**Comment by chdg61** [comment]
I have the same problem too. When I try to run any menu items or just choose any video file.
I use snap package on Linux system.

**Comment by VeeDou** [comment]
same too windows 
when i start to record 
![image](https://github.com/chidiwilliams/buzz/assets/27848735/ffffc7f3-9a0c-4206-8fbb-b2f4c3de35dc)

**Comment by Base-115** [comment]
For those that are in _GNU/Linux_, you need to check the permission and allow the options:

- audio-record
- password-manager-service
- removable-media

![Acessar_Outros_Menus_Buzz_Snap](https://github.com/chidiwilliams/buzz/assets/112908515/59f07e87-eca0-4641-a80c-f1d1afc6da11)
___

Or run the following comando in terminal:
```
sudo snap connect buzz:password-manager-service
sudo snap connect buzz:removable-media
sudo snap connect buzz:audio-record
```

**Comment by raivisdejus** [comment]
Latest version 1.0.0 or later (or snap versions after 2024-07-06) will warn user about missing SNAP permissions as well as have `large-v2` or `large-v3` models selectaable

**Comment by raivisdejus** [comment]
If it is Windows, please see if Buzz has permission to use the microphone in Settings -> Privacy -> Microphone
See method 1 in this video https://www.youtube.com/watch?v=eRcCYgOuSYQ
For method 2 there is no need to uninstall the antivirus, but see if you can temporarily disable it or if there are settings to allow Buzz use the microphone or make it a trusted application.
