### ISSUE TITLE
App not transcribing

### ISSUE THREAD

**Issue by Roentgeno** [chidiwilliams/buzz#544]
This program worked flawlessly yesterday , but today is not transcribing.  It says it is, but not producing anything.

**Comment by chidiwilliams** [comment]
Could you share which model/task type/language/version you're using?

**Comment by Roentgeno** [comment]
Hi, actually, I got it to work. I had pending updates that were jacking
with my desktop. My apologies. However, I do want to thank you
immensely for this app!  It is incredible and has saved me an unprecedented
amount of time transcribing for my dissertation. Thank you!

**Comment by chidiwilliams** [comment]
Great to hear!
