### ISSUE TITLE
Unable to delete/redownload models

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [chidiwilliams/buzz#546]
Not knowing where the download path of the model is, the model cannot be deleted or re-downloaded after downloading. This leads to the fact that if the download fails (especially for Mac M1/M2 series, it still shows downloaded), after testing normal uninstallation or app cleaner & uninstaller uninstallation and reinstallation, the models that show downloaded (actually unsuccessfully downloaded) are still there.
This leads to a weird circle: if the app crashes and exits while downloading a model, that model that failed to download will show up in the downloaded list and then never work, even with a fresh install!

**Comment by QuantumRoseinAmethystVase** [comment]
Found the path.
Whisper model file: /Users/UserName/.cache/whisper
Faster Whisper model file: /Users/UserName/.cache/huggingface/hub

**Comment by chidiwilliams** [comment]
Will mark this as closed for now. Let me know if you run into any other issues.
