### ISSUE TITLE
Italian translation of the UI

### ISSUE THREAD

**Issue by wocmultimedia** [chidiwilliams/buzz#547]
Hi,
I downloaded the buzz.po from this link https://github.com/chidiwilliams/buzz/blob/main/locale/ca_ES/LC_MESSAGES/buzz.po
then I made a translation in Italian. Here's 
[BUZZ_Locale_Italian_UI.zip](https://github.com/chidiwilliams/buzz/files/12208813/BUZZ_Locale_Italian_UI.zip)
I checked in my machine and it works perfectly.
If do you use it please, credit me in your file.
Thanks a lot.

**Comment by kohasummons** [comment]
Thanks for the contribution, @wocmultimedia 🔥

**Comment by chidiwilliams** [comment]
Updated with attribution here: https://github.com/chidiwilliams/buzz/pull/556/files#diff-71befa11ca3a0f8296f4e74d7750248ef9b042e7c54449c0c86130e242a35ec3R11. Thanks!

**Comment by wocmultimedia** [comment]
Thank you very much

3 ago 2023 00:10:58 Chidi Williams ***@***.***>:
