### ISSUE TITLE
Transcript text individual line export issue

### ISSUE THREAD

**Issue by devcpra** [chidiwilliams/buzz#554]
For version v0.8.1, when exporting the transcript as .txt file, the content exported was in paragraph format. But with v0.8.2 and v0.8.3, after exporting the transcript as .txt file, the exported content or text is on it's own individual line and not in paragraph format. This issue (text on individual lines after export to .txt format) is still there in the latest version (0.9.0, windows). How can I change this to reflect like a paragraph?

**Comment by raivisdejus** [comment]
@devcpra In the next version `1.0.2` text exports will be paragraphs again. If there is 2 or more second gap between transcription segments a new paragraph will be crated. This logic will be the same in viewing transcript as txt or exporting it as txt.

Development version with this feature is available in latest development build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
To download app from the artifact section you need to log into the github

Thanks for your report of the issue.

**Comment by devcpra** [comment]
I would request it be a single paragraph instead of it creating a new paragraph if there is 2 or more second gap between transcription segments. There is also the issue of random extra spaces between words.
