### ISSUE TITLE
Auto TXT export exit issue

### ISSUE THREAD

**Issue by devcpra** [chidiwilliams/buzz#555]
I'm using Windows 10 and v8.0.1. Sometimes when I select automatic TXT export option, the software closes and I have to open it up again. I've sometimes had this issue in v8.0.2 and v8.0.3.

**Comment by PrinceDisant** [comment]
I am a software developer and would be willing to help you with this. Please provide more information.

**Comment by devcpra** [comment]
I open Buzz (v8.0.1) on Windows 10. Sometimes the TXT export option is selected (tick mark). If I unselect it, Buzz closes. Then, I have to open it again. This has also happened with v8.0.2 and v8.0.3.

**Comment by raivisdejus** [comment]
Assume this is no longer an issue in latest releases https://github.com/chidiwilliams/buzz/releases

**Comment by devcpra** [comment]
I have tested this on a few files and there seems to be no issues as of now. If any issues do arise, i'll open another ticket or will inform you about this. Thanks.
