### ISSUE TITLE
Types of English language

### ISSUE THREAD

**Issue by thejonnyjon** [chidiwilliams/buzz#563]
Is it possible to have an option that could allow users to select types of English such as English (US), English (UK), etc?

**Comment by chidiwilliams** [comment]
Whisper does not support US/UK dialects, but you can use the Advanced Settings > Initial Prompt to prompt the model towards UK/US dialects.

For example, you can select English and transcribe, then start a new transcription with US spellings for some of the words in the transcription, e.g. "color, analyze, traveling". The resulting transcription will have more US spellings. It's not as good a solution as just having a specific English (US), but it should work.
