### ISSUE TITLE
Crash for no reason

### ISSUE THREAD

**Issue by DeafNet** [chidiwilliams/buzz#566]
I don't understand why it keep crashing on large models when I did not disturb anything but allow it running it own. Anyone know why ? I am hoping it does not doing the same with Mac one I brought it on Mac.

**Comment by chidiwilliams** [comment]
Does it work with the latest version, 0.8.4?

**Comment by DeafNet** [comment]
> so far, it still going.

**Comment by DeafNet** [comment]
@chidiwilliams it still crashing. 

At first 45 min it work well, it just each audio 3 to 5 min then after that it crash. It does not show why it crash. Every time I pull up , it keep crashing after it start running. What can I do to help to improve this system ?
