### ISSUE TITLE
Not working in Hebrew

### ISSUE THREAD

**Issue by amithunter** [chidiwilliams/buzz#568]
It won't show the right captions at all (not even the right number of words in a time frame) and it's showing russian letters instead of hebrew.

<img width="875" alt="image" src="https://github.com/chidiwilliams/buzz/assets/142341761/5570c672-1a9f-4f82-914b-f1c4d8abc19d">

**Comment by chidiwilliams** [comment]
Does it work well when you select the 'Detect Language' option?

**Comment by amithunter** [comment]
Yes it is, but the output is each word individually. Can’t work with that for subtitles.

**Comment by chidiwilliams** [comment]
Fix should be out later this week.

**Comment by amithunter** [comment]
Thank you! please please please reply when it's fixed!

**Comment by amithunter** [comment]
> Fix should be out later this week.

any update?

**Comment by chidiwilliams** [comment]
Yeah, the new build is waiting for App Store review. It typically takes 2-3 days, I'll update here once it's done.

**Comment by amithunter** [comment]
> Yeah, the new build is waiting for App Store review. It typically takes 2-3 days, I'll update here once it's done.

Hey again! Any news?

**Comment by chidiwilliams** [comment]
Hey, this should be live on the App Store now. Sorry for the delay, had a bit of a long back-and-forth with the App Store review. Pls let me know if this works for you now.

**Comment by amithunter** [comment]
Now it's working when i'm selecting Hebrew, but it still exporting word by word and not sentences. Really upsetting.

<img width="531" alt="image" src="https://github.com/chidiwilliams/buzz/assets/142341761/b13aa82e-9f01-4e61-9a0f-72e5143a62d9">

**Comment by chidiwilliams** [comment]
Missed this message. Could you turn off the "Word-level timings" option?

<img width="503" alt="image" src="https://github.com/chidiwilliams/buzz/assets/17879672/3f1d3f79-04f3-4fdf-b55f-17e63388d31c">
