### ISSUE TITLE
Release crashes on Windows

### ISSUE THREAD

**Issue by moebiussurfing** [chidiwilliams/buzz#57]
Hello, thanks for sharing.
I am getting this error.
Also when opening as admin
![image](https://user-images.githubusercontent.com/2106149/195278950-684a269c-d60d-4365-a3da-0ca6fa47341d.png)
Cheers

**Comment by moebiussurfing** [comment]
btw, the Build/run locally / poetry worked.

**Comment by chidiwilliams** [comment]
Yes, I have a fix for that, but haven't released yet. Will update this thread soon.

**Comment by moebiussurfing** [comment]
PS. What do you use to convert a "Py script stuff" to a "windowed binary app"?

**Comment by chidiwilliams** [comment]
Fixed release in 0.3.4: https://github.com/chidiwilliams/buzz/releases/tag/v0.3.4

**Comment by chidiwilliams** [comment]
> PS. What do you use to convert a "Py script stuff" to a "windowed binary app"?

PyInstaller bundles the app into binaries: https://pypi.org/project/pyinstaller/
