### ISSUE TITLE
Failed to execute script 'main' due to unhandled exception

### ISSUE THREAD

**Issue by EthanShotz** [chidiwilliams/buzz#570]
**Getting this error after installing and attempting to run the .EXE with Admin Privileges"**
![2023-08-16 16_19_40-Unhandled exception in script](https://github.com/chidiwilliams/buzz/assets/6538217/fdc91b00-6800-45b1-b8ab-9e34b34c980a)

Failed to execute script 'main' due to unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 54, in main
  File "buzz\gui.py", line 1305, in __init__
  File "buzz\gui.py", line 849, in __init__
  File "buzz\gui.py", line 978, in load_tasks_from_cache
  File "buzz\cache.py", line 23, in load
  File "buzz\cache.py", line 36, in load_json_tasks
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DeafNet** [comment]
Same here and I had to switch to Mac and buy his app and using it for while

**Comment by chidiwilliams** [comment]
@EthanShotz, did you have an earlier app version, or is this on the first install? Also, do you have any cache file at `C:\Users\<username>\AppData\Local\Buzz\Buzz\Cache`?

**Comment by chidiwilliams** [comment]
@DeafNet were you also on Windows?

**Comment by chidiwilliams** [comment]
Could you pls share your OS/version?

**Comment by DeafNet** [comment]
> @DeafNet were you also on Windows?

Yes I was on windows, it was window 11 and your latest update version. It stop function and switch to Mac. It is really slow when I use Mac.

**Comment by EthanShotz** [comment]
**Update:** I installed Version 0.8.2 and that is working correctly, but 0.8.3 installation is still getting the error.

0.8.2 was working initially, but it suddenly stopped working a few days ago.

I'm on Windows 11 Pro Version 10.0.22621 Build 2262

Here is what I'm seeing in the 0.8.2 Cache Folder currently:
![image](https://github.com/chidiwilliams/buzz/assets/6538217/c88a903d-9b8c-45f6-b588-9a8efdf337a7)

**Comment by chidiwilliams** [comment]
Thanks for the info. I've found the issue and there should be a fix in a new version soon.

**Comment by DeafNet** [comment]
Here is my version ![image](https://github.com/chidiwilliams/buzz/assets/70997786/516147ed-c486-494a-8b4c-fe38dff146b9)
