### ISSUE TITLE
Crash on 0.8.4 on window

### ISSUE THREAD

**Issue by DeafNet** [chidiwilliams/buzz#581]
I still have problems crashing out of nowhere after it working for 45 min.

**Comment by DeafNet** [comment]
So it is connect to my hard drive external and if I open my hard drive external file and running with buzz. It is seem to be running without crash.

**Comment by chidiwilliams** [comment]
What model settings and audio length are you transcribing with? Also, if you check your task manager, is your computer running out of memory when transcription is in progress? I think this might have to do with running out of system resources - great to hear that it works with your external hard drive, though. Let me know if you still have issues with it.

**Comment by chidiwilliams** [comment]
Got it. Also the fix for Buzz Captions auto-export should be out on the App Store later this week.

**Comment by DeafNet** [comment]
> Got it. Also the fix for Buzz Captions auto-export should be out on the App Store later this week.

Thank you so far, as long as I keep my hard drive extended open on my window. It work as much it can.

**Comment by chidiwilliams** [comment]
I'll close this for now. Let me know if you have any further issues.
