### ISSUE TITLE
pre-existing text with audio

### ISSUE THREAD

**Issue by DeafNet** [chidiwilliams/buzz#582]
Is there a way you can make this work ? Just asking ? 

pre-existing text with audio into Srt ?

**Comment by chidiwilliams** [comment]
Is this same as #584? I left a comment there.

**Comment by DeafNet** [comment]
> Is this same as #584? I left a comment there.

Just put the message there

**Comment by raivisdejus** [comment]
@DeafNet you would like to load (import) some text? Regular text with no timestamps? Or subtitle files with timestamps.

If you want to align existing good text with audio you need to look for "[Forced alignment](https://github.com/topics/forced-alignment)" tools. Tools based on AIs like whisper will not be super precise, so look for some non-AI tools. 

[echogarden](https://github.com/echogarden-project/echogarden) is a very good and precise tool that can do forced alignment.
