### ISSUE TITLE
`poetry install` does not install `buzz`

### ISSUE THREAD

**Issue by paulmenzel** [chidiwilliams/buzz#585]
Using version 0.8.4, and on GNU/Linux running

    $ pip install poetry
    $ poetry install

there is no tool `buzz` installed in `~/.local/bin`. Running `poetry run python main.py` works, but the CLI tool, [mentioned in the documentation](https://chidiwilliams.github.io/buzz/docs/cli), is not installed.

**Comment by raivisdejus** [comment]
See notes on running locally https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md

Try running `poetry build` to build the `*.whl` and then install it from `./dist` folder. Or just use snap https://snapcraft.io/buzz
