### ISSUE TITLE
Windows version: ignore GPU during processing (still not fix as that issue is nr. 3 from what I see)

### ISSUE THREAD

**Issue by jurandfantom** [chidiwilliams/buzz#587]
I removed Buzz couple month ago as it was slow and buggy. Now when its more stable, I still see uber low speeds caused by not loading models to GPU and use that hardware (RTX4090 btw) for processing. For now I use WhisperDesktop, but really wish to swap it for project that is keep alive and constantly improved. 

What could be possible cause of that issue? My windows contain all set of NVIDIA GPU Computing Toolkit\CUDA\ pythons and whatever is needed to run text2img, text2voice, voice2text and such projects.

**Comment by AlmostHuman34** [comment]
Yeah, it never worked for me to use CUDA with BUZZ. There has been few tries from creator to implement it.

**Comment by raivisdejus** [comment]
Linux version has full support for use of GPU. As models can be big and if they do not fit the GPU VRAM app will crash, for now Buzz for Huggingface Whisper will use GPU if it has at least 10GB VRAM. 

Whisper and Faster Whisper are also configured to use GPU if it is available, no additional checks for VRAM size.

Support for GPU on Windows is available for the source version, see https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows.

**Comment by raivisdejus** [comment]
Latest version 1.0.0 should support CUDA GPUs with no VRAM checks. https://github.com/chidiwilliams/buzz/releases

Please re-open the issue if Windows GPU still has some issues
