### ISSUE TITLE
How can compile for windows?

### ISSUE THREAD

**Issue by johnfelipe** [chidiwilliams/buzz#593]

**Comment by johnfelipe** [comment]
I want to compile .exe with latest changes, can u create MD file with steps??

**Comment by raivisdejus** [comment]
Steps for running locally are now described here https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md
Windows build tool setup is incomplete and I can't find all the missing steps to get the tools needed, so the guide will try to use pre-compiled `whisper.dll`. Feedback on if this works properly is highly welcome.

The easiest way to get `.exe` with latest version of the app is to fork the repo and run `Manual build` action on your forked repo. Application files will be attached to `Artifacts` section of your build on your forked repo.

Run it like this from your forked repo
![attels](https://github.com/chidiwilliams/buzz/assets/5319134/6733a6dd-8822-44ad-ad1a-6c88259813b8)

Get the app files
![attels](https://github.com/chidiwilliams/buzz/assets/5319134/3fadf3ba-08f0-43e1-9f20-093afcd7f6de)
