### ISSUE TITLE
Where can i download models by hand?

### ISSUE THREAD

**Issue by Tridu33** [chidiwilliams/buzz#594]
i want to download models by hand because  `Download failed: A connection error occurred`
is there any url i can downlaod models?
Whisper model file: /Users/UserName/.cache/whisper
Whisper.cpp file: /Users/UserName/Library/Caches/Buzz
Faster Whisper model file: /Users/UserName/.cache/huggingface/hub

**Comment by lin-du** [comment]
Having same issue here. Please help.

**Comment by Vinfall** [comment]
You can get the modesl on HuggingFace:
- [Whisper.cpp](https://huggingface.co/ggerganov/whisper.cpp/tree/main)
- faster-whisper stores models in different repos, you can get large-v2 model [here](https://huggingface.co/guillaumekln/faster-whisper-large-v2/tree/main)

Remember to **rename** the model. Check logs (on Windows, it's `%LOCALAPPDATA%\Buzz\Buzz\Logs`) for the desired path (on Windows, mine is `C:\Users\USERNAME\.cache\whisper`, but it used to be `C:\Users/USERNAME\AppData\Local\Buzz\Buzz\Cache`) & filename. You can see the direct download URL by the way.

I think it's also stored in the code:
https://github.com/chidiwilliams/buzz/blob/a3b54891e8c403d28b7bf2d86443ad310d2d1b51/buzz/model_loader.py#L108-L118
