### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by DeafNet** [chidiwilliams/buzz#597]
![image](https://github.com/chidiwilliams/buzz/assets/70997786/8f76ae75-b1b8-4bf8-a69a-72c93a7cf603)it simple stop working when I got one audio running and it reach to 92%

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases

If still a problem please paste this `%USERPROFILE%\AppData\Local\Buzz\Buzz\Logs` in windows address bar to get tot the Logs folder. There will be a `logs` file that may have useful information to identify the problem.

**Comment by raivisdejus** [comment]
Please re-open if more information is available
