### ISSUE TITLE
English audio cannot be translated into chinese

### ISSUE THREAD

**Issue by nillight** [chidiwilliams/buzz#598]
English audio cannot be translated to Chinese (although I have selected the task:"translate" and chosen the "language":detect language/chinese/english)
I'll be glad if you solve my confusion

**Comment by nillight** [comment]
I had used it successfully on August 26th, but I can't use it now.

**Comment by raivisdejus** [comment]
Whisper supports only translating to English.

Latest development versions of Buzz support translation via ChatGPT or some local AI. For more info see https://chidiwilliams.github.io/buzz/docs/usage/translations

**Comment by nillight** [comment]
> Whisper supports only translating to English.
> 
> Latest development versions of Buzz support translation via ChatGPT or some local AI. For more info see https://chidiwilliams.github.io/buzz/docs/usage/translations

Does this mean that only other languages can be translated into English?
If so, thank you for helping me close this question.
But if not, why you close it? There has no one answer this.
(Sorry for my terrible English cause I'm not a guy always speak English.)

**Comment by raivisdejus** [comment]
Yes whisper "translation" feature is meant to translate only to English, or at least it works well only when translating only to English. To translate to other languages you need to use the "AI translation" feature, that will use some AI, like ChatGPT to translate to any language.

**Comment by nillight** [comment]
> Yes whisper "translation" feature is meant to translate only to English, or at least it works well only when translating only to English. To translate to other languages you need to use the "AI translation" feature, that will use some AI, like ChatGPT to translate to any language.

Oh, that's a pity, but I still thank you for solve my issue  o(*￣3￣)o 
(Still sorry for my terrible English (；へ：)
