### ISSUE TITLE
Help setting up audio loopback driver in windows

### ISSUE THREAD

**Issue by algo-se** [chidiwilliams/buzz#599]
Hi, I would like to use Buzz to transcribe audio playing from my computer (windows 11). I've read the [docs](https://chidiwilliams.github.io/buzz/docs/usage#record-audio-playing-from-computer-macos), and I have installed [Virtual Audio Cable](https://vac.muzychenko.net/en/) but I can't figure out how to make it work. Does anyone know how to make it work on Windows? Or could you send me a tutorial where they explain it?

**Comment by raivisdejus** [comment]
Please see https://chidiwilliams.github.io/buzz/docs/faq

You will need https://vb-audio.com/Cable/
