### ISSUE TITLE
Dear author, I have encountered some problems and hope to get your help

### ISSUE THREAD

**Issue by Knowhoi** [chidiwilliams/buzz#604]
I ran the program normally today, and after deleting some of the running results, the error report kept popping up, and the reinstallation was invalid
!
![1695479822701](https://github.com/chidiwilliams/buzz/assets/145854856/ba7d7cba-641d-4ddb-9870-84666e25c53f)

**Comment by chidiwilliams** [comment]
Could you try deleting the cache file at `C:\Users\<username>\AppData\Local\Buzz\Buzz\Cache` and trying again?

**Comment by Knowhoi** [comment]
its work！ thank you
