### ISSUE TITLE
App Store  is  Buzz

### ISSUE THREAD

**Issue by mukgong** [chidiwilliams/buzz#605]
It is better on the App Store. Get a Mac-native version of Buzz with a cleaner look, audio playback, drag-and-drop import, transcript editing, search, and more.
Mac Air M2, 1 hour of Chinese conversation audio, using the Medium model, has not been completed after 3 hours. I dare not purchase from the App Store.

**Comment by aycajr** [comment]
Wanted to Support it but it's showing me to download later. Not sure why.
![CleanShot 2023-11-07 at 10 05 32@2x](https://github.com/chidiwilliams/buzz/assets/18382126/3266dbb4-9170-4ad9-ac2c-ada2267c7aa3)

**Comment by chidiwilliams** [comment]
@aycajr  Do you have the open-source version installed? If so, you need to uninstall it first.

**Comment by raivisdejus** [comment]
Closing as stale, please re-open with more information if still relevant
