### ISSUE TITLE
New feature support required - OpenAI Whisper in Azure OpenAI service.

### ISSUE THREAD

**Issue by JackyWay** [chidiwilliams/buzz#606]
Can we have support for Azure OpenAI Whisper? Thanks.

https://techcommunity.microsoft.com/t5/azure-ai-services-blog/announcing-the-preview-of-openai-whisper-in-azure-openai-service/ba-p/3928388

**Comment by Khrees2412** [comment]
> Can we have support for Azure OpenAI Whisper? Thanks.
> 
> https://techcommunity.microsoft.com/t5/azure-ai-services-blog/announcing-the-preview-of-openai-whisper-in-azure-openai-service/ba-p/3928388

What's the difference?

**Comment by raivisdejus** [comment]
Translation feature and abilty to specify custom baseurl for OpenAI API has been added to the latest main branch. See instructions on how to use translations or get the latest development version here https://chidiwilliams.github.io/buzz/docs/usage/translations

This is very fresh feature, some hikups are possible. If you encounter them, please report. Feedback on if the overall usage is clear and intuitive to understand would be welcome.
