### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [chidiwilliams/buzz#607]
hello my friend...what amazing project...congratulations!please tell me something if  I wan transcribe correct I have to choose at least medium...there is some way to transcribe faster?and if yes,can you explain me what I have to do?

                                                            THANKS A LOT!!!

**Comment by raivisdejus** [comment]
The bigger the model, the more quality it will have. Quality will also depend on language, some have good quality, some not so good. As this is quite resource intensive work for the computer a way to make it faster is to get a GPU video card. Transcribing on GPU video cards will be faster. Fastest model to run on a CPU without a GPU video card is Whisper.cpp

**Comment by raivisdejus** [comment]
To speed up Buzz you can use external API servers and transcribe on GPUs provided by them. 
Get the latest version - https://github.com/chidiwilliams/buzz/releases
See APIs that you could use - https://github.com/chidiwilliams/buzz/discussions/827
