### ISSUE TITLE
Cannot download models due to network errors

### ISSUE THREAD

**Issue by lin-du** [chidiwilliams/buzz#608]
I tried to download whisper.cpp - Large model from the app, but it kept saying "Request failed: The network connection was lost.
Check your network settings and try again." Is there a reason for this error? 

As a workaround, I downloaded ggml-large.bin and wanted to save in the model stored folder. However, there's no such a folder exists as ~/Library/Caches/Buzz (Mac OS). So where this folder might be? And what else should I do after pasting ggml-large.bin to that folder?

I'm using Mac Air M2 chip. Thanks.

**Comment by raivisdejus** [comment]
For Apple silicon please try the latest version 1.1.0
For Intel get the version from latest development build (you need to log into the github to see the artifact download button) https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

Also maybe you find useful the advanced preference feature to specify custom model download folder https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences

For info on model locations see FAQ https://chidiwilliams.github.io/buzz/docs/faq

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
