### ISSUE TITLE
Program Keeps Crashing

### ISSUE THREAD

**Issue by Dylan66** [chidiwilliams/buzz#609]
I have been using the Buzz app for approximately one month on my Windows machine. Currently, it keeps crashing and displaying this error when I attempt to open it. 
![image](https://github.com/chidiwilliams/buzz/assets/18328808/15d93b60-b027-4b34-a494-3ba79f64c848)

**Comment by rawwerks** [comment]
i'm having the same problem on os x with the latest .dmg binary.

**Comment by raivisdejus** [comment]
1. Try the latest version from Releases section https://github.com/chidiwilliams/buzz/releases
2. Find your cache folder https://chidiwilliams.github.io/buzz/docs/faq and delete any `*.json` and `.sqlite` files. Can delete all files in the cache folder
