### ISSUE TITLE
Error Download failed

### ISSUE THREAD

**Issue by SWxEng** [chidiwilliams/buzz#613]
hi @chidiwilliams 

Error Download failed  A connection error occurred in buzz

It happened twice at Download 99%.

Why and what is the solution?

![image](https://github.com/chidiwilliams/buzz/assets/55116927/2b0eaa74-61c7-44f5-8880-55e54d2882d7)

**Comment by yaniv-coupang** [comment]
+1

**Comment by raivisdejus** [comment]
Please try latest version https://github.com/chidiwilliams/buzz/releases
