### ISSUE TITLE
Keystroke audio recording

### ISSUE THREAD

**Issue by yahorbarkouski** [chidiwilliams/buzz#62]
Hey man, firstly wanna say thanks for this cool app! I'm just wondering about one feature: 

> audio recording will not last a specific time until you press stop, but as long as you press one of the keypad buttons

You could think of it as a Discord  / any video game microphone button that only records you as long as you press the key. I'm just also wondering about building an opensource "Developer Assistant" using Whisper, and I thought your app with such a feature would be pretty handy 🙌

**Comment by chidiwilliams** [comment]
Hey, thanks for the feedback! The keypad button idea sounds quite good. There are some other UI improvements I'm looking to make soon as well.

Also, what do you mean by a Developer Assistant?

**Comment by yahorbarkouski** [comment]
There are lazy programmers who like to automate everything (like me), I wrote a couple of scripts for myself that allow to open PR in gitlab/hub by calling the command for you with all the needed metadata, and I thought that using Whisper we could automate things even more: besides integration with git we can make notes / ideas tracking by voice (most useful here) in notion, sending messages to slack / teach helper to open the right sites and do other things, which I have not yet had enough imagination. Anyway it's just an idea for now, but it seems to me that your application is a really good base for it

**Comment by chidiwilliams** [comment]
Ah, got it. Sounds interesting.
