### ISSUE TITLE
Button "run" is greyed out after canceling progress

### ISSUE THREAD

**Issue by RooTender** [chidiwilliams/buzz#622]
# Description
When I load the audio or video and click on `run` button, when I then click on `cancel` (to cancel some process like downloading model etc) I still have the `run` button greyed out.

![image](https://github.com/chidiwilliams/buzz/assets/24989290/e8e132b1-aac6-4b68-b3c5-adfa88db0ef9)

**Comment by raivisdejus** [comment]
Will be fixed in next release. Thanks for reporting.
