### ISSUE TITLE
After downloading the model with coreML, the version of Mac cannot run properly. Is there any way to delete the model and download it again? Also, can you provide a new version of Whisper for download?

### ISSUE THREAD

**Issue by RonanDex** [chidiwilliams/buzz#627]

**Comment by chidiwilliams** [comment]
You can find the models stored here: `~/Library/Containers/com.chidiwilliams.Buzz/Data/Library/Application Support/Buzz/Models`. The next version will add support for deleting/re-downloading CoreML models. The new version of Whisper will also be added shortly.

**Comment by RonanDex** [comment]
Great job

**Comment by chidiwilliams** [comment]
Available now https://apps.apple.com/gb/app/buzz-captions/id6446018936?mt=12

**Comment by RonanDex** [comment]
<img width="184" alt="截屏2023-11-16 11 35 04" src="https://github.com/chidiwilliams/buzz/assets/4251021/15cb7028-8a9b-4e65-877a-fc32aa27929f">

I have already updated, but there are still a few issues.

1. The model list does not distinguish between v3 and other models. I'm not sure if all of them are using the v3 model.

2. I used the original recording for recognition in small and tiny, but the accuracy has decreased. I don't know if this is an exception. I will try with other recordings.

3. The speed of medium recognition seems to be slower than before? It needs further observation.

One of the important scenarios for me to use Buzz is real-time recognition, so small and tiny have a greater impact on me.

Thank you for updating so quickly, it's appreciated!

**Comment by RonanDex** [comment]
Just to add, the medium recognition is completely ineffective and cannot be used at all...

**Comment by RonanDex** [comment]
<img width="407" alt="截屏2023-11-16 12 31 55" src="https://github.com/chidiwilliams/buzz/assets/4251021/0ae18161-8705-4b34-8902-077bc38a98e1">

**Comment by RonanDex** [comment]
After updating the model, the recognition is back to normal. However, I still hope to have the freedom to choose v3 and other models. Thank you.

**Comment by chidiwilliams** [comment]
> The model list does not distinguish between v3 and other models. I'm not sure if all of them are using the v3 model.

OpenAI only releases Large models of the new versions, so there's a Large v2/v3, but only v1 for the other size. I'll work on adding Large v1 and v2 options in the next version. Glad to hear everything else works fine now.

Also, if you could leave a star rating review on the App Store, that would be very appreciated. Thanks!

**Comment by RonanDex** [comment]
Five-star rating
