### ISSUE TITLE
Crashing nonstop on model downloads and transcription attempts.

### ISSUE THREAD

**Issue by jmilldotdev** [chidiwilliams/buzz#629]
All models and settings, latest version (0.8.4), M1 MBP

**Comment by raivisdejus** [comment]
For Apple silicon please try the latest version 1.1.0
For Intel get the version from latest development build (you need to log into the github to see the artifact download button) https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
