### ISSUE TITLE
The app is crashing

### ISSUE THREAD

**Issue by g123k** [chidiwilliams/buzz#634]
Hello,

Thanks for your application, however on the latest version (Version 0.3.0 (112)) downloaded from the App Store, I have a crash when:

1. Right-click on a transcription
2. Select Delete
3. Confirm with Delete
4. Crash

There is no log in the console.

**Comment by ndillmanhasso** [comment]
+1, having this issue. Originally thought it was just when files were unable to be accessed (I had an issue with some file paths changing while I was starting the transcription process), but according to OP it happens nevertheless.

**Comment by chidiwilliams** [comment]
Thanks for the feedback. Will be fixed in a coming release.

**Comment by jordiprenafeta** [comment]
+1 having this issue in a Macbook Pro M2 Pro Max with MacOS Sonoma 14.2.
When is this new release expected to be launched approximately?

**Comment by chidiwilliams** [comment]
Submitted to the App Store earlier today, and it should be available for use in a couple of days. Thanks.

**Comment by Sircam19** [comment]
Hello just wondering what changes we could expect

**Comment by Sircam19** [comment]
![CleanShot 2024-01-15 at 18 41 44](https://github.com/chidiwilliams/buzz/assets/4651001/a51993bd-9984-411d-ad53-0e686ffd65d1)

**Comment by chidiwilliams** [comment]
@g123k @jordiprenafeta The update is available now. Please let me know if you face any other issues!

**Comment by ndillmanhasso** [comment]
Fixed it for me! Thanks, Chidi.

**Comment by wasauce** [comment]
@chidiwilliams Do you plan on doing another release here? last release is from I think Aug 2023. 

Can I be of help in setting up a build system / github actions to do builds as new code is merged into main?

**Comment by jordiprenafeta** [comment]
> @g123k @jordiprenafeta The update is available now. Please let me know if you face any other issues!

Fixed for me with this new version. Thank you.
