### ISSUE TITLE
UI enhancement: Indicate task of operation and others

### ISSUE THREAD

**Issue by AltayYuzeir** [chidiwilliams/buzz#637]
Hello. Thank you for all the time, effort and love you are putting into this really user-friendly interface. 
When we select a file to be processed, we select the model, language and task to be done (Transcription or Translation).
I believe it will be useful perhaps all these parameters are indicated as columns in the Queue table. Currently the Queue table has only 2 columns - File Name and Status. With the current setup, when something goes wrong, I find it difficult to troubleshoot batch file operations, especially if files need to be both translated and transcribed. Thank a lot once again!

**Comment by chidiwilliams** [comment]
Thanks for your kind words! Your suggestion will be added in the next release.
