### ISSUE TITLE
it's not working well in Sonoma 14.0

### ISSUE THREAD

**Issue by raultaboraz** [chidiwilliams/buzz#641]
Hello, 

First, congratulations for this idea?  Much better than terminal commands... I have bought it but I have a problem

I have transcribed a 1h m4a file, It took 40 minutes (using Large model) but the SRT result is very poor, only few lines of 1 hour conversation is not correct.

How can I investigate what happens here?

I have tried whisper (openai) and I am able to get a transcription from that file.

Thanks

**Comment by raivisdejus** [comment]
Most likely something with the model. Things to try:
- Get the latest version `1.1.0`
- Try shorter audio to see if model works fine in principle
- Try different model size
- Try different Whisper type (Whisper or Whisper.cpp)
- Try specifying language, whisper models can some times guess language wrong and then you get garbage.

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
