### ISSUE TITLE
AV Security issue reported on your doc site

### ISSUE THREAD

**Issue by tohagan** [chidiwilliams/buzz#647]
My AVG anitvirus product reports a phishing link from this URL:

- https://chidiwilliams.github.io/buzz/docs/usage

Note the reference to existential.audio . 

![image](https://github.com/chidiwilliams/buzz/assets/301525/7f7fecd2-0d31-43ce-8da8-8b6654e66836)

**Comment by raivisdejus** [comment]
Is it still being reported as dangerous?

**Comment by tohagan** [comment]
Looks OK now. I tested all the docs pages.
