### ISSUE TITLE
Ubuntu, version 0.82 crashes on opening preferences

### ISSUE THREAD

**Issue by MWH-Rookie** [chidiwilliams/buzz#648]
Dear all
I am not experienced with using github, so I hope that I do this right. I want to report an issue with the buzz snap version. I use Ubuntu 22.04 LTS. The version of buzz seams to be 0.82.
Actually I could not record anything, but as I wanted to check the preferences, the app crashes. Then I started the app from the shell.

Before the crash, this was the output:
`buzz
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
Gtk-Message: 14:22:45.335: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:22:45.336: Failed to load module "canberra-gtk-module"
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /snap/buzz/12/usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
[2023-12-20 14:22:45,413] file_transcriber_queue_worker.run:29 DEBUG -> Waiting for next transcription task
`

Then when I click on "help" -> "preferences" in the GUI the app crashes. Then this appears on the shell:

`[2023-12-20 14:23:56,977] backend._load_plugins:201 DEBUG -> Loading KWallet
[2023-12-20 14:23:56,979] backend._load_plugins:201 DEBUG -> Loading SecretService
[2023-12-20 14:23:57,005] backend._load_plugins:201 DEBUG -> Loading Windows
[2023-12-20 14:23:57,054] backend._load_plugins:201 DEBUG -> Loading chainer
[2023-12-20 14:23:57,054] backend._load_plugins:201 DEBUG -> Loading libsecret
[2023-12-20 14:23:57,055] backend._load_plugins:201 DEBUG -> Loading macOS
Traceback (most recent call last):
  File "/snap/buzz/12/buzz/gui.py", line 1279, in on_preferences_action_triggered
    preferences_dialog = PreferencesDialog(shortcuts=self.shortcuts, parent=self)
  File "/snap/buzz/12/buzz/widgets/preferences_dialog.py", line 24, in __init__
    general_tab_widget = GeneralPreferencesWidget(parent=self)
  File "/snap/buzz/12/buzz/widgets/general_preferences_widget.py", line 19, in __init__
    self.openai_api_key = keyring_store.get_password(KeyringStore.Key.OPENAI_API_KEY)
  File "/snap/buzz/12/buzz/store/keyring_store.py", line 16, in get_password
    password = keyring.get_password(APP_NAME, username=key.value)
  File "/snap/buzz/12/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/snap/buzz/12/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/snap/buzz/12/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/snap/buzz/12/lib/python3.10/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/snap/buzz/12/lib/python3.10/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/snap/buzz/12/lib/python3.10/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/snap/buzz/12/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.AccessDenied] ('An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.421" (uid=1000 pid=64508 comm="python /snap/buzz/12/main.py " label="snap.buzz.buzz (enforce)") interface="org.freedesktop.DBus.Properties" member="Get" error name="(unset)" requested_reply="0" destination="org.freedesktop.secrets" (uid=1000 pid=3035 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")',)
Fatal Python error: Aborted

Thread 0x00007fa1e8df3640 (most recent call first):
  File "/usr/lib/python3.10/threading.py", line 320 in wait
  File "/usr/lib/python3.10/queue.py", line 171 in get
  File "/snap/buzz/12/buzz/file_transcriber_queue_worker.py", line 33 in run

Current thread 0x00007fa2149d6740 (most recent call first):
  File "/snap/buzz/12/buzz/buzz.py", line 56 in main
  File "/snap/buzz/12/main.py", line 4 in <module>

Extension modules: PyQt6.QtCore, _cffi_backend, PyQt6.QtGui, PyQt6.QtNetwork, PyQt6.QtWidgets, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.enum, av.error, av.utils, av.option, av.descriptor, av.container.pyio, av.dictionary, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.audio.fifo, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.audio.resampler, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, yaml._yaml, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, charset_normalizer.md, frozenlist._frozenlist, torch._C, torch._C._fft, torch._C._linalg, torch._C._nn, torch._C._sparse, torch._C._special, regex._regex (total: 75)
Aborted (core dumped)`

Can you make something out of it? What further information should I provide?

**Comment by faveoled** [comment]
You should enable permissions for the app using Ubuntu Software app

**Comment by MWH-Rookie** [comment]
There I allowed everything accept for "Read, add, change, or remove saved passwords".

**Comment by faveoled** [comment]
Yeah, I can see it needs that for storing and reading API keys
