### ISSUE TITLE
I can‘t install buzz caption in my M1 macbook air from MacStore

### ISSUE THREAD

**Issue by SiYangming** [chidiwilliams/buzz#651]
<img width="725" alt="Snipaste_2023-12-21_14-00-31" src="https://github.com/chidiwilliams/buzz/assets/20296009/b6f7fede-cc39-4c31-95a9-a10633c2031b">
Always stop as figure shown.

**Comment by chidiwilliams** [comment]
Do you have the open-source version installed? Can you try deleting it before installing the one from the App Store?
