### ISSUE TITLE
An error occurred while loading the Whisper model: A connection erroroccurred.Please retry or check the application logs for more information.

### ISSUE THREAD

**Issue by caidesi** [chidiwilliams/buzz#654]
![Uploading 微信截图_20231226160244.png…]()

**Comment by RayonYou** [comment]
How to  fix this problem? I have the same problem,but i cant see your picture

**Comment by Barmaid1076** [comment]
same

**Comment by raivisdejus** [comment]
See [FAQ](https://chidiwilliams.github.io/buzz/docs/faq) for how to find cache folder. Delete the cached data and try again.

Will see if we can make this more user friendly in future versions

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
