### ISSUE TITLE
Some of word not splitting

### ISSUE THREAD

**Issue by prithiviclteam** [chidiwilliams/buzz#657]
Hi,

I have tested your Buzz app, and the data quality is good. However, some lines are not splitting in the output. For example below and I have attached respative files and mp3 files for testing: 

22
00:00:11,940 --> 00:00:13,169
 **of Mum's flowers,**

27
00:00:10,679 --> 00:00:10,769
 many

28
00:00:10,769 --> 00:00:11,360
 **kids with one leg kicking footballs he thought.**

[
[Buzz_Testing.zip](https://github.com/chidiwilliams/buzz/files/13792157/Buzz_Testing.zip)
](url)

**Comment by raivisdejus** [comment]
How words and sentences are returned depends on the model configuration during training. If some model does not split words or sentences as you need you can try different model. Discussion thread to collect good custom models is here https://github.com/chidiwilliams/buzz/discussions/866

Also in the upcoming `1.0.2` version there will be a feature that lets you resize subtitles after they have been generated. This feature is available in latest development version. See artifact section of the development builds https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
To download log into the github.
