### ISSUE TITLE
启动时找不到序数

### ISSUE THREAD

**Issue by zc188** [chidiwilliams/buzz#667]
启动失败，提示无法定位序数380于动态链接库 xxxxx\path\Buzz.exe 上
![图片](https://github.com/chidiwilliams/buzz/assets/41810347/7615d1cc-20ca-426b-abbb-9ff89c205be6)

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases

**Comment by zc188** [comment]
已收到，谢谢！
