### ISSUE TITLE
Feature Request: Copy transcript to clipboard

### ISSUE THREAD

**Issue by kanjieater** [chidiwilliams/buzz#669]
A lot of language learning tools rely on either getting data via clipboard or websocket for quick lookups of words you don't know. Adding something that could copy the text to your clipboard would be a big help.

**Comment by raivisdejus** [comment]
@kanjieater current version in transcription editor window already has option to select and copy some word to clipboard. 
Steps to do it:
1. Open some transcript in edit mode
2. Double click on some segment (sentence)
3. Double click or select some word 
4. Rightclick it and select "Copy" or press `Ctrl+C`

[Ekrānieraksts 2024-08-17 15-50-48.webm](https://github.com/user-attachments/assets/10e52c90-e483-4421-89b5-c3255971a312)

Also if you press `Ctrl+C` when some subtitle sentence is selected its text will be copied to the clipboard.

If these options are not enough we could implement some copy to clipboard feature. To know what exactly would be needed, please describe the desired workflow you would like to see in the Buzz or scenario how you would use this feature.

**Comment by raivisdejus** [comment]
Will close, please re-open if currently available copying options are not enough
