### ISSUE TITLE
Constant pop up folders as output/input files

### ISSUE THREAD

**Issue by Vamtian** [chidiwilliams/buzz#670]
When I open the Buzz, it will pop up out some of my folders while as output/input file format, it just constantly shows, while the Buzz doesn't work as transcribe at any model.
![65dc1cf159918902b24d5f2569d5fccf](https://github.com/chidiwilliams/buzz/assets/96088195/1a85b8d1-6c9f-4987-90b4-3e8e8ae67042)

**Comment by Sircam19** [comment]
I have exactly the same issue. Am on a Mac M1 - 16GB Sonoma 14.2

**Comment by chidiwilliams** [comment]
Thanks for the report. A second update was published yesterday to fix this issue. Thanks.
