### ISSUE TITLE
Major memory issues with sequential batched transcriptions (edit: memory leak issue?)

### ISSUE THREAD

**Issue by ndillmanhasso** [chidiwilliams/buzz#672]
Latest macOS App store update causes major memory issues when running multiple transcriptions. Got an error that too much memory was used on M2 Pro Macbook Pro (first time ever). Screenshot of activity monitor attached. I selected 20 video files to run SRT transcriptions on all of them; prior to this update I had no issues with batch transcriptions (not simultaneous but sequential).
![Screenshot 2024-01-20 at 4 00 50 PM](https://github.com/chidiwilliams/buzz/assets/40174188/08161a1d-b7fa-45fe-962e-4fa17fd795b9)

**Comment by ndillmanhasso** [comment]
Happens when batch transcribing with csv output as well and not using world-level timings. Here is more detailed info:

1) Video files stored locally on device but through cloud storage (OneDrive, but kept on device; tested when not in cloud storage and same issue happens)
2) Open buzz and click import, select "File..." and select all files in question (mp4 in this case)
3) Start transcription. I used the "Whisper.cpp - Large" model for all transcriptions as I have before with no issue. Language is English. Happened with word level timings on for SRT and off for CSV. Click "Run"
 - side note -- no way to click "cancel" on this screen without quitting Buzz that I've seen... You either have to click "Run" or force quit buzz through command + option + escape, command + q doesn't work either. I may be missing something though.
4) Transcriptions run normally at first with no hiccups. Files export to downloads as expected, but after each transcription, the total memory usage of Buzz doesn't go down but continues to rise. Memory pressure graphic in activity monitor shows consistent increase in memory usage for each sequential transcription. Not a problem with VM size as shown in the above screenshot, as plenty of apps have VM at or even above Buzz's VM.
5) After 9-12 transcriptions of hour long videos, MacOS dialogue pops up warning that too much memory is being used and to force quit some apps. Memory usage of Buzz is extraordinarily high, even though I only have 16GB of RAM. Force quitting all apps besides Buzz gives maybe 1-2 minutes of more time, but eventually, Buzz has to be force quit.
6) After force quitting Buzz, memory pressure immediately drops down to green levels from red levels in activity monitor. Reopening Buzz doesn't cause any issues automatically, but all queued transcriptions have to be manually right clicked and "cancelled" (they still show as queued even though they never transcribe).

Happy to provide any more logs/testing/info if you need, just let me know.

Activity monitor for first transcription:
![Screenshot 2024-01-21 at 10 09 22 AM](https://github.com/chidiwilliams/buzz/assets/40174188/68b5c9f9-8a6e-4a4d-baa0-6267ea4f864c)

Activity monitor for second transcription:
![Screenshot 2024-01-21 at 10 09 54 AM](https://github.com/chidiwilliams/buzz/assets/40174188/5ea6b580-b86b-40af-8614-c685445ea90d)

Activity monitor for third transcription:
![Screenshot 2024-01-21 at 10 16 58 AM](https://github.com/chidiwilliams/buzz/assets/40174188/ef80267f-b3fb-4139-96ce-ae19196c9939)

Memory pressure increase from first to second transcription:
![Screenshot 2024-01-21 at 10 10 26 AM](https://github.com/chidiwilliams/buzz/assets/40174188/ff502d3a-9f15-4aa7-af9d-844907d340e5)

**Comment by chidiwilliams** [comment]
Appreciate the detailed feedback. I'll take a look at this.

**Comment by chidiwilliams** [comment]
> side note -- no way to click "cancel" on this screen without quitting Buzz that I've seen... You either have to click "Run" or force quit buzz through command + option + escape, command + q doesn't work either. I may be missing something though.

Just the "Escape" button here should close the alert.

**Comment by ndillmanhasso** [comment]
> Just the "Escape" button here should close the dialog. I'll add a 'Cancel' button as well.

whelp, I feel dumb for missing that... thanks for the tip!

**Comment by chidiwilliams** [comment]
This should be fixed now in the latest update. Thanks!
