### ISSUE TITLE
the work stops as pure music on the track

### ISSUE THREAD

**Issue by MondiShen2024** [chidiwilliams/buzz#676]
Please Help Me! Thank You Very Much! 

When working in batches with the whisper medium model, the work will stop here when there is a piece of pure music without human voice in the middle（any where on the track） of the audio, and the sound of the following lines will not be translated into subtitles.

When I cut out the pure music, the whole track will be translated.

![1706757536549](https://github.com/chidiwilliams/buzz/assets/158411257/5bda4b06-bc45-4326-95fb-b5c071aae141)
![1706758233523](https://github.com/chidiwilliams/buzz/assets/158411257/0d84dc79-cb74-4dd2-ae37-818b915cdb9e)
![1706758832926](https://github.com/chidiwilliams/buzz/assets/158411257/23d93e3a-eac5-4b57-82f0-dd3bbb6f52cd)

**Comment by raivisdejus** [comment]
A few things to try:
- The latest version of the app https://github.com/chidiwilliams/buzz/releases
- Different Whisper type, like Faster whisper or Whisper.cpp. Faster whisper will be better on computer with CUDA GPU and Whisper.cpp will be faster on computer with no powerful GPU

Also if you can upload the audio somewhere I would be glad to look if we can fix this somehow. I did a test with some music in the middle of two speech segments and it worked fine, but I have also seen transcriptions where after a radio song in English models transcriptions jump to English from the original language.

**Comment by raivisdejus** [comment]
Closing as stale. Please re-open with example file that we can replicate this issue.
