### ISSUE TITLE
Buzz v0.8.4 always show "in Progress(0%)" and does not show actual progress at all

### ISSUE THREAD

**Issue by johnjch** [chidiwilliams/buzz#677]
Buzz v0.8.4 always show "in Progress(0%)" and does not show actual progress at all.

![Buzz in Progress (0%)](https://github.com/chidiwilliams/buzz/assets/43320866/520c3c66-e706-4e05-b798-6234f5eaca8a)

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
