### ISSUE TITLE
CLI produces blank filename. ".srt or vtt" v0.8.4

### ISSUE THREAD

**Issue by trobinson03195** [chidiwilliams/buzz#678]
C:\Users\Tim\Music\iTunes\iTunes Media\Podcasts\The Christian O_Connell Show>"C:\Program Files (x86)\Buzz\buzz.exe" add --task transcribe --srt --vtt "MINI_ Misheard Lyrics.mp3" "FULL_ Salami On.mp3"

![image](https://github.com/chidiwilliams/buzz/assets/43625735/ca097715-ff11-486e-8b28-28a250629c8c)

![image](https://github.com/chidiwilliams/buzz/assets/43625735/3a79a95c-da1c-4dfb-be9c-74d046255a03)

**Comment by Francefire** [comment]
Same here, blank .txt file for me 

this 
![image](https://github.com/chidiwilliams/buzz/assets/18541964/6ec3aaf2-b281-407f-9a68-e84070e7d143)


produced this : 
![image](https://github.com/chidiwilliams/buzz/assets/18541964/31d0287e-a8ed-44f3-a41f-371361775fc9)


**The content of the .txt is exactly as expected tho only the name is blank.**

**Comment by trobinson03195** [comment]
This occurs in version 0.8.4 since export filename field appeared. Tested 0.8.3 not an issue.

![image](https://github.com/chidiwilliams/buzz/assets/43625735/b8307bcd-211f-4748-8e4a-4a6749791c01)

**Comment by chidiwilliams** [comment]
Should be fixed now in [0.9.0](https://github.com/chidiwilliams/buzz/releases/tag/v0.9.0).

**Comment by Sircam19** [comment]
Hello Chidi. Will there be a mac (i.e. dmg) version or only in the apple mac store?
