### ISSUE TITLE
build project

### ISSUE THREAD

**Issue by DittmerOk** [chidiwilliams/buzz#683]
I downloaded the source code. How do I build the project to get the exe? and where will he lie down?

**Comment by Sridhar9095** [comment]
• Check if there is a build script or instructions in the project's documentation
• If there is no build script or instructions, check if there is a Makefile or a build configuration file
• If there is a Makefile or build configuration file, run the appropriate command to build the project
• If there is no build script, instructions, Makefile, or build configuration file, check if there is a build tool specified in the project's documentation
• If there is a build tool specified, install the build tool and follow its instructions to build the project
• If there is no build script, instructions, Makefile, build configuration file, or specified build tool, reach out to the project's maintainers or community for assistance

**Comment by raivisdejus** [comment]
For notes on running the Buzz locally see https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md
This will not produce the `.exe` as for that a setup process is needed that I am not familiar with on Windows. 

`.exe` for the current release you can find in the releases section https://github.com/chidiwilliams/buzz/releases

An option to get the `.exe` of your custom version is to do the build on GitHub. Fork the repo and add a manual run github action like this https://github.com/raivisdejus/buzz/blob/manual-build/.github/workflows/manual-build.yml Then trigger this action on your repo and once it is finished you will be able to download the `.exe` from the Assets section of the action (look at the very bottom of action summary page once it is finished)

**Comment by raivisdejus** [comment]
Did some changes. 

Now after commits to the repo GitHub actions will run the build and you can download the `.exe` from the artefacts section of the run. This should work also on a forked repo 

![attels](https://github.com/chidiwilliams/buzz/assets/5319134/befae20d-520a-4e45-806c-4184fddc56a9)
