### ISSUE TITLE
brew install --cask buzz installs Buzz-0.8.4 not Buzz-0.9.0

### ISSUE THREAD

**Issue by wasauce** [chidiwilliams/buzz#691]
Following the install instructions in the readme for a mac:

`brew install --cask buzz` leads to installing the old version:

==> Downloading https://github.com/chidiwilliams/buzz/releases/download/v0.8.4/Buzz-0.8.4-mac.dmg

**Comment by krehel** [comment]
Homebrew maintainer here. 👋 

Is a build of `buzz` 0.9.0 expected for macOS?

Thank you!

**Comment by Sircam19** [comment]
Not seeing it in the App Store as of yet 

![CleanShot 2024-03-17 at 09 19 18](https://github.com/chidiwilliams/buzz/assets/4651001/5eb0b6e9-8de9-4af1-9212-ef0e43ff891e)

**Comment by krehel** [comment]
Appreciated - Homebrew does not use the App Store though.

I suppose the better question is - will there be a `0.9.0` release for macOS on GitHub.

**Comment by chidiwilliams** [comment]
I temporarily removed the Homebrew build for Mac because there were issues with the code signing. I'll work on fixing it and updating the 0.9.0 release when I get some time soon.

**Comment by ccchan234** [comment]
> I temporarily removed the Homebrew build for Mac because there were issues with the code signing. I'll work on fixing it and updating the 0.9.0 release when I get some time soon.

why not sign the windows .exe too? signing it makes people feel more safe, thanks.
[https://github.com/chidiwilliams/buzz/issues/699](url)

**Comment by rdewolff** [comment]
Any link for the 0.9.0 for macOS meanwhile?

**Comment by raivisdejus** [comment]
1.0.1 is now uploaded to the brew. It will not run on Intel Macs. Latest version with all the most recent fixes is available in artifact section of the development builds https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
To download log into the github.

Also there is now a section in the documentation on how to run Buzz from source on macOS, might also be an option for some https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#mac
