### ISSUE TITLE
Portable Feature

### ISSUE THREAD

**Issue by kevinqingqinga** [chidiwilliams/buzz#692]
Is it possible to make it portable? Thanks in advance!

**Comment by raivisdejus** [comment]
@kevinqingqinga Buzz once installed is essentially a portable app. You can copy it to the USB stick and run on any other PC.

When run on another PC the settings you save in the Help -> Preferences will not be available on the new PC, but there are no too many things you may need changing.
Also take a look at the Advanced preferences that you can specify via environment values - https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences

So say you want to use models from the USB stick, you could create a `.bat` file that sets the `BUZZ_MODEL_ROOT` to the current directory where the bat file is run from and then would run the `Buzz.exe`  in a folder `Buzz` that you copied from the `C:\Program Files (x86)`

This is a possible content of `run_buzz.bat` as suggested by Github Copilot 
```
@echo off
set BUZZ_MODEL_ROOT=%~dp0
start "" "%BUZZ_MODEL_ROOT%Buzz\Buzz.exe"
```
