### ISSUE TITLE
No Italian translation available.

### ISSUE THREAD

**Issue by albanobattistella** [chidiwilliams/buzz#694]
Hi,

I installed the last version of buzz, but the italian translation is not available.
Could you please check it?
Also, it would be nice to make the transcription window bigger when you record because it's too small.
Thank you!
Best regards,
A.

**Comment by raivisdejus** [comment]
Translations are fixed by https://github.com/chidiwilliams/buzz/pull/741 main app screen will be made bigger by https://github.com/chidiwilliams/buzz/pull/744
