### ISSUE TITLE
[bug] i cant set the prompt in advanced option in the new 0.9.0. on win10 64bit, thx

### ISSUE THREAD

**Issue by ccchan234** [chidiwilliams/buzz#696]
hi,

i think in the last version i could still edit it.

but today i dnld-ed the new 0.9.0,
they are always non-editable.

thanks.

![image](https://github.com/chidiwilliams/buzz/assets/37549409/2156e062-3a2c-4356-8efa-684413e592a1)

ps, i use the whisper API key method, API key method is the only one that support initial prompt, correct? thx

**Comment by ccchan234** [comment]
ps, i used translate this time, let me see if is it only available in transcribe mode. thx

**Comment by chidiwilliams** [comment]
Initial prompt value is currently only enabled when selecting Whisper local models. Will add for Whisper.cpp and Whisper API in the next version.
