### ISSUE TITLE
potential security problem, virus found.

### ISSUE THREAD

**Issue by ccchan234** [chidiwilliams/buzz#699]
no joke, virus found!

![image](https://github.com/chidiwilliams/buzz/assets/37549409/071f8218-78c9-4c20-97fe-9493554dbfc1)

from the version 0.9.0, windows.

i did submit that to virustotal before i run,
but virustotal report nothing.

not sure if a new update in windows caught it.

**Comment by ccchan234** [comment]
ps: i sent the install.exe to virustotal, yet it's the buzz.exe that windows caught.

**Comment by ashepp** [comment]
I'm also seeing this and was about to report.

**Comment by ccchan234** [comment]
> I'm also seeing this and was about to report. Is this a real issue or a false positive?

i wish i can upload the buzz.exe to virustotal for better analysis.
however, my windows didn't allow me to touch the file anymore.

even i am on a chromebook, the installer is a .exe and i cant decompress it.

would be nice if someone could decompress the installer/install in sandboxie and send to virustotal for 50 scanners. thx

**Comment by chidiwilliams** [comment]
I believe this is a false positive from the installer not being code-signed. I'll leave this issue open for a few more days in case you find anything else, but I'll sign the 0.9.0 installer and give updates on #700.

**Comment by ccchan234** [comment]
hi, today i just extracted the buzz.exe and submitted to virustotal again (last time i submitted the install.exe),

it doesn't look good...
![image](https://github.com/chidiwilliams/buzz/assets/37549409/3e093851-b12a-404c-9968-268df9195ff7)

thank you.

however, one could use buzz inside vm/sandbox instead.

**Comment by ashepp** [comment]
This morning I had an ~$8K paypal transactions fraudulently charged to my account. I have no idea if it's related to the virus that was identified in the executable but I'm flagging so that this is investigated properly. It's unclear from this thread whether there's an issue or not.

**Comment by chidiwilliams** [comment]
Created at discussion at #702

**Comment by ccchan234** [comment]
> This morning I had an ~$8K paypal transactions fraudulently charged to my account. I have no idea if it's related to the virus that was identified in the executable but I'm flagging so that this is investigated properly. It's unclear from this thread whether there's an issue or not.

are you sure?

would be nice if i could get a screen shot /w the private info cropped out.

thanks

**Comment by chidiwilliams** [comment]
The 0.9.0 signed exe has been updated on the Releases page. Pls let me know if you see the Windows warning again. Will close this issue for now since there was no follow-up from @ashepp.
