### ISSUE TITLE
Where does the model get stored?

### ISSUE THREAD

**Issue by mcdmcdmcdmcd** [chidiwilliams/buzz#70]
Hi,

I downloaded the large model, but can't seem to locate where it is stored in my Mac.
Also, there should be a cancel button for the "Downloading Resources" dialog.

Cheers!

**Comment by chidiwilliams** [comment]
Hi, it should be in "$HOME/.cache/whisper/".

Looking into the cancel for the downloading resources dialog. Thanks!

**Comment by mcdmcdmcdmcd** [comment]
> Hi, it should be in "$HOME/.cache/whisper/".
> 
> Looking into the cancel for the downloading resources dialog. Thanks!

Not sure how should I go and locate `$HOME/.cache/whisper/`. However, I tried to find the `whisper` folder in ` ~/Library/Caches` but can't seem to find it either.

**Comment by chidiwilliams** [comment]
`~/.cache/whisper`
