### ISSUE TITLE
Fix Windows Code Signing

### ISSUE THREAD

**Issue by chidiwilliams** [chidiwilliams/buzz#700]
I'm creating this issue to give updates on the Windows code signing in response to https://github.com/chidiwilliams/buzz/issues/691#issuecomment-2006953189 and https://github.com/chidiwilliams/buzz/issues/699.

I wasn't previously code-signing the Windows binaries as the cheapest certificates I found were for around $200/year. I've found a more affordable OSS license from Certum, and I'm currently in the verification process. Will update this thread with more details and fix the 0.9.0 release once done.

**Comment by ccchan234** [comment]
hi,

1. if i install thru python, is it that this should be solved?

2. pls make a donation method? i am still a student but i am ok to donate USD 5. Let users share the money. thanks. (ps the method pls be international otherwise some cant pay)

**Comment by MardoDan** [comment]
Se encuentra disponible el .exe 0.9.0 instalador de Windows para la descarga???
