### ISSUE TITLE
buzz seems dont accept files from NAS, with UNC path. v0.9.0

### ISSUE THREAD

**Issue by ccchan234** [chidiwilliams/buzz#704]
hi,

i am still using v0.9.0 as it allow processing large files.

however i tested that when a file is with UNC path, drag and drog into buzz wont work.

but if you copy it into say w:/ then buzz can process it.

ps: i use some sort of sandbox so i dont know if it's my sandbox's setting problem.

thank you, and thank author for the program.

**Comment by L134139** [comment]
Where to download 0.9.0 Windows version

**Comment by COSTLAND** [comment]
having the same issue.

**Comment by raivisdejus** [comment]
> Where to download 0.9.0 Windows version
All downloadable files are attached to the relevant releases https://github.com/chidiwilliams/buzz/releases

**Comment by raivisdejus** [comment]
@ccchan234 @COSTLAND I tested this on Buzz version `1.0.1`, Windows 10, UNC paths from Synology NAS and it worked. My user had read and write permissions on the remote folder, file was transcribed and subtitles were saved in the remote folder.

Please try the latest version `1.0.1` and if it still fails, please check if you can get any useful information from the logs (see https://chidiwilliams.github.io/buzz/docs/faq for where to look for logs). If possible check the logs on your server maybe there is some useful information.

**Comment by raivisdejus** [comment]
Will close, feel free to re-open if more information on failing NAS setup is available
