### ISSUE TITLE
Buzz starts, I see `In progress (0%)`  (mp3 transcribe), and after several seconds closes silently without any info or any output file

### ISSUE THREAD

**Issue by jameskentTX** [chidiwilliams/buzz#715]
I have Debian 12.
I used Buzz 8 version without any problems. Version 9 doesn't work properly.
I have run command `sudo snap remove --purge buzz`, restarted pc, then installed buzz once again. Unfortunately it didn't help.

If I open Buzz again, I see status `canceled`.

I tried three different mp3 files.

![Screenshot from 2024-03-27 04-46-43](https://github.com/chidiwilliams/buzz/assets/17946652/e6dd4403-ddf9-470a-8078-73cf4d36ec57)

**Comment by raivisdejus** [comment]
Please start the Buzz from the command line, you will see some more output for the crash that may be helpful in solving it.

Also may try to delete the old caches in `~/.cache/Buzz`

**Comment by raivisdejus** [comment]
Please try the latest development version it has several improvements for Linux `sudo snap install buzz --channel latest/edge`

**Comment by jameskentTX** [comment]
@raivisdejus

Thanks, grate advice; Buzz is working again!

One remark for Buzz creators.
Buzz is working slowly. Tiny whisper is transcribing 5MB of mp3 (MPEG-1 Layer 3 (MP3), 44100Hz) for about one minute.
You need about 10 minutes to transcribe one hour mp3.
I can live with such Buzz speed, but there is probably space for improvement there.
Thanks for fixing Buzz for Linux!

**Comment by raivisdejus** [comment]
For running Buzz on regular computer / on CPU try Whisper.cpp it runs faster.

Other option to get faster speeds is to get more powerful hardware with Nvidia GPU.
