### ISSUE TITLE
Missing .exe Windows Binary for version 0.9.0

### ISSUE THREAD

**Issue by rtrampert** [chidiwilliams/buzz#718]
The windows download .exe file is missing for v0.9.0 on the releases page.

**Comment by wulong-tea** [comment]
same question. where is windows version?

**Comment by chidiwilliams** [comment]
I’m still waiting to get the signing certificate for the app. Once that’s available, I’ll sign the .exe and update the release.

**Comment by rtrampert** [comment]
Thanks for the update. I also need to know if this app will work with
Windows 7.

**Comment by rtrampert** [comment]
I'm also having issues with Buzz crashing in Ubuntu Linux 22.04.

**Comment by chidiwilliams** [comment]
@rtrampert, no the minimum Windows version supported is 10. Will look into the Linux issue.

**Comment by chidiwilliams** [comment]
The latest Windows exe has been updated on the releases page.
