### ISSUE TITLE
something's wrong when trying to transcribe

### ISSUE THREAD

**Issue by MrFutureV** [chidiwilliams/buzz#722]
as the pic showed
![QQ截图20240413042005](https://github.com/chidiwilliams/buzz/assets/46783891/1e0cd0d9-520f-4158-8164-afa2cac728ec)

**Comment by raivisdejus** [comment]
Please provide more information on the issue. What settings were used. For more information on troubleshooting see https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md

Also you could try testing the latest development version as the issue may have been fixed. Log into GitHub and download the latest development version from some successful action run. https://github.com/chidiwilliams/buzz/actions?query=branch%3Amain

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
