### ISSUE TITLE
crash in m1 macbook pro

### ISSUE THREAD

**Issue by DemonofMaxwells** [chidiwilliams/buzz#724]
when hit record ,crash began ,crash report attached in flie below.
[crash.txt](https://github.com/chidiwilliams/buzz/files/14986341/crash.txt)

**Comment by belugaming** [comment]
> when hit record ,crash began ,crash report attached in flie below.
> 
> [crash.txt](https://github.com/chidiwilliams/buzz/files/14986341/crash.txt)
> 
> 

 Same problem in Mac studio

**Comment by ddkwing** [comment]
Same problem in m2 macbook pro

**Comment by JasonChen86899** [comment]
Same problem in macbook pro

**Comment by raivisdejus** [comment]
For Apple silicon please try the latest version 1.1.0
For Intel get the version from latest development build (you need to log into the github to see the artifact download button) https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
