### ISSUE TITLE
0.9.0 Long audio to subtitle, with advertisements

### ISSUE THREAD

**Issue by XLiming** [chidiwilliams/buzz#726]
When converting audio files to subtitles, they may become advertisements after 16 minutes, prompting likes and follow. What should be done?

**Comment by chidiwilliams** [comment]
Yes, this is a hallucination from the Whisper model itself, not Buzz. You can learn more about it [here](https://github.com/openai/whisper/discussions/679) and [here](https://deepgram.com/learn/whisper-v3-results). You can try some things, like using a different model (larger/smaller), splitting the audio into smaller chunks, etc., but it's a known problem with these models.

**Comment by XLiming** [comment]
Thank you very much!
