### ISSUE TITLE
The sentence is too long 句子过长

### ISSUE THREAD

**Issue by Liu8Can** [chidiwilliams/buzz#727]
English:
I really like Buzz, a direct successor to Whisper, it has helped me a lot, and I am very grateful to the cool developer!
I used Buzz's transcribe function to identify that the subtitles are too long, the model I used is whisper-small, the language is English, and the generated subtitles are in srt format. How can this be solved, is it to adjust the parameters in advanced-temperature?
I would not be grateful if I could answer my busy schedule

Chinese：
我很喜欢buzz这款直接继承whisper的软件，它帮了我的大忙，很感谢帅气的开发者！
我是用buzz的transcribe功能识别出的字幕过长，我使用的model是whisper-small，language为English，生成的字幕格式为srt。这该如何解决呢，是调整advanced-temperature中的参数吗？
若能在百忙之中解答，我将不甚感激。

**Comment by Liu8Can** [comment]
![image](https://github.com/chidiwilliams/buzz/assets/102885173/670cd50f-b5ff-4ec1-b46f-36e1011c2202)
just like this, it's so long😂

**Comment by Barmaid1076** [comment]
any fixes?

**Comment by mynamepfd** [comment]
你可以用其他的软件，比如[Const-me / Whisper](https://github.com/Const-me/Whisper)，能利用GPU加速快速转录。输出长句子正是Buzz的特色。

**Comment by raivisdejus** [comment]
For this problem there is no easy fix. Length of the returned subtitles is something that lives in and comes out of the whisper itself. Buzz can't change it.

One possible solution is to generate subtitles with word level timestamps and then glue the words into sentences as you need.

Another solution is to use some other tool to process already generated subtitles. This tool seems to so something like this https://github.com/peterk/srt_equalizer

**Comment by Liu8Can** [comment]
您好！感谢您的邮件，我已经收到了您的来信。我会尽快阅读并回复您的邮件。请注意，这封邮件是自动回复，我目前无法立即回复您的邮件。感谢您的耐心等待！

**Comment by niubility000** [comment]
I think it's easy to do by yourself. First generate a word level srt. Then merge from the initial capital word to the Word end with“,”. This will be a whole sentence. And the timestamp will be very accurate.

**Comment by raivisdejus** [comment]
In next release `1.0.2` a new feature will be introduced that will let resize subtitles on the transcription edit screen. The same place where you can play the audio and see how it matches the subtitles and the same place you can edit some subtitles if that is necessary. Look for new "resize" button in the top bar.

You can also get this feature in latest development builds from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain (to download you need to log into the github, see artifact section)
