### ISSUE TITLE
Feature Request: Automatic Translation of Detected English Subtitles into Other Languages

### ISSUE THREAD

**Issue by belugaming** [chidiwilliams/buzz#728]
I am wondering if it’s possible to add a feature that automatically translates detected English subtitles into other languages in videos. This functionality would greatly enhance international accessibility, allowing non-English speakers to understand video content more easily. I look forward to your feedback.

**Comment by COSTLAND** [comment]
Currently, the default action when using the 'Translate' feature is to convert any transcribed language into English only.
- I don't think it's possible to add non-English language as the OpenAI's Whisper only support translation into English

**Comment by belugaming** [comment]
OK, thanks

COST ***@***.***>于2024年4月25日 周四19:15写道：

**Comment by moodler** [comment]
This is definitely a much-needed feature!    I hope we can find a solution sometime!   It's frustrating how US-centric OpenAI are ... :/

**Comment by moodler** [comment]
Surely, though, we can use another LLM call to translate the English into another language?

A common use case is a conference which is bi-lingual (say Spanish and English) and you want to have a local TV screen showing captions in both languages at once, all the time, regardless of which language is being spoken.

**Comment by raivisdejus** [comment]
Translation feature has been added to the latest main branch. See instructions on how to use translations here https://chidiwilliams.github.io/buzz/docs/usage/translations

This is very fresh feature, some hikups are possible. If you encounter them, please report. Feedback on if the overall usage is clear and intuitive to understand would be welcome.

**Comment by belugaming** [comment]
Please provide a tutorial for using macos, I have ollama

Raivis Dejus ***@***.***>于2024年6月15日 周六16:52写道：

**Comment by raivisdejus** [comment]
@belugaming Can't give you macOS specific instructions, but here are general instructions.

1. Start ollama on local, select appropriate model, I used `llama3:8b`, with default settings it will run on `http://localhost:11434`
2. Go to settings in Buzz and enter any key as OpenAI API key. It will not be used, but has to be filled, for example enter `ollama`
3. Enter your local ollama address as OpenAI address, Where the placeholder in settings says `https://api.openai.com/v1` enter `http://localhost:11434/v1`
4. Now open some transcribed file and click on the "Translate" button
5. In the settings dialog (the same window you see when you click "Advanced settings" when you specify transcription settngs) enable AI translations, enter model you have selected in ollama (for example `llama3:8b`) and enter translation promt.
6. When all the settings are filled and you click the translation button it will start translating and translations will appear in a new column besides the transcribed text.


A few notes:
* Translation results with local models were not too good. you can maybe get overall idea what the text is about, but translation quality was quite poor. For acceptable quality for Latvian translation I used ChatGPT. 
* To get the latest version with translation log into the GitHub and download it from some Action, f.e. from here https://github.com/chidiwilliams/buzz/actions/runs/9526889044

**Comment by belugaming** [comment]
thank you so much

Raivis Dejus ***@***.***>于2024年6月15日 周六23:28写道：

**Comment by belugaming** [comment]
thank you so much
