### ISSUE TITLE
Microphone errors - InputStream

### ISSUE THREAD

**Issue by shazwozza** [chidiwilliams/buzz#729]
Getting errors with selecting any of the Microphone options.
Running on a Windows 11 machine. Buzz 0.9.0

**Microphone: Microsoft Sound Mapper - Input**
An error occurred while starting a new recording:Error opening InputStream:
Unanticipated host error [PaErrorCode -9999]: 'Undefined external error.' [MME
error 1]. Please check your audio devices or check the application logs for more
information.

**Microphone: Microphone Array (Intel@ Smart**
An error occurred while starting a new recording:Error opening InputStream:
Unanticipated host error [PaErrorCode -9999]: 'Undefined external error.' [MME
error 1]. Please check your audio devices or check the application logs for more
information.

**Microphone: Primary Sound Capture Driver**
An error occurred while starting a new recording:Error opening InputStream:
Unanticipated host error [PaErrorCode -9999]: 'DirectSound error' [Windows
DirectSound error -2147467259]. Please check your audio devices or check the
application logs for more information.

**Microphone: PC Speaker (Realtek HD Audio output with SST)**
An error occurred while starting a new recording:Error opening InputStream:
Invalid device [PaErrorCode -9996]. Please check your audio devices or check the
application logs for more information.

**Microphone: Stereo Mix (Realtek HD Audio Stereo input)**
An error occurred while starting a new recording:Error opening InputStream:
Invalid device [PaErrorCode -9996]. Please check your audio devices or check the
application logs for more information.

**Microphone: Microphone (Realtek HD Audio Mic input)**
An error occurred while starting a new recording:Error opening InputStream:
Invalid device [PaErrorCode -9996]. Please check your audio devices or check the
application logs for more information.

**Microphone: Microphone Array 1 ()**
An error occurred while starting a new recording:Error opening InputStream:
Invalid device [PaErrorCode -9996]. Please check your audio devices or check the
application logs for more information.

**Comment by Jaykumaran** [comment]
An error occurred while starting a new recording:Error opening InputStream: Unanticipated host error [PaErrorCode -9999]: 'Input/output error' [ALSA error -5]. Please check your audio devices or check the application logs for more information


Facing same error on ubuntu 22.04, any fix?

Suggestions would be much appreciated

**Comment by raivisdejus** [comment]
Cause of issue on Ubuntu is known, we are working to fix it. To fix this for you, please connect necessary snap interfaces:
```
sudo snap connect buzz:audio-record
sudo snap connect buzz:password-manager-service
sudo snap connect buzz:pulseaudio
sudo snap connect buzz:removable-media
```

This will grant Buzz access to the microphone for sound recording, password manager service so it can store OpenAI API key and also removable media, so you can select files for transcription from removable media.


Issue with Windows is not clear yet. Does the microphones work in other apps?

**Comment by raivisdejus** [comment]
For Windows case, please, see if this is relevant https://support.microsoft.com/en-gb/topic/error-message-error-initializing-direct-sound-occurs-when-starting-directx-c892d63a-ac48-51c4-8c25-3653448703ed

IMO, googling for errors around `DirectSound error' [Windows DirectSound error -2147467259]` has the most potential to get to some solution, `PaErrors` seem relatively generic.

**Comment by raivisdejus** [comment]
If it is Windows, please see if Buzz has permission to use the microphone in Settings -> Privacy -> Microphone
See method 1 in this video https://www.youtube.com/watch?v=eRcCYgOuSYQ
For method 2 there is no need to uninstall the antivirus, but see if you can temporarily disable it or if there are settings to allow Buzz use the microphone or make it a trusted application.
