### ISSUE TITLE
(0.9.0)Failed to execute script 'main' due to unhandled exception: NOT NULL constraint failed: transcription.time_queued

### ISSUE THREAD

**Issue by nillwyc** [chidiwilliams/buzz#733]
when i launched it after installing this version but :

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 61, in main
  File "buzz\widgets\application.py", line 28, in __init__
  File "buzz\db\db.py", line 19, in setup_app_db
  File "buzz\db\db.py", line 30, in _setup_db
  File "buzz\db\helpers.py", line 16, in copy_transcriptions_from_json_to_sqlite
sqlite3.IntegrityError: NOT NULL constraint failed: transcription.time_queued

**Comment by raivisdejus** [comment]
A way to fix this issue might be to remove caches of previous Buzz version from your system (the `Buzz` folder). For folder locations see https://chidiwilliams.github.io/buzz/docs/faq

**Comment by Shawn-Chou** [comment]
I have encountered the same problem. And I uninstalled and reinstalled the program, and also I have tried to deleted thr Buzz folder. But the problem still happened.

**Comment by Shawn-Chou** [comment]
> A way to fix this issue might be to remove caches of previous Buzz version from your system (the `Buzz` folder). For folder locations see https://chidiwilliams.github.io/buzz/docs/faq

I have encountered the same problem. And I uninstalled and reinstalled the program, and also I have tried to deleted thr Buzz folder. But the problem still happened.

**Comment by raivisdejus** [comment]
Also can try the latest version https://github.com/chidiwilliams/buzz/releases
