### ISSUE TITLE
Translated as separate words

### ISSUE THREAD

**Issue by miaokaixii** [chidiwilliams/buzz#735]
![截屏2024-05-11 01 24 05](https://github.com/chidiwilliams/buzz/assets/169276317/2086dbb9-f4da-484a-962c-7c16ce1d835e)

BUZZ 0.8.4

**Comment by raivisdejus** [comment]
If you enable word level timestamps this is the expected behaviour. Uncheck the word level timestamps and you will get translations per sentences.
