### ISSUE TITLE
faster whisper large The model cannot be downloaded, and the download has been failing

### ISSUE THREAD

**Issue by wzgrx** [chidiwilliams/buzz#742]
The model cannot be downloaded, and the download has been failing
![Snipaste_2024-05-19_14-02-13](https://github.com/chidiwilliams/buzz/assets/39661556/9c839d1f-962e-4943-b2b5-b1b9365fda02)

**Comment by raivisdejus** [comment]
If you run the Buzz from the command line you will most likely see additional output. This output may help us identify and fix the problem.

Also do other models for faster-whisper download fine? And how about models for other Whisper variants?

**Comment by wzgrx** [comment]
> If you run the Buzz from the command line you will most likely see additional output. This output may help us identify and fix the problem.
> 
> Also do other models for faster-whisper download fine? And how about models for other Whisper variants?

others are all normally ，only large cant down

**Comment by raivisdejus** [comment]
In next release the downloading process will be improved. Please check the network activity of your system, it is possible model is downloading but the progress bar is stuck. It should download normally if you wait long enaugh
