### ISSUE TITLE
Space in every line in text

### ISSUE THREAD

**Issue by DeafNet** [chidiwilliams/buzz#746]
I was wonder when someone recognize on text note. There is every space on first word on the line. Like this: 
 Hi, 
 welcome to my channel
 Is there anything I can do ?
 This is why it is annoying 

I was wondering if there way to fix it ?

**Comment by raivisdejus** [comment]
@DeafNet  In the next version `1.0.2` there will no longer be extra spaces at the beginning or every transcript. 

Development version with this feature is available in latest development build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
To download app from the artifact section you need to log into the github

To get latest development version on Linux use `sudo snap install buzz --channel latest/edge`

Thanks for your report of the issue.

**Comment by DeafNet** [comment]
@raivisdejus  are this induced in 1.1.0 ? If so , I have not see change yet.
