### ISSUE TITLE
Disabling Word-level timings is not being remembered/saved

### ISSUE THREAD

**Issue by robsiera** [chidiwilliams/buzz#747]
I've noticed that when you disable "Word-level timings" in either the `File>Import File` or in `Preferences>Folder Watch`, that setting is applied, but it is not remembered the 'next time'. Especially for the Folder Watch that is a problem as that makes that feature unusable for me.
Maybe when loading the settings something goes wrong?

I'm using the Windows version.

**Comment by raivisdejus** [comment]
I have noticed this as well, will fix at some free moment

**Comment by robsiera** [comment]
Probably related: ones you "enable folder watch", the disable does not seems to work. So maybe some issue with interpreting the state of checkboxes in general?

**Comment by raivisdejus** [comment]
Issue fixed. Latest builds for Windows and Linux with this feature are in https://github.com/chidiwilliams/buzz/actions/runs/9329068715 Linux snap https://github.com/chidiwilliams/buzz/actions/runs/9329068717

**Comment by robsiera** [comment]
I just installed the last dev build. I can config, on Windows, the state of the 'Word-level timings' checkbox is remembered when transcribing an audio file. However, in `Preferences>Folder Watch` it is still not retained: disable it, save it, close preferences, open again and you will see it is enabled again.

**Comment by raivisdejus** [comment]
This should fix it, let us know if you find any other issues.
