### ISSUE TITLE
Windows Repair

### ISSUE THREAD

**Issue by TheusTimo** [chidiwilliams/buzz#759]
Hey There! I cannot install Buzz anymore it, it crashes during install process. Which are the folders name where bu installs itself? I installed v0.9 while 0.84 was still installed and it messed something up. Even after uninstalling both, it does not work anymore... Cannot install neither old nor new version... Thanks for you help!

**Comment by TheusTimo** [comment]
![Screenshot 2024-05-27 083957](https://github.com/chidiwilliams/buzz/assets/83712530/100a15d6-dc1e-4d83-a1df-1a4fceb8f2b5)

Also this error message when installing Buzz 0.9 and checking autolaunch. Buzz fails to install the buzz.exe

**Comment by raivisdejus** [comment]
To repair your installation of the Buzz, try:
1. Uninstall it
2. Delete the settings. 
- Open Registry editor (regedit.exe)
- Go to `HKEY_CURRENT_USER -> Software -> Buzz`
- Delete the `Buzz` registry folder. Be careful to not delete anything else as this may break other programs
![attels](https://github.com/chidiwilliams/buzz/assets/5319134/e14244a7-e521-4327-83b8-33ad6ec4db3f)
3. Reinstall Buzz


Still interested in the logs if you manage to get them and also let us know if this worked.

**Comment by TheusTimo** [comment]
Thank you so much for your answer and Solution :) I cleaned the registry and also went into the local appdata/roaming folder and deleted the folder there manually. Then i was able to install. The final fix was whitelisting the program in Avast Antivir because it kept deleting the .exe file. Now it works again!
All the best!

**Comment by raivisdejus** [comment]
Glad to hear. Next version will be able to delete registry during uninstal.
