### ISSUE TITLE
GitHub page content is not updating

### ISSUE THREAD

**Issue by raivisdejus** [chidiwilliams/buzz#776]
Added changes to documentation in [FAQ section](https://github.com/chidiwilliams/buzz/blob/main/docs/docs/faq.md), but changes do not appear on the GitHub page even after page action run. Changes are visible fine if docusaurus is compiled locally.

@chidiwilliams can you take a look at this at some free moment, please.

**Comment by chidiwilliams** [comment]
Sure, fixed now
