### ISSUE TITLE
Brew shows Buzz as deprecated and has 0.8.4 as latest version

### ISSUE THREAD

**Issue by fad1** [chidiwilliams/buzz#794]
Please check https://formulae.brew.sh/cask/buzz#default

**Comment by raivisdejus** [comment]
1.0.1 is now uploaded to the brew. It will not run on Intel Macs. Latest version with all the most recent fixes is available in artifact section of the development builds https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
To download log into the github.

Also there is now a section in the documentation on how to run Buzz from source on macOS, might also be an option for some https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#mac
