### ISSUE TITLE
Buzz will create multiple duplicate tasks when multiple files are placed in the watch path at the same time

### ISSUE THREAD

**Issue by Zeebo007** [chidiwilliams/buzz#796]
In Windows operating system (and possibly other operating systems), there is a known issue where placing multiple files in the configured watch path at the same time or adding new files to the watch path while a previous task is incomplete will result in duplicating tasks for the earlier files. 
This problem may occur because each file placement triggers the file copy system event repeatedly, leading to duplicate event processing, while the program does not check if the file has already been assigned a conversion task.

Hope this issue can be fixed, thanks!

**Comment by raivisdejus** [comment]
Issue fixed.
You can get fixed version by downloading latest development version from some latest Action run https://github.com/chidiwilliams/buzz/actions?query=branch%3Amain (you need to log in to the Github to see the artifacts section) or wait for the release `1.0.2`

Thanks for reporting.

**Comment by Zeebo007** [comment]
Thank you for taking the time to fix the issue. I have downloaded the code and tested it successfully.
