### ISSUE TITLE
Failed error 403 trying using whisper OPEN AI API?

### ISSUE THREAD

**Issue by ZerefCG** [chidiwilliams/buzz#797]
Nice app guys i love it, but trying change the model to OPEN AI gives me this error
![asd](https://github.com/chidiwilliams/buzz/assets/97218603/e96a24bc-8aaf-406b-9473-ff610662c1fc)

¿I'm doing something wrong? i create a new token in open ai project section and copy/paste it

i don't know so much programming things, very newbie here, but i read the docs of buzz and follow step by step

EDIT: nvm i'm fool, i think OPENAI blocks IP'S from my country LOL sadly
![image](https://github.com/chidiwilliams/buzz/assets/97218603/15dd0a2e-5bbb-4826-9d89-41a7c385bc68)

**Comment by raivisdejus** [comment]
Will look into this.
Did you have language selected or was it at "Detect automatically"?

**Comment by raivisdejus** [comment]
Hope Open AI API will soon be available everywhere
