### ISSUE TITLE
Customizable api_base for OpenAI: URL is not used

### ISSUE THREAD

**Issue by faspie** [chidiwilliams/buzz#800]
Thank you for adding customizable API support to buzz!

I tested the new version yesterday. The new URL does not seem to be used for
- open AI key testing and
- in the "record" mask - data is not sent to my internal whisper server

**Comment by raivisdejus** [comment]
Please provide more info of your local setup. Internally we use python OpenAI python API. Is your internal whisper compatible with it?

**Comment by faspie** [comment]
My local setup is tiny openai whisper api (https://github.com/morioka/tiny-openai-whisper-api) which should be compatible with the official openai api.

The main problem is that the parameters provided by "preferences" are not used by the record mask.

The "check key" button in preferences leads still to a connection to the openai server

**Comment by raivisdejus** [comment]
Ignore the "check key" for now, that part indeed has an issue, but I think the actual recognition should work. 

Or wait a few days, I'll look into the check key part as well

**Comment by raivisdejus** [comment]
Use of custom base url has been added to API key check as well. If the custom API used does not support it API key check will give an error, but should still work.

Please test and let us know if it works as expected.

**Comment by faspie** [comment]
Unfortunately, here is no option for using the api.
If Model "Whisper" is selected, buzz is downloading language models locally so I guess it does not use the api
![Bildschirmfoto vom 2024-06-18 22-06-54](https://github.com/chidiwilliams/buzz/assets/151960839/0da318a1-1bcf-45f1-ab8c-c58a2465de45)

**Comment by raivisdejus** [comment]
Whisper API is not supported for Live recordings, "OpenAI Whisper API" option will be available for file recording transcriptions.  Will look into making API work for Live recordings

**Comment by faspie** [comment]
OK, is there any reason why live recording is not supported? It should not make any difference whether a local whisper or an API is transcribing...

**Comment by raivisdejus** [comment]
Support for Open AI API has been added to live recordings. Let me know if you spot any issues.
