### ISSUE TITLE
Recording does not work at all

### ISSUE THREAD

**Issue by TanjaZ84** [chidiwilliams/buzz#819]
I updated to version 0.9.0. Since then clicking on the microphone or pressing buttons CTRL+R does nothing. I tried a reinstall - no change. I deinstalled and deleted every remaining file, downloade the exe again and installed fresh - no change.
What can I do? Or can you post somewhere the older version since that worked on my PC? Thanks!

**Comment by raivisdejus** [comment]
You can try latest development version from Actions section. You have to be logged in the GitHub. See https://github.com/chidiwilliams/buzz/actions/runs/9718013525

Previous version is available here https://github.com/chidiwilliams/buzz/releases/tag/v0.8.4

**Comment by raivisdejus** [comment]
We have version 1.0.0 released now - https://github.com/chidiwilliams/buzz/releases

Please make sure that you see some sound in the sound activity bar near the record button. Maybe you need to select different input device.

![attels](https://github.com/chidiwilliams/buzz/assets/5319134/6afd53ac-db11-421f-ba25-302a6f0a05b0)

**Comment by raivisdejus** [comment]
Closing as stale. Please re-open if issue is still present and more information is available
