### ISSUE TITLE
Problem for PyPI version

### ISSUE THREAD

**Issue by jelly-ma** [chidiwilliams/buzz#823]
I'm using PyPI version on my MAC, python version is 3.10.11,  and something error occurs:
ModuleNotFoundError: No module named 'buzz.whisper_cpp'
as the picture shows:
<img width="1426" alt="截屏2024-07-06 11 32 30" src="https://github.com/chidiwilliams/buzz/assets/59598944/d29f4a90-33d9-4ffc-a9ac-8f203d64aa5b">

Is there something wrong with it? thanks!

**Comment by JasonChen86899** [comment]
the same to me. Then I hit record, the app crash

**Comment by Joeking-around** [comment]
same here, and i tried building  it on windows and install the whl file , turns out the same. i am guessing is it because of something wrong happened while building the buzz-captions with whisper_cpp?

**Comment by raivisdejus** [comment]
Workaround for short term could be to download the app from https://github.com/chidiwilliams/buzz/releases for macOS or Windows and snap from https://snapcraft.io/buzz for Linux

Will try to sort this out.

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索

**Comment by raivisdejus** [comment]
Also I assume you are using latest `1.0.0` version, so another workaround may be to install previous version `pip install buzz-captions==0.9.0`

**Comment by Joeking-around** [comment]
> Also I assume you are using latest `1.0.0` version, so another workaround may be to install previous version `pip install buzz-captions==0.9.0`

yeah but my initial need is to run this on windows with gpu-cuda acceleration. And based on the document i find the only way 
 i can doing this is to install pypi 1.0.0 version cause i can't modify .exe realease. is it right or is there any way to achieve my goal?

**Comment by raivisdejus** [comment]
@Joeking-around We have a good chance to test GPU acceleration on Windows. Huggingface Whisper, Faster Whisper and the regular Whisper all have code to use CUDA GPU if it is available, but I have not tested it on Windows.  Please test and report your results. If test is successful, I'll update the documentation.

**Comment by Joeking-around** [comment]
sure , i am testing faster whisper with cuda gpu on windows these days . And once you fixed the pypi 1.0.0 ModuleNotFoundError just let me know, i will test it on my windows computer as well.

**Comment by Joeking-around** [comment]
> @Joeking-around We have a good chance to test GPU acceleration on Windows. Huggingface Whisper, Faster Whisper and the regular Whisper all have code to use CUDA GPU if it is available, but I have not tested it on Windows. Please test and report your results. If test is successful, I'll update the documentation.

sure , i am testing faster whisper with cuda gpu on windows these days . And once you fixed the pypi 1.0.0 ModuleNotFoundError just let me know, i will test it on my windows computer as well.

**Comment by raivisdejus** [comment]
@Joeking-around Working wheel file is available for testing https://github.com/chidiwilliams/buzz/actions/runs/9886248824

Please log into github and see it in the "Buzz-Windows.zip" in the artifacts section.

**Comment by Joeking-around** [comment]
> @Joeking-around Working wheel file is available for testing https://github.com/chidiwilliams/buzz/actions/runs/9886248824
> 
> Please log into github and see it in the "Buzz-Windows.zip" in the artifacts section.

i got a error message 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\anaconda3\envs\buzz\Lib\site-packages\buzz\__main__.py", line 4, in <module>
    buzz.buzz.main()
  File "D:\anaconda3\envs\buzz\Lib\site-packages\buzz\buzz.py", line 57, in main
    from buzz.cli import parse_command_line
  File "D:\anaconda3\envs\buzz\Lib\site-packages\buzz\cli.py", line 5, in <module>
    from PyQt6.QtCore import QCommandLineParser, QCommandLineOption
ModuleNotFoundError: No module named 'PyQt6.sip'

but i am sure that i have pyqt6 

(buzz) C:\Users\Administrator>pip install pyqt6.sip
Requirement already satisfied: pyqt6.sip in d:\anaconda3\envs\buzz\lib\site-packages (13.6.0)

i don't know if i installed it correctly but i got message that i successfully installed the .whl file 

Successfully built stable-ts
Installing collected packages: polib, platformdirs, ctranslate2, av, yt-dlp, keyring, huggingface-hub, dataclasses-json, tokenizers, transformers, stable-ts, faster-whisper, buzz-captions

**Comment by raivisdejus** [comment]
@Joeking-around @jelly-ma @JasonChen86899 Please try the latest development wheel version from https://github.com/chidiwilliams/buzz/actions/runs/10167390711 (you need to log into the github to see the artifacts section)

Windows .exe version should include `pyqt6.sip` dependency

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索

**Comment by raivisdejus** [comment]
Hopefully this is fixed now with `1.1.0`. Please re-open if some issues still remain

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索
