### ISSUE TITLE
Misspelling of the word "Transcribe"

### ISSUE THREAD

**Issue by thejonnyjon** [chidiwilliams/buzz#830]
"Transcribe" is misspelled as "tanscribe" in version 1.0.0.

![image](https://github.com/chidiwilliams/buzz/assets/96361520/2d712080-9ea2-4f47-9edb-de25f3640b50)

![image](https://github.com/chidiwilliams/buzz/assets/96361520/afcf61b8-8617-4baa-ba6f-c0a405a5f070)

**Comment by raivisdejus** [comment]
Thanks for reporting this. Fixed.
