### ISSUE TITLE
Translation not available

### ISSUE THREAD

**Issue by albanobattistella** [chidiwilliams/buzz#836]
Hi,
Italian translation is not available for a GUI.
Any idea?
Thanks,
A.

**Comment by raivisdejus** [comment]
@albanobattistella Issue with Linux snap translations is fixed. Is your translation missing in some other platform?

**Comment by albanobattistella** [comment]
> @albanobattistella Issue with Linux snap translations is fixed. Is your translation missing in some other platform?

HI,
I installed snap package and I have not translation.

**Comment by raivisdejus** [comment]
Yes that was a mistake that is now fixed.

You can get snap version with translations fixed by running `sudo snap install buzz --channel latest/edge`

**Comment by raivisdejus** [comment]
Fix for snap locales will be available on the edge channel in next few days.
