### ISSUE TITLE
Simplified Chinese (zh-CN) instead of Traditional Chinese (zh-TW).

### ISSUE THREAD

**Issue by kekeyo1314** [chidiwilliams/buzz#845]
I need the output to be in Simplified Chinese (zh-CN) instead of Traditional Chinese (zh-TW).

**Comment by raivisdejus** [comment]
Whisper built in models that are used in Buzz do not offer ability to distinguish different Chinese variants. 

You can try to use some whisper variant from Huggingface https://huggingface.co/models?sort=trending&search=whisper+zh-cn

Select "Huggingface" whisper type and enter model identificator. If you find some model that works well, please tell us what model is good here, that may be useful for others
