### ISSUE TITLE
Falla al iniciar Buzz

### ISSUE THREAD

**Issue by Jack-479** [chidiwilliams/buzz#853]
tengo la versión PRO, la utilizo en un Mac Air M1, al transcribir archivos MP4 transcribe es lento incluso utilizando modelos pequeños, desde hace un par de dias marca un error al tratar de cargar algun archivo

audios de 40 minutos tarda de 3 a 4 hora utilizando incluso modelos rápidos y pequeños

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases
