### ISSUE TITLE
Model loading through USB

### ISSUE THREAD

**Issue by adijahangir123** [chidiwilliams/buzz#854]
I have a PC which we use for video editing etc and completely offline, no internet at all. Installed buzz through USB. Is there any way to download models separately and load in buzz

**Comment by raivisdejus** [comment]
Go Help -> Settings then select Models tab
Download models you want and once they will be downloaded select "Show file location".  This will show model location in the cache folder 

Copy the folder `C:\Users\YourUserName\AppData\Local\Buzz\Buzz\Cache\models` to the other PC and it should work
