### ISSUE TITLE
wispher.cpp with large-v3 model only use CPU，do not use GPU

### ISSUE THREAD

**Issue by Aridea2021** [chidiwilliams/buzz#855]
Dear developer, 
    Many thanks for offering such a useful software, I try it from my friends sharing. now it seems that it can work with only CPU when I choose whishper.cpp large-v3 model. But I'd like to know how to use the GPU to accelerate the transcribe progress.  

best regards.

from Dong

**Comment by raivisdejus** [comment]
If you have a GPU with enough VRAM there is little speed difference among Whisper.cpp and Faster Whisper. 
So the easiest way to get faster transcription with GPU is to use some other Whisper type.

**Comment by Aridea2021** [comment]
> If you have a GPU with enough VRAM there is little speed difference among Whisper.cpp and Faster Whisper. So the easiest way to get faster transcription with GPU is to use some other Whisper type.

Hi raivisdejus, thank you for the kindness help, but I did not get you. I do have a modified 2080ti with 22g VRAM. It can work well in  WhisperDesktop.exe with Whisper.cpp large v3 model. Can you tell me which whisper type should  I choose so that I can use GPU to  boost the progress. Thanks again~
![PixPin_2024-07-24_01-14-36](https://github.com/user-attachments/assets/ccb6256e-600e-45e7-bed7-9338491ec944)

**Comment by raivisdejus** [comment]
Use Faster Whisper.

But you also need CUDA installed https://developer.nvidia.com/cuda-downloads

**Comment by Aridea2021** [comment]
> Use Faster Whisper.
> 
> But you also need CUDA installed https://developer.nvidia.com/cuda-downloads

so nice, thank you, raivisdejus
