### ISSUE TITLE
Failed to execute script 'main'

### ISSUE THREAD

**Issue by nemrod171** [chidiwilliams/buzz#856]
I used to use Buzz 0.8.4 on Windows 11.
it worked perfectly.
Today I update ti 1.0.1 but it doesn't run correctly.
Image with the error in the post
![buzz_2024-07-24_11h59_19](https://github.com/user-attachments/assets/3223357f-59df-4a2c-9d88-2004fd3c0c24)

**Comment by raivisdejus** [comment]
There is some issue in importing the list of old transcription results into the new version. 
You can try to delete the old transcription database. To do it:
1. Go to `C:\Users\YourUserName\AppData\Local\Buzz\Buzz`
2. Delete `Buzz.sqlite` gile and any files that end with `.json`. You can also delete the whole folder.

Also if settings are not imported correctly, try uninstalling the Buzz  first. The last step of uninstaller will ask it you want tot delete the settings, select Yes. Then install Buzz again.

Please let us know if this helped.

**Comment by raivisdejus** [comment]
Will close. Please re-open if additional assistance is needed.
