### ISSUE TITLE
An error occurred while loading your audio devices.

### ISSUE THREAD

**Issue by jiangbianqi** [chidiwilliams/buzz#883]
![Snipaste_2024-08-15_14-35-28](https://github.com/user-attachments/assets/eb3c523e-17e0-4572-8b8f-1ad78a72c1e0)
这个问题一直存在，重装后依旧。求解决问题的办法。
This issue has persisted even after reinstalling. Seeking a solution to resolve it.

![image](https://github.com/user-attachments/assets/363f1d60-f463-4c6f-869e-52981ec1ced9)

**Comment by raivisdejus** [comment]
Please see the https://chidiwilliams.github.io/buzz/docs/faq

Item 1. in the doc will give information on where to find the log file, there may be some useful information

Item 6. is a solution to one similar problem with audio devices, it may help you as well.

**Comment by raivisdejus** [comment]
This can also happen if some other application is using the microphone. Most likely cause some configuration on the system.

Will close for now, feel free to re-open if more info is available
