### ISSUE TITLE
Transcript with Person names

### ISSUE THREAD

**Issue by adijahangir123** [chidiwilliams/buzz#887]
Is it possible to somehow add functionality which enables user to identify person speaking without listening to original audio. Even if it labels them as person A and person B etc

**Comment by raivisdejus** [comment]
Theoretically it is possible. Technically the feature is called `Speaker Diarization` and there are solutions that do this. Some future version may get this feature. Will close this issue as this feature already has been requested in https://github.com/chidiwilliams/buzz/issues/492
