### ISSUE TITLE
how to add word-level timing option in cli command?

### ISSUE THREAD

**Issue by youbl** [chidiwilliams/buzz#898]
I searched the doc: https://chidiwilliams.github.io/buzz/docs/cli
and can't found the option about word-level timing

**Comment by raivisdejus** [comment]
@youbl the `-wt` or `--word-timestamps` options are now available for running Buzz from CLI to request word level timestamps. See them in the latest development build https://github.com/chidiwilliams/buzz/actions/runs/11083916137
To download you will need to log into the github
