### ISSUE TITLE
Interface Translation Issue

### ISSUE THREAD

**Issue by jfbloom22** [chidiwilliams/buzz#902]
The application works great, but it is difficult to navigate because the interface is translated into various languages all at the same time.  

Running on a MacBook Pro M3 and Sonoma 14.6.1

Any idea what is going on here?

I am expecting it all to be in English.  

A friend of mine has an M1 MacBook Pro running Sonoma 14.6.1 and they are not having any issues.  

Running version 1.1.0 of Buzz downloaded from Github.  

![PNG image 3](https://github.com/user-attachments/assets/8e67a51f-54fc-4d1b-8d3c-3b039ce68d88)

![PNG image 2](https://github.com/user-attachments/assets/5671a85f-6a2b-4839-9b65-68e52e1c51ba)

**Comment by raivisdejus** [comment]
@jfbloom22 Strange that it can happen like this. Let's see if we can figure out what is going on there.

Question 1 / Test 1 - To check if installation files from the latest build also have this problem https://github.com/chidiwilliams/buzz/actions/runs/10864725745 You need to log into the GitHub to see the download button

Question 2 - Does the brew version behave the same? `brew install --cask buzz`

Question 3 - Was some version of Buzz installed on the computer before? Meaning did you upgrade it? If so can try removing the old version and then install it again.

**Comment by jfbloom22** [comment]
Thanks @raivisdejus for helping me with this.  1.0.1 was installed before updating to 1.1.0.  1.0.1 had a similar issue.  

Before I try re-installing, what is the best way to completely uninstall?

**Comment by raivisdejus** [comment]
@jfbloom22 Open This forlder `~/Library/Logs/Buzz` and see the `logs.txt`
The very first line should be something like this
```
locale.<module>:12 DEBUG -> UI locales ['lv-LV', 'lv-Latn-LV', 'lv']
```

Curious what languages are defined on your system. 

I found an inconsistency that might have caused the issue you see. Please try the latest development version from https://github.com/chidiwilliams/buzz/actions/runs/11068243968 to see if it fixed the issue.
You need to log into the Github to download the files

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases

If the issue remains, please re-open the issue
