### ISSUE TITLE
Error when pressing Record

### ISSUE THREAD

**Issue by danka621** [chidiwilliams/buzz#903]
On Windows 10, selecting Live Recording with default settings and working microphone input bars, pressing Record, generates an error dialog box titled Buzz with content "An error occurred while loading the Whisper model: A connection error occurred. Please retry or check the application logs for more information."

I can't find any application logs for more information.
The PC is stand-alone w/o internet access.

**Comment by raivisdejus** [comment]
To work Buzz needs to download model files. You need to download them on some PC with internet and then move to the PC without the internet.

See Help -> Preferences -> Models to download and find where the model files should be placed.

Advanced preference for model folder may also be useful to you https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences
