### ISSUE TITLE
Favorite languages

### ISSUE THREAD

**Issue by brmassa** [chidiwilliams/buzz#908]
For those using it with different languages, it's kinda a pain to scroll all the way to find the needed language. It would be nice to have in the settings to checkbox the "favorite" languages so it appears at the top of the dropdown list.

Example:

Imagine one uses Buzz to transcribe/translate mainly from Spanish. marking English and Spanish in the settings the dropdown list would be like:

```txt
English
Spanish
-----------------------
Afrikaans
Albanian
...
```

Either move the fav at the top or duplicate them.

**Comment by raivisdejus** [comment]
@brmassa I would like to keep the settings UI simple for new users, to avoid big screens of settings that only a few users use and that may confuse other users.

But to give extra flexibility for more advanced users that want extra features, currently I am experimenting with advanced settings https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences

Please tell me if adding favorite languages to the list of available advanced options would suit you?
This approach relies on users setting different custom options in the environmental settings in their operating system. A bit un-common, but very flexible way to set custom advanced options

**Comment by brmassa** [comment]
@raivisdejus , it think it would be enough. It's generally a one-time setting anyway. The full list is just too bad UX, so this might help

**Comment by raivisdejus** [comment]
@brmassa Environment variable `BUZZ_FAVORITE_LANGUAGES` has been added to pass coma separated list of favorite language codes, f.e. `en,es` 

Available in latest development version https://github.com/chidiwilliams/buzz/actions/runs/11090309881
To see the download button you need to log into the github

Thanks for the feature suggestion!
