### ISSUE TITLE
Faster Whisper does not use GPU

### ISSUE THREAD

**Issue by xpk20040228** [chidiwilliams/buzz#910]
using a 4060 8G with CUDA 12.6.65, on windows installed with pip
pytorch version is "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124"
it says in powershell log "[warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead."
and there's no load on my 4060.
Weirdly normal Whisper in all different model sizes can use the GPU and does not show the above warning line.

**Comment by raivisdejus** [comment]
@xpk20040228 See if a bit older version or `torch` works 
```
pip3 unstall torch torchaudio  
pip3 install torch==2.2.1+cu121 torchaudio==2.2.1+cu121 --index-url https://download.pytorch.org/whl/cu121
```

Assuming that you have `torch 2.2.4` installed now

**Comment by raivisdejus** [comment]
@xpk20040228 Seems current versions of Faster whisper can't use GPU on Windows as https://developer.nvidia.com/cublas is not available for Windows for CUDA 12 at this time. 

The somewhat good part of this is that with GPU there is not a big difference in speed among Faster whisper and regular Whisper or Huggingface (transformer) whisper.

Thanks for pointing this issue out. Sad that there is nothing much we can do at this time besides waiting for Nvidia to release cuBLAS for Windows.

**Comment by raivisdejus** [comment]
For regular Whisper and Huggingface version on Windows you can try the latest development version that has GPU support for Windows included.

Log into github 
Get latest development version https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

No solution for Faster whisper at the moment

**Comment by somacruz10** [comment]
> For regular Whisper and Huggingface version on Windows you can try the latest development version that has GPU support for Windows included.
> 
> Log into github Get latest development version https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
> 
> No solution for Faster whisper at the moment

Am I right that this is not works for windows right now? Because if I use just python script to launch Faster Whisper it will user GPU.

**Comment by raivisdejus** [comment]
@somacruz10  What version of faster whisper are you using in the python script?

Older versions do work on Windows, but the latest that we use in Buzz does not work.

**Comment by somacruz10** [comment]
> @somacruz10 What version of faster whisper are you using in the python script?
> 
> Older versions do work on Windows, but the latest that we use in Buzz does not work.

pip show faster-whisper:
Version: 1.0.1
Summary: Faster Whisper transcription with CTranslate2

I am new to this stuff, I dunno how I got faster-whisper actually for python, thought I got it with buzz (if it works this way.) But I would like to setup Buzz to work with GPU. Normal Whisper working with it. Is there a way to get older version for Buzz?

**Comment by raivisdejus** [comment]
@somacruz10 All releases of buzz are in the releases section https://github.com/chidiwilliams/buzz/releases
`v.0.9.0` https://github.com/chidiwilliams/buzz/releases/tag/v0.9.0 is using the older version of Faster whisper, but since this version there have been many changes and bug fixes, I think I remember there being some issues with GPU on windows in this version.

If you are experimenting, maybe Linux is an option? Setup is quite simple and I am happy to help if you get some questions. Faster whisper works fine on Linux and uses GPU. 

Also the Huggingface Whisper uses GPU on Windows. In my tests it is almost as fast as Faster whisper. To get the same models that are used in regular Whisper search for "Openai" in the Huggingface model box.

Main advantage of Faster whisper is that it uses less VRAM. If that is not an issue IMO Huggingface will get you almost similar speeds. In test on Linux for 15 min audio Faster whisper did it in 59 seconds, Huggingface in 61 seconds, with the same size model.

**Comment by raivisdejus** [comment]
@somacruz10 Please see this https://github.com/chidiwilliams/buzz/issues/925

Looks like the Whisper Turbo models run even faster than Faster Whisper as well as use less VRAM. Buzz supports them via Huggingface whisper type.

**Comment by bash99** [comment]
> > @somacruz10 What version of faster whisper are you using in the python script?
> > Older versions do work on Windows, but the latest that we use in Buzz does not work.
> 
> pip show faster-whisper: Version: 1.0.1 Summary: Faster Whisper transcription with CTranslate2
> 
> I am new to this stuff, I dunno how I got faster-whisper actually for python, thought I got it with Buzz (if it works this way.) But I would like to setup Faster Wishper for Buzz to work with GPU. Normal Whisper working with it. Is there a way to get older version for Buzz?

I'm also on the same boat, faster-whipser works from python script, not Buzz 1.2.0

```
(faster_whisper) D:\cmds\codes>pip show faster-whisper
Name: faster-whisper
Version: 1.1.0
Summary: Faster Whisper transcription with CTranslate2
Home-page: https://github.com/SYSTRAN/faster-whisper
Author: Guillaume Klein
Author-email:
License: MIT
Location: D:\cmds\miniforge3\envs\faster_whisper\Lib\site-packages
Requires: av, ctranslate2, huggingface-hub, onnxruntime, tokenizers, tqdm
Required-by:

(faster_whisper) D:\cmds\codes>pip show ctranslate2
Name: ctranslate2
Version: 4.4.0
Summary: Fast inference engine for Transformer models
Home-page: https://opennmt.net
Author: OpenNMT
Author-email:
License: MIT
Location: D:\cmds\miniforge3\envs\faster_whisper\Lib\site-packages
Requires: numpy, pyyaml, setuptools
Required-by: faster-whisper
```

**Comment by raivisdejus** [comment]
@bash99 Please see the latest development version. It should support Turbo models for Faster Whisper and GPU on Windows. https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version
