### ISSUE TITLE
Problem with brew install on M1 Macbook Pro

### ISSUE THREAD

**Issue by jarlcohan** [chidiwilliams/buzz#921]
Hello!

I have purchased the app from app store but prefer the brew install version 1.1.0, since it has more settings and access to models. But I can't get it to live transcribe. It listens to the microphone, and it transcribes files but live transcription isn't working. 

I also have one more request and that is if you could consider to add a "sort" function so that the newest line in a live transcription is always on top. That way you could have it running on a screen somewhere without any operating needed. I want to use it for accessibility purposes for hearing impaired persons in an workshop. And an even larger display mode with that in mind would be so revolutionary and very popular in the community!

Kind regards,
Carl Johan

**Comment by raivisdejus** [comment]
@jarlcohan Will see what we can do about the "sort" function, this could be very useful.

Regarding live transcript, what Whisper type do you use and what model size? It is possible that transcription can't keep up with the speech, but I assume it was working previously, so will need to investigate this. To give more information about the issue, can you please try Whisper.cpp with tiny model size. Quality will be poor, but with this test we want to check if the issue is with transcription speed.

**Comment by raivisdejus** [comment]
@jarlcohan in the latest development version I have added an option to select sorting of the direction live transcripts add new sentences. The setting is in the Help->Preferences (the General preferences) It also has an option to select the new live transcription mode that will try to correct the errors in previous transcripts.

To get the latest development version you can:
- Log into the Github
- Get the installation file from latest development build here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

**Comment by jarlcohan** [comment]
Thank you so much! I still can't get it to work on my own M1 computer but it worked fine when I tried on a different M2 mac mini. It's amazing that you implemented the sorting function so quickly and I think it will be a great asset for us! It would be useful with even larger fonts and only for the text not the UI so that we can display it large on a screen. But this can we solve in other ways to so I'm just mentioning it in case you think it's valuable input.

**Comment by raivisdejus** [comment]
@jarlcohan You can change font size in the Preferences. 
![attels](https://github.com/user-attachments/assets/3341772f-6b57-49c8-9845-83f42d77f398)
This UI is in Latvian, but it is the first input field in the General section.

Fix for transcription issue may come some time later. Need to find a testing device. Or maybe some other developer will find time to look at this.

**Comment by raivisdejus** [comment]
See the latest version https://github.com/chidiwilliams/buzz/releases
