### ISSUE TITLE
[Enhancement]Dark mode for Windows

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#922]
Dark mode will be great addition to this amazing tool. Thank you.

**Comment by raivisdejus** [comment]
As dark mode fan I agree! Will see what we can do.

**Comment by raivisdejus** [comment]
Dark theme support for Windows has been added.

You can test it in latest development version.
1. Log into the Github
2. Get installation files from latest development build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

**Comment by mriamnobody** [comment]
Thanks a lot @raivisdejus for quick implementation of Dark mode. If I use these builds, will there be support for GPU as the installation info page says GPU support is only available for PIP installation and building from source.

**Comment by raivisdejus** [comment]
@mriamnobody Yes the latest development build should also have GPU support for Windows. That is second improvement from Yesterday :)

Documentation will be updated once we release the new version some day later.

**Comment by mriamnobody** [comment]
> @mriamnobody Yes the latest development build should also have GPU support for Windows. That is second improvement from Yesterday :)
> 
> Documentation will be updated once we release the new version some day later.

Cheers.
