### ISSUE TITLE
You can’t open the application “Buzz.app” because this application is not supported on this Mac

### ISSUE THREAD

**Issue by chuyizhang23** [chidiwilliams/buzz#924]
I usually use the homebrew version, today, I suddenly got this error message. I reinstalled with dmg and that doesn't solve the problem.

macOS Sequoia 15.0(24A335)

**Comment by raivisdejus** [comment]
Guessing you have an Intel Mac. You need to:
1. Log into the github
2. Go to the section of latest development releases https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
3. Download `Buzz-macOS-X64` dmg file.

Future releases will have Intel installation files in the releases section

**Comment by raivisdejus** [comment]
Will close, feel free to re-open if there are more questions

**Comment by ibeee9** [comment]
I was having the same issue but this resolved my problem. Now is there a way to use whisper model .pt file as in windows to be placed inside models folder directly on a pc with limited internet access in my company.

**Comment by raivisdejus** [comment]
@ibeee9 Yes, Buzz can be used without internet connection if you download the necessary models on some other computer that has the internet and manually move them to the offline computer. The easiest way to find where the models are stored is to go to Help -> Preferences -> Models. Then download some model, and push "Show file location" button. This will open the folder where the models are stored. Copy the models folder to the offline computer. On MacOS you need to copy the `/Users/yourUserName/Library/Caches/Buzz/Models` folder .
