### ISSUE TITLE
[Resolved] Whisper large v3 turbo support

### ISSUE THREAD

**Issue by yieme** [chidiwilliams/buzz#925]
Any possibility of adding support for https://huggingface.co/openai/whisper-large-v3-turbo

**Comment by raivisdejus** [comment]
Buzz already supports Turbo models. The "Huggingface" Whisper type in Buzz is running on the transformers engine, that supports the turbo models. To run it on Windows with GPU support you will need to wait for `1.2.0` release or get the latest development version from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
To see the download link you need to log into the Github.

Then select **Huggingface** whisper type and in the Huggingface model ID input box search for "openai" or "turbo" or paste "openai/whisper-large-v3-turbo"
