### ISSUE TITLE
[Bug]Dark Mode Text and Menus Appear Whitewashed in Windows 11 Build

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#928]
**Environment:**
OS: Windows 11 (26100.1882)
Python: 3.10.7
Buzz Version:  [This action run](https://github.com/chidiwilliams/buzz/actions/runs/11181865374)
CUDA Version: 12.1

I have just installed the latest build of Buzz from [this action run](https://github.com/chidiwilliams/buzz/actions/runs/11181865374) on Windows 11, specifically to test the dark mode feature. However, I encountered an issue where most of the text and menus appear to be completely whitewashed, making it difficult to see or interact with the UI elements.

Please let me know if I can provide any further information or logs to help resolve this issue.

**EDIT**: Please add a toggle or setting to switch between modes.

![Screenshot 2024-10-05 120925](https://github.com/user-attachments/assets/30625064-fd2d-4da5-91fb-6ba985a71c03)
![Screenshot 2024-10-05 120923](https://github.com/user-attachments/assets/5781d2a6-dee7-4116-8a8c-94542ec7674f)
![Screenshot 2024-10-05 120912](https://github.com/user-attachments/assets/d6014a1b-555a-4c7d-9949-3c0316e2a9f6)
![Screenshot 2024-10-05 120903](https://github.com/user-attachments/assets/d838c2f6-4b1d-4d19-9500-1feb148334c0)

**Comment by raivisdejus** [comment]
@mriamnobody I added necessary fixes to make dark theme look proper on Windows 11. You can test it in the latest development build from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

For Buzz I try to keep settings to the minimum, so they do not confuse new users. Currently dark theme will read setting from the OS and if the user has enabled dark mode for apps it will switch Buzz to the dark theme. Nice, easy and everything is automatic.

If you see a scenario or workflow where additional custom setting for the dark theme is needed we can implement an advanced preference like we have some here https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences
This would keep settings section clean and simple, but would also give more advanced users a way to set the settings in the OS to get the result they need.

**Comment by mriamnobody** [comment]
> @mriamnobody I added necessary fixes to make dark theme look proper on Windows 11. You can test it in the latest development build from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

Just downloaded and installed the build. Thanks a lot for fixing the error.






> For Buzz I try to keep settings to the minimum, so they do not confuse new users. Currently dark theme will read setting from the OS and if the user has enabled dark mode for apps it will switch Buzz to the dark theme. Nice, easy and everything is automatic.
> 
> If you see a scenario or workflow where additional custom setting for the dark theme is needed we can implement an advanced preference like we have some here https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences This would keep settings section clean and simple, but would also give more advanced users a way to set the settings in the OS to get the result they need.

Good strategy. Sound good to me.
