### ISSUE TITLE
Using Buzz with alternative Whisper OpenAI-API-compatible server

### ISSUE THREAD

**Issue by PierreMesure** [chidiwilliams/buzz#948]
Hi,

I find it really hard to find a good app to use Whisper on Windows so thank you for making Buzz, it has great potential!

I tried to use it with my own private Whisper server (I use [faster-whisper-server](https://github.com/fedirz/faster-whisper-server))

It worked for a while but then I tried to change the default model on the server side and it stopped working in Buzz. I reset the values but it didn't solve it, I'm now stuck with this error message instead of the transcription:
`Error: 'ascii' codec can't encode character '\xf6' in position 8: ordinal not in range(128)`

I'm not sure how to give you more information on this bug. Anyhow, I think it could be useful to allow for the creation of custom API models in the settings in order to be able to set custom names. Or even better, fetch the list of models available at the endpoint from `v1/models` 😊

**Comment by PierreMesure** [comment]
I just found the source of the problem! I had a non-supported character in the password field 🙈🙈🙈.
My password was "lösenord" and now that I changed to "losenord", it works again!

I'm so irritated at myself but at the same time, I think this bug should be fixed and if it can't, a warning message should be added if the password has wrong characters!

**Comment by raivisdejus** [comment]
@PierreMesure Thanks for figuring this out. There have been previous reports of this that had no known cause. I have added a check for non-base64 characters to the Preferences screen. This should make use of Custom APIs more stable.

Development version with this fix is available https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

Regarding getting models from the API, yes, this is also a good idea. Will look into it.

**Comment by raivisdejus** [comment]
Not all APIs support `/models` endpoint and in case of groq.com the models endpoint has many non-audio models. So for now I do not think there is much benefit in getting models list from API as it will work only some times.
