### ISSUE TITLE
Buzz not Working

### ISSUE THREAD

**Issue by adijahangir123** [chidiwilliams/buzz#952]
I have downloaded buzz in windows 10 but whenever i try to run a transcription, it generates following error

```
### > Traceback (most recent call last):
> 
> File "multiprocessing process.py", line 314, in_bootstrap File "multiprocessing process.py", line 108, in run
> 
> File "buzz transcriber\whisper.file transcribe.py", line 104, in transcribe_whisper
> 
> File "buzz transcriber\whisper file transcriber.py", line 200, in transcribe openai whisper
> 
> "whisperinit.py", in load_model File "torch serialization.py", Line 1005, in load
> 
> File
> 
> with open zipfile_reader(opened_file) as opened.zipfile:
> 
> File "torch serialization.py", line 457, in _init_ super()._init__(torch._C.PyTorchFileReader(name_or_buffer))
> 
> RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
> File "main.py", line 4, in <module>
> 
> File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
> 
> File "buzz buzz.py", line 38, in main
> 
> File "multiprocessing\spawn.py", line 122, in spawn_main File "multiprocessing spawn.py", line 135, in main
> 
> File "multiprocessing\process.py", line 329, in_bootstrap AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by raivisdejus** [comment]
@adijahangir123 let's try to figure this out. I assume you have latest version 1.1.0 from the releases section. Do other whisper types like Whisper.cpp work?

One option you can try is to reinstall the Buzz. 
Another option is to get latest development version from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

Also do you have any custom security tools or anti virus installed? Or maybe Buzz is installed on some network drive or in some non-standart location?

**Comment by raivisdejus** [comment]
@adijahangir123 comments on the internet seem to indicate that problem may be caused by corrupt model file. Go to Preferences -> Models and delete / re-download the model file and see if that fixes the issue
