### ISSUE TITLE
Just crush when I click "Run"

### ISSUE THREAD

**Issue by gogolevmatvey** [chidiwilliams/buzz#956]
So I tried Whisper Largev3 and tiny, Faster Whisper Larvev3 and tiny. Task Transcribe, language English, export TXT. Windows 11

**Comment by raivisdejus** [comment]
@gogolevmatvey Can you please check the logs. Paste this in Windows address bar `%USERPROFILE%\AppData\Local\Buzz\Buzz\Logs` and check what is in the `logs.txt`

Does your PC have a GPU? If so what GPU is it? 

Also please try some `Whisper.cpp` model size. Whisper.cpp will use CPU so may help us identify some GPU related issues.

If the export TXT is checked Buzz will save the transcript to the same location where the input audio or video file is located. Is this location regular folder or maybe some network drive. 

Something strange is happening on your system that is not usually happening. Let's see if we can debug what is causing this.
Feels like you may be running into some issue with `ffmpeg`. Did you install the Buzz v1.1.0 with the installer from the releases section or by some other means?

**Comment by gogolevmatvey** [comment]
Sorry, I forgot to tell that I'm trying to transcribe YouTube video by URL. It's only now that I realized that maybe it's not supported. 
I have rtx 2060.
Same with Whisper.cpp
I installed from the releases section.

**Comment by raivisdejus** [comment]
@gogolevmatvey  Support for YouTube urls via `File -> Import Url` was fixed recently. You can get the version where this works here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

To download you will need to log into the Github.

**Comment by gogolevmatvey** [comment]
@raivisdejus I don't understand how to get it there

**Comment by raivisdejus** [comment]
@gogolevmatvey Yes, first time around this can be a bit confusing. Hope the screenshots will help.

So first you need to select any latest build in the link I posted above.
![attels](https://github.com/user-attachments/assets/af5b98f9-e5ea-4169-b026-2ea929e93408)

Then scroll down to the artifacts section and click the download icon near `Buzz-Windows-X64`
![attels](https://github.com/user-attachments/assets/2e49d5cf-16b2-414e-9cb8-f96cf32611a0)
You need to be logged in to the Github to see the download link.

A `.zip` file will be downloaded, unzip it and the Buzz installation will be in it.

**Comment by gogolevmatvey** [comment]
@raivisdejus Sorry, I just needed to scroll down
