### ISSUE TITLE
Feature Request : Suggest the option to change the path of a folder location Buzz 

### ISSUE THREAD

**Issue by SWxEng** [chidiwilliams/buzz#972]
Hi Chidi Williams

Buzz 

C:\Users\www\AppData\Local\Buzz\Buzz\Cache\models

to

D:\Buzz\Buzz\Cache\models

The reason is that I do not have the disk C size

![image](https://github.com/user-attachments/assets/f040f8dd-0b32-4a51-bb00-144d7856751c)

**Comment by raivisdejus** [comment]
Please see `BUZZ_MODEL_ROOT` variable that is available as Advanced preference https://chidiwilliams.github.io/buzz/docs/preferences#available-variables

Curious if you know how to set environment variables for your computer or maybe a link to some tutorial for this is needed in the documentation.

**Comment by abandon-alt** [comment]
> 请参阅可用作 高级首选项 https://chidiwilliams.github.io/buzz/docs/preferences#available-variables 的变量`BUZZ_MODEL_ROOT`
> 
> 想知道您是否知道如何为您的计算机设置环境变量，或者文档中需要一些相关教程的链接。

请问如果是windows系统应该在哪改动呢，非常感谢
