### ISSUE TITLE
is not working 

### ISSUE THREAD

**Issue by Chenghao999** [chidiwilliams/buzz#974]
Hi!
i download https://github.com/chidiwilliams/buzz/releases/download/v1.1.0/Buzz-1.1.0-mac.dmg for Mac edition, however it is not working. 
is this only for arm chips?

Mac mini
Mac os: 14.6.1
CPU: 3.2 GHz 6 core Intel Core i7

**Comment by raivisdejus** [comment]
Next release will have a `.dmg` file for Intel chips in the release section. 

For now you can get the latest development version for Intel and Arm chips from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

1. select any latest build
2. scroll down to the artifacts section
3. download `Buzz-macOS-X64` for Intel Macs (to see the download link you have to be logged in the Github)
