### ISSUE TITLE
YouTube: "Sign in to confirm you're not a bot"

### ISSUE THREAD

**Issue by gogolevmatvey** [chidiwilliams/buzz#975]
Hi, I'm trying to transcribe by youtube url and get a error:  "Failed (ERROR: [youtube] link: Sign in to confirm you're not a bot. This helps protect our community.Learn more)". How to fix it?

**Comment by raivisdejus** [comment]
@gogolevmatvey According to this https://github.com/yt-dlp/yt-dlp/issues/3766  Your IP has been blocked by YouTube. 

I see two possible solutions:
- Use a different IP, or some proxy.
- Use `yt-dlp` to manually download audios

 At this point I do not see any easy way to fix this.

**Comment by raivisdejus** [comment]
I have an idea how this could be fixed

**Comment by raivisdejus** [comment]
@gogolevmatvey Latest development version has support for a cookie file to access private videos or as a workaround for anti bot systems.

See https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp for information on how to get a cookie file

Pass path to the cookie file via `BUZZ_DOWNLOAD_COOKIEFILE` environment variable. For more information see https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences

To download latest development version:
1. Go here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
2. Select latest build and scroll down to the artifacts section
3. Ensure you are logged in the Github and download the installation file.
