### ISSUE TITLE
[Suggestion]Duplicate Transcription for Previously Processed URLs

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#979]
When using the app to transcribe videos from a URL, I noticed that if a URL has already been processed and transcribed, re-entering the same URL triggers another transcription. Instead, the app should either provide an error message or an alert to indicate that this URL has already been transcribed, avoiding redundant processing.

**Comment by raivisdejus** [comment]
In some specific use cases I see that this would be useful, but for now there are no plans to implement such feature. 

For now it is up to the user to check what to add to the Buzz.
