### ISSUE TITLE
[Suggestion]Enable URL Copying from "File Name/URL" Column in App

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#980]
In the "File Name/URL" column displays the file name for uploaded files and the URL when a link (e.g., a YouTube URL) is used for transcription. There’s currently no way to copy the URL directly from the app once it appears in this column, making it difficult to retrieve or reuse the URL later.

We can add a right-click or context menu option to copy the URL.

**Comment by mriamnobody** [comment]
Below mentioned suggestions are related this one:

https://github.com/chidiwilliams/buzz/issues/979
https://github.com/chidiwilliams/buzz/issues/980

**Comment by mriamnobody** [comment]
My suggestion is to add a new column before the File Name/URL column to indicate whether the entry is a URL or a file. We could then rename File Name/URL to Title. For copying functionality, we could add a right-click option called Copy URL for URLs and Copy Location for files (or simply omit the copy feature for files if preferred). Just sharing my two cents. I hope this helps!

**Comment by raivisdejus** [comment]
@mriamnobody good idea, thanks for suggestion!

Next version will have an ability to copy the contents of "File name / URL" column. CTRL+C (or equivalent on Macs) will copy file name or url of selected row or rows to the clipboard, so you can do CTRL+V to paste it.

You can get this feature from the latest development builds.
1. Go to https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
2. Scroll down to the artifacts section and download the installation files. To see the downlaod link you need to be logged in the Github.

**Comment by mriamnobody** [comment]
Thanks a lot @raivisdejus for quick implementation of the suggestion. Cheers.
