### ISSUE TITLE
Wrong transcribation

### ISSUE THREAD

**Issue by gogolevmatvey** [chidiwilliams/buzz#981]
I'm trying to transcribe 20 min long [youtube video](https://www.youtube.com/watch?v=iIRyCYx28GM) in english with different models and that what I'm getting:
Whisper Large-v3 and Whisper.cpp Large-v3
![image](https://github.com/user-attachments/assets/40e43279-eecb-4572-9543-bef5c43844b4)
Whisper Base and Whisper.cpp Base
![image](https://github.com/user-attachments/assets/e90fc7fe-4a52-4309-bdb6-977d6972ca5d)
Whisper Medium
![image](https://github.com/user-attachments/assets/31afe788-c96e-4c7d-b665-3a3af9b7e961)
Whisper.cpp Medium
![image](https://github.com/user-attachments/assets/3923d359-df75-4b2d-8d26-f09d19a6d082)
Whisper Tiny 
![image](https://github.com/user-attachments/assets/d8c009a6-22f9-4d41-b369-74076d442a8b)
Whisper.cpp Tiny
![image](https://github.com/user-attachments/assets/570e3c85-a6d4-4417-91a3-8b2b53883aa2)

**Comment by raivisdejus** [comment]
@gogolevmatvey Effects like this usually happen when audio is corrupt. There was an issue with downloading and processing of Youtube videos that we recently fixed. Can you try latest development version from here https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

1. Take latest build
2. Scroll down to the artifacts section
3. Download installation file (you need to be logged in to the Github to see the download link)

I tested this video on my system and it was transcribed ok with Whisper.cpp tiny model.

**Comment by raivisdejus** [comment]
Please see the latest version https://github.com/chidiwilliams/buzz/releases
The issue should be solved
