### ISSUE TITLE
UI language set to Russian

### ISSUE THREAD

**Issue by woflmao** [chidiwilliams/buzz#983]
Title, I downloaded the latest windows exe and the UI language is set to Russian, is there any way to change that?

**Comment by raivisdejus** [comment]
@woflmao Buzz will detect supported languages automatically, are you in Russia or is any of the supported languages on your computer Russian?

To get additional information, please see this https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#troubleshooting
And share the part from the logs that has language codes in it

**Comment by woflmao** [comment]
Thank you that fixed the problem! I had Ukrainian as a language pack, I'm unsure why it used that though, no other application has ever used that as a default, is there a way to keep my language pack installed and have the UI remain in English?

Also apologies for labeling Ukrainian as Russian, I am not very familiar with the differences between the two languages!

**Comment by raivisdejus** [comment]
@woflmao Next version will have option to override locale via an advanced preference environment variable `BUZZ_LOCALE`. For more info see https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences

To get the latest development version with this feature:
1. Take latest development build from https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
2. Scroll down to artifact section
3. Download installation file. To see download button, you need to be logged in the github.
