### ISSUE TITLE
Can't install…

### ISSUE THREAD

**Issue by iannismccluskey** [chidiwilliams/buzz#991]
Hi,

I paid for the Buzz app (through Apple App Store) 30 minutes ago but I simply can't install it. Having tried the old open source version, I thought giving your new paid one a try. Still, could you refund me, please.

<img width="276" alt="Screenshot Buzz" src="https://github.com/user-attachments/assets/58b0d1b7-ed11-44fb-8e7d-174b0315c039">

**Comment by raivisdejus** [comment]
As community helper I can help to point you to this link https://github.com/chidiwilliams/buzz/discussions/443


Also this may be relevant about getting the latest version of the open source app https://github.com/chidiwilliams/buzz/issues/974

**Comment by raivisdejus** [comment]
I hope the notes in the links above helped you sort the issue out. Anything refunds related should be handled thru App store if there is such an option. 

Also you can check out the latest version that has some Mac related improvements and fixes.

Will close the issue, feel free to re-open if necessary

**Comment by iannismccluskey** [comment]
Hi,

No, there doesn't seem to be such a feature in the App store. I finally managed to install it. Though, in the meantime, I found a solution better suited for my needs. Anyway, thanks for the help.

Iannis McCluskey
41 Rue Albert Walter
93200 Saint-Denis
***@***.***
+33 7 69 35 68 22
