### ISSUE TITLE
[Question]Is there an option to Automatically Start Transcribing/Translating when importing URL?

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#997]
Buzz currently requires manual intervention to start the transcription or translation process after importing a file or URL. For files, this is manageable as multiple files can be imported at once for transcription or translation. However, this process becomes tedious when working with multiple URLs, as I need to individually add each URL, select a model, and choose the task (transcription or translation).

Is there an existing option or setting to configure Buzz to automatically begin transcribing or translating immediately after importing a file or URL? If not, it would be great to have a toggle or setting that users can enable.

Additionally, an option for the bulk import of URLs would be a fantastic addition alongside the above feature.

Thank you.

**Comment by raivisdejus** [comment]
@mriamnobody Thanks for pointing this out. The easiest way to add new tasks to the Buzz is via CLI. URL import option did not work there previously, but now ability to import urls via CLI has been added to the latest development version. 

Info on CLI - https://chidiwilliams.github.io/buzz/docs/cli
Info on getting latest development version - https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version

**Comment by mriamnobody** [comment]
> @mriamnobody Thanks for pointing this out. The easiest way to add new tasks to the Buzz is via CLI. URL import option did not work there previously, but now ability to import urls via CLI has been added to the latest development version.
> 
> Info on CLI - https://chidiwilliams.github.io/buzz/docs/cli Info on getting latest development version - https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version

That was quick. Thank you @raivisdejus. Can we add something similar to GUI as well? This will a good addition.

**Comment by mriamnobody** [comment]
Getting error while trying to run new builds as mentioned in #1000.

![Screenshot 2024-11-24 071833](https://github.com/user-attachments/assets/05c2d7c2-0aa4-4003-9fd5-6b3d3422754e)

**Comment by raivisdejus** [comment]
Crash is fixed in the latest development version.

Adding ability to import multiple URLs in UI is a bit more tricky, so for now a CLI would be a way to do it.
