### ISSUE TITLE
Function suggestion

### ISSUE THREAD

**Issue by Chenghao999** [chidiwilliams/buzz#998]
hi!
in my using i suggestion add any function to improve usability.
- add a  `hidden` in downloading window, because i can not operate else when it is downloading.
- add a `import URL` icon next to `import file`, because i some mac did not care menu bar, like me.

**Comment by raivisdejus** [comment]
@Chenghao999 Thanks for your suggestions. Good and useful ideas. 

I have added URL import icon to the latest development version. Please see info on how to get the latest development version here https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version

Ability to hide the download indicator for models is visible only first time model is downloaded and can have important information to the users, so will not hide it at this time. This should not be too much of an issue to the users as downloaded models will be cached, so this will be visible only for the first time the model is downloaded.
