### ISSUE TITLE
CLI gives error with -wt and --word-timestamps flags

### ISSUE THREAD

**Issue by jitendra-koodo** [chidiwilliams/buzz#999]
This is the documented flag : https://chidiwilliams.github.io/buzz/docs/cli

running with any of these flags gives following error :

Buzz: Unknown option 'w'
Buzz: Unknown option 'word-timestamps'

**Comment by raivisdejus** [comment]
@jitendra-koodo This feature will be available in the next release. Right now you can get it in the latest development build. 
Please see https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version on how to get the latest development version.

Added note to the documentation so this is less confusing
